<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Lecture: T-Tests: One, Two, Paired</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-f3d32509bb0d2f779b0d504f04cffa98.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture: T-Tests: One, Two, Paired – UMD Biostatistics">
<meta property="og:description" content="The hypothesis-testing framework, the t-distribution, and one-sample, two-sample (Student’s and Welch’s), and paired t-tests — with assumption checks and degrees of freedom made explicit — on the pine needle data the class collected.">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture: T-Tests: One, Two, Paired</h1>
  <p class="subtitle">Comparing means</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry
</div>
</div>
</div>

</section>
<section id="where-we-left-off" class="slide level2 scrollable">
<h2>Where We Left Off</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Last time:</p>
<ul>
<li>Histograms / frequency distributions</li>
<li>Probability distribution functions (PDFs)</li>
<li>Z-scores and t-scores</li>
<li>Tests of means using t-tests: one sample, two sample</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea from last lecture</strong></p>
<p>A t-score is just a z-score computed with the <em>sample</em> standard deviation instead of the population standard deviation<br>
— that substitution is why we need the t-distribution at all. Today we put it to work.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-536528302.png" style="width:2.51in;height:3.44in"></p>
<figcaption>Diagram of a large circle labeled ‘population’ with dots representing individuals and Greek-letter parameters (mu, sigma, sigma-squared), with orange arrows showing a subset of dots being drawn down into a small circle labeled ‘sample’ with its statistics (y-bar, s, s-squared), illustrating that a sample is used to estimate unknown population parameters.</figcaption>
</figure>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Today’s roadmap</strong></p>
<ol type="1">
<li>Hypothesis testing framework</li>
<li>The t-distribution and <strong>degrees of freedom</strong></li>
<li>One-sample t-test — two-tailed and one-tailed</li>
<li>Two-sample t-test (Student’s and Welch’s)</li>
<li>Paired t-test</li>
<li>Checking assumptions throughout</li>
</ol>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-1-our-data" class="slide level2 divider">
<h2>Part 1 · Our Data</h2>
</section>
<section id="setup-one-source-line-two-tools" class="slide level2">
<h2>Setup — One <code>source()</code> Line, Two Tools</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a aria-label="2"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-3"><a aria-label="3"></a><span class="fu">library</span>(car)   <span class="co"># qqPlot(), leveneTest()</span></span>
<span id="cb1-4"><a aria-label="4"></a></span>
<span id="cb1-5"><a aria-label="5"></a><span class="fu">source</span>(<span class="st">"themes_functions/r_themes_and_functions.R"</span>)</span>
<span id="cb1-6"><a aria-label="6"></a></span>
<span id="cb1-7"><a aria-label="7"></a>pine_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/pine_data.csv"</span>)</span>
<span id="cb1-8"><a aria-label="8"></a></span>
<span id="cb1-9"><a aria-label="9"></a>pine_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 64 × 6
   source_file            team  replicate side  needle_length_mm needle_width_mm
   &lt;chr&gt;                  &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;           &lt;dbl&gt;
 1 Bartell_Shingledecker… grac…         1 sunny             18.4            0.79
 2 Bartell_Shingledecker… grac…         2 sunny             12.5            0.99
 3 Bartell_Shingledecker… grac…         3 sunny             17.7            1.12
 4 Bartell_Shingledecker… grac…         4 sunny             14.0            0.94
 5 Bartell_Shingledecker… grac…         5 sunny             14.2            1   
 6 Bartell_Shingledecker… grac…         6 sunny             19.2            0.99
 7 Bartell_Shingledecker… grac…         7 sunny             10.9            0.81
 8 Bartell_Shingledecker… grac…         8 sunny             17.3            1.29
 9 Bartell_Shingledecker… grac…         1 shady             16.6            0.75
10 Bartell_Shingledecker… grac…         2 shady             17.0            0.84
# ℹ 54 more rows</code></pre>
</div>
</div>
<p><a href="data/pine_data.csv" class="btn btn-primary" download="pine_data.csv">📥 Download the data</a> <a href="themes_functions/r_themes_and_functions.R" class="btn btn-primary" download="r_themes_and_functions.R">📥 Download the tools script</a></p>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ What <code>source()</code> just gave you</strong></p>
<ul>
<li><code>theme_regular()</code> — the publication theme from the Graphing lecture</li>
<li><code>summary_stats()</code> — hand it a column of numbers, get back <code>n</code>, <code>mean</code>, <code>sd</code>, <code>se</code> and a 95% CI</li>
</ul>
<p>Save the file in a <strong><code>themes_functions/</code></strong> folder in your project and this exact line works. One line at the top of a script, and both tools are available for the rest of the semester — fix the theme once, and every figure in every script updates.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Recap</strong></p>
<p>This is the data <strong>you</strong> collected: <code>team</code> is your field team (one tree each), <code>side</code> is sunny vs.&nbsp;shady, <code>replicate</code> is which of the 8 needles.</p>
<p>64 rows — but only <strong>4 trees</strong>.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="look-at-all-the-data-spread" class="slide level2">
<h2>Look at All the Data — Spread</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a>raw_box_plot <span class="ot">&lt;-</span> pine_df <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a aria-label="2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(side, needle_length_mm)) <span class="sc">+</span></span>
<span id="cb3-3"><a aria-label="3"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb3-4"><a aria-label="4"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.08</span>)) <span class="sc">+</span></span>
<span id="cb3-5"><a aria-label="5"></a>  <span class="fu">theme_regular</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span>
<span id="cb3-6"><a aria-label="6"></a></span>
<span id="cb3-7"><a aria-label="7"></a>raw_box_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-02-1.png" alt="Boxplot of needle length for the shady and sunny sides using all 64 raw needle measurements, with every needle plotted as a jittered point in front of the box, showing wide and heavily overlapping spread." width="307"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Start where the data start</strong></p>
<p>This is <strong>every needle we measured</strong> — all 64 rows, 32 per side, exactly as they came out of the field. Before we do anything clever, look at it.</p>
<p>Wide spread. Heavy overlap. Nothing obviously going on.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Why jitter here?</strong></p>
<p>32 needles land on a single x value, so plain <code>geom_point()</code> would stack them into a line and hide the duplicates. <code>position_jitter()</code> nudges them sideways so you can see how many there are.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="look-at-all-the-data-mean-se" class="slide level2">
<h2>Look at All the Data — Mean ± SE</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-label="1"></a>raw_mean_se_plot <span class="ot">&lt;-</span> pine_df <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a aria-label="2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(side, needle_length_mm)) <span class="sc">+</span></span>
<span id="cb4-3"><a aria-label="3"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a aria-label="4"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a aria-label="5"></a>  <span class="fu">theme_regular</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span>
<span id="cb4-6"><a aria-label="6"></a></span>
<span id="cb4-7"><a aria-label="7"></a>raw_mean_se_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-03-1.png" alt="Point and error bar plot of mean needle length plus or minus one standard error for the shady and sunny sides, computed from all 64 raw needles, showing very short error bars." width="307"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Those error bars are a lie</strong></p>
<p>They look <strong>tight</strong> — and tight error bars feel like strong evidence. They are computed as SD / √n with <strong>n = 32</strong>.</p>
<p>But we did not measure 32 independent things per side. We measured <strong>4 trees</strong>, eight times each. The 32 is fake, so the precision is fake.</p>
<p>Hold this picture in your head. We are going to fix it on the next slide and then look again.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="averaging-out-pseudoreplication" class="slide level2">
<h2>Averaging Out Pseudoreplication</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a><span class="co"># The 8 needles from one side of one tree are pseudoreplicates —</span></span>
<span id="cb5-2"><a aria-label="2"></a><span class="co"># average them so each tree/side is ONE data point</span></span>
<span id="cb5-3"><a aria-label="3"></a>p_df <span class="ot">&lt;-</span> pine_df <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a aria-label="4"></a>  <span class="fu">group_by</span>(team, side) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a aria-label="5"></a>  <span class="fu">summarise</span>(<span class="at">needle_length_mm =</span> <span class="fu">mean</span>(needle_length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-6"><a aria-label="6"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb5-7"><a aria-label="7"></a></span>
<span id="cb5-8"><a aria-label="8"></a>shady_df <span class="ot">&lt;-</span> p_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(side <span class="sc">==</span> <span class="st">"shady"</span>)</span>
<span id="cb5-9"><a aria-label="9"></a>sunny_df <span class="ot">&lt;-</span> p_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(side <span class="sc">==</span> <span class="st">"sunny"</span>)</span>
<span id="cb5-10"><a aria-label="10"></a></span>
<span id="cb5-11"><a aria-label="11"></a>p_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  team       side  needle_length_mm
  &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt;
1 botany     shady             16.1
2 botany     sunny             17.3
3 grace_jace shady             15.4
4 grace_jace sunny             15.5
5 one        shady             13.2
6 one        sunny             14.2
7 waterbugs  shady             11.7
8 waterbugs  sunny             13.8</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Why average first?</strong> The true experimental unit here is <em>tree side</em>, not <em>needle</em>.<br>
Treating every needle as independent would inflate our sample size and our confidence<br>
— the same pseudoreplication trap from Getting Started.</p>
<p>This is the <strong>two-stage summary</strong> from Describing Your Data: <code>group_by()</code> down to the unit you actually replicated, <em>then</em> analyse.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ 64 rows became 8</strong></p>
<p>That is not data loss — it is the correct sample size. <strong>n = 4 trees per side.</strong> Every degree of freedom today comes from that 4.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="summary-statistics-the-long-way" class="slide level2">
<h2>Summary Statistics — the Long Way</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-label="1"></a>stats_df <span class="ot">&lt;-</span> p_df <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a aria-label="2"></a>  <span class="fu">group_by</span>(side) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a aria-label="3"></a>  <span class="fu">summarize</span>(</span>
<span id="cb7-4"><a aria-label="4"></a>    <span class="at">n    =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(needle_length_mm)),</span>
<span id="cb7-5"><a aria-label="5"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(needle_length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-6"><a aria-label="6"></a>    <span class="at">sd   =</span> <span class="fu">sd</span>(needle_length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-7"><a aria-label="7"></a>    <span class="at">se   =</span> sd <span class="sc">/</span> <span class="fu">sqrt</span>(n),</span>
<span id="cb7-8"><a aria-label="8"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb7-9"><a aria-label="9"></a>  )</span>
<span id="cb7-10"><a aria-label="10"></a>stats_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  side      n  mean    sd    se
  &lt;chr&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 shady     4  14.1  2.02 1.01 
2 sunny     4  15.2  1.57 0.786</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>This is the block you typed in the Probability activity.</strong></p>
<p>Four lines of <code>summarize()</code> that you will want again in <em>every</em> analysis for the rest of the course — correlation, regression, ANOVA, all of it.</p>
<p>Which is exactly why we turned it into a function.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="summary-statistics-the-summary_stats-way" class="slide level2">
<h2>Summary Statistics — the <code>summary_stats()</code> Way</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-label="1"></a><span class="co"># one group of numbers</span></span>
<span id="cb9-2"><a aria-label="2"></a><span class="fu">summary_stats</span>(p_df<span class="sc">$</span>needle_length_mm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
      n  mean    sd    se ci_lower ci_upper
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1     8  14.7  1.77 0.627     13.2     16.1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-label="1"></a><span class="co"># by group -- group_by() as usual, then reframe()</span></span>
<span id="cb11-2"><a aria-label="2"></a>p_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(side) <span class="sc">%&gt;%</span> <span class="fu">reframe</span>(<span class="fu">summary_stats</span>(needle_length_mm))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  side      n  mean    sd    se ci_lower ci_upper
  &lt;chr&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 shady     4  14.1  2.02 1.01      10.9     17.3
2 sunny     4  15.2  1.57 0.786     12.7     17.7</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-label="1"></a><span class="co"># a different column, no retyping</span></span>
<span id="cb13-2"><a aria-label="2"></a>pine_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(side) <span class="sc">%&gt;%</span> <span class="fu">reframe</span>(<span class="fu">summary_stats</span>(needle_width_mm))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  side      n  mean    sd     se ci_lower ci_upper
  &lt;chr&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 shady    32  1.00 0.208 0.0368    0.929     1.08
2 sunny    32  1.15 0.192 0.0339    1.08      1.21</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea</strong></p>
<p><code>summary_stats()</code> is the same <code>summarize()</code> block, packaged once and <code>source()</code>d forever. It also hands back <code>ci_lower</code> and <code>ci_upper</code> — the 95% confidence interval we build by hand later this lecture.</p>
<p>There is <strong>no new notation</strong> inside it. It takes a column of numbers, calls it <code>x</code>, and computes exactly what you computed on the last slide.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Why <code>reframe()</code> and not <code>summarize()</code>?</strong></p>
<p><code>summarize()</code> wants <strong>one value</strong> per group. <code>summary_stats()</code> hands back a whole <strong>row</strong> — six columns at once — so we use <code>reframe()</code>, which allows that. Same <code>group_by()</code> you already know in front of it.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-same-two-plots-after-averaging" class="slide level2">
<h2>The Same Two Plots, After Averaging</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-label="1"></a>box_plot <span class="ot">&lt;-</span> p_df <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a aria-label="2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(side, needle_length_mm)) <span class="sc">+</span></span>
<span id="cb15-3"><a aria-label="3"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb15-4"><a aria-label="4"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-5"><a aria-label="5"></a>  <span class="fu">theme_regular</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span>
<span id="cb15-6"><a aria-label="6"></a></span>
<span id="cb15-7"><a aria-label="7"></a>box_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-07-1.png" alt="Boxplot of mean needle length for the shady and sunny sides using the four tree-side means per side, with each tree plotted as a point in front of the box." width="307"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-label="1"></a>mean_se_plot <span class="ot">&lt;-</span> p_df <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a aria-label="2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(side, needle_length_mm)) <span class="sc">+</span></span>
<span id="cb16-3"><a aria-label="3"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a aria-label="4"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a aria-label="5"></a>  <span class="fu">theme_regular</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span>
<span id="cb16-6"><a aria-label="6"></a></span>
<span id="cb16-7"><a aria-label="7"></a>mean_se_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-08-1.png" alt="Point and error bar plot of mean needle length plus or minus one standard error for the shady and sunny sides, computed from the four tree-side means per side, showing error bars about twice as long as the raw-data version." width="307"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea · The means did not move. The error bars did.</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">raw needles</th>
<th style="text-align: right;">tree means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n per side</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;"><strong>4</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">shady mean</td>
<td style="text-align: right;">14.12</td>
<td style="text-align: right;"><strong>14.12</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">sunny mean</td>
<td style="text-align: right;">15.21</td>
<td style="text-align: right;"><strong>15.21</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">shady SE</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;"><strong>1.01</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">sunny SE</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;"><strong>0.79</strong></td>
</tr>
</tbody>
</table>
<p>Averaging changed the <strong>means not at all</strong> and <strong>doubled the standard errors</strong>.</p>
<p>That is the whole cost of pseudoreplication, in one table. The raw plot was not more precise — it was just wrong about how much we knew.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 No jitter needed now</strong></p>
<p>Four points per side, so plain <code>geom_point()</code> is enough. And a boxplot of four numbers is a thin thing — which is exactly why we plot the points in front of it.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-pairing-is-hiding-in-plain-sight" class="slide level2">
<h2>The Pairing Is Hiding in Plain Sight</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-label="1"></a>slope_plot <span class="ot">&lt;-</span> p_df <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a aria-label="2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(side, needle_length_mm, <span class="at">group =</span> team)) <span class="sc">+</span></span>
<span id="cb17-3"><a aria-label="3"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb17-4"><a aria-label="4"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-5"><a aria-label="5"></a>  <span class="fu">theme_regular</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span>
<span id="cb17-6"><a aria-label="6"></a></span>
<span id="cb17-7"><a aria-label="7"></a>slope_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-09-1.png" alt="Slope plot with one line per field team joining that team's shady tree mean to its sunny tree mean; all four lines slope the same way." width="307"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Look at the lines before we test anything</strong></p>
<p>The boxes overlap a lot. But <strong>every line slopes the same way.</strong></p>
<p>Hold that thought — it is the whole story of today’s last section.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-2-hypothesis-testing-framework" class="slide level2 divider">
<h2>Part 2 · Hypothesis Testing Framework</h2>
</section>
<section id="hypothesis-testing-the-key-components" class="slide level2 scrollable">
<h2>Hypothesis Testing — the Key Components</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Every test you will ever run starts with the same five lines, <strong>in this order</strong>, written down <em>before</em> you look at the output:</p>
<ol type="1">
<li><strong>Question</strong> — the biology, in plain English. <em>Does the sunny side of a pine tree grow longer needles than the shady side?</em></li>
<li><strong>Prediction</strong> — what you expect to see, and why. <em>Sunny needles will be longer, because more light means more photosynthate available for growth.</em></li>
<li><strong>Null hypothesis (H₀)</strong> — “no effect,” the thing the test actually evaluates. <em>H₀: μ<sub>sunny</sub> = μ<sub>shady</sub></em></li>
<li><strong>Alternative hypothesis (Hₐ)</strong> — what is true if H₀ is not. <em>Hₐ: μ<sub>sunny</sub> ≠ μ<sub>shady</sub></em></li>
<li><strong>Significance level (α)</strong> — your threshold, chosen up front. Typically <strong>α = 0.05</strong>.</li>
</ol>
<p><strong>Decision rule:</strong> reject H₀ if p &lt; α.</p>
</div><div class="column" style="width:40%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>The prediction and the alternative are not the same thing</strong></p>
<p>The <strong>prediction</strong> is directional and biological — <em>sunny is longer</em>. The <strong>alternative hypothesis</strong> here is two-tailed — <em>they differ</em>, either way.</p>
<p>If your prediction is genuinely directional and you commit to it beforehand, you can run a one-tailed test. Deciding that <em>after</em> seeing the data is cheating.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reference</strong></p>
<p>Gotelli &amp; Ellison, <em>A Primer of Ecological Statistics</em>, Ch. 4 — Framing and Testing Hypotheses.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-logic-of-a-statistical-test" class="slide level2">
<h2>The Logic of a Statistical Test</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>A test assesses the likelihood of the null hypothesis being true.</p>
<ul>
<li>If H₀ is likely false, Hₐ is assumed correct</li>
<li>More precisely: the long-run probability of obtaining our sample value (or a more extreme one) <strong>if the null hypothesis is true</strong></li>
<li>Written p(data | H₀) — the probability of the data, <em>given</em> H₀</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea</strong></p>
<p>p(data | H₀) is <strong>not</strong> the same as p(H₀ | data). A t-test never tells you the probability that H₀ is true — only how surprising your data would be if it were.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">p-value</th>
<th style="text-align: left;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">p &gt; 0.10</td>
<td style="text-align: left;">No evidence against H₀</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.05 – 0.10</td>
<td style="text-align: left;">Weak evidence against H₀</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.01 – 0.05</td>
<td style="text-align: left;">Moderate evidence against H₀</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.001 – 0.01</td>
<td style="text-align: left;">Strong evidence against H₀</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p &lt; 0.001</td>
<td style="text-align: left;">Very strong evidence against H₀</td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section id="part-3-the-t-distribution" class="slide level2 divider">
<h2>Part 3 · The t-Distribution</h2>
</section>
<section id="one-tailed-questions" class="slide level2">
<h2>One-Tailed Questions</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>One-tailed questions ask about the area of the distribution to the left (or right) of a certain value.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Table-reading example — not our data</strong></p>
<p>A study with <strong>n = 8</strong> has <strong>df = n − 1 = 7</strong>. That is the row highlighted in the table beside this slide, and the only reason 8 and 7 appear together here.</p>
<ul>
<li>95% of the observations fall to the left of <strong>t = 1.895</strong></li>
<li>5% fall outside, in the one tail</li>
</ul>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-1822465473.png" style="width:2.78in;height:2.06in"></p>
<figcaption>Bell-shaped t-distribution curve with the area to the left of the critical value shaded, illustrating a one-tailed cutoff where the shaded region represents the proportion of the distribution below that t-value (here t = 1.895 at df = 7).</figcaption>
</figure>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-4103165911.png" style="width:3.12in"></p>
<figcaption>Student’s t critical-value table with the one-tail 0.05 column and df = 7 row highlighted, intersecting at the critical value 1.895, the value used for a one-tailed test at alpha = 0.05.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="two-tailed-questions" class="slide level2">
<h2>Two-Tailed Questions</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Two-tailed questions refer to the area <em>between</em> certain values.</p>
<p>Same table-reading example — <strong>n = 8, so df = 7</strong>:</p>
<ul>
<li>95% of the observations lie between <strong>t = −2.365 and t = 2.365</strong> (2.5% outside on each side)</li>
<li>Compare to the one-tailed cutoff: t = 1.895 (5% outside)</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-2234740159.png" style="width:2.5in"></p>
<figcaption>Bell-shaped t-distribution curve with both tails shaded beyond the critical values (here t = -2.365 and t = 2.365 at df = 7), illustrating a two-tailed cutoff where the two shaded regions together represent the proportion of the distribution outside that range.</figcaption>
</figure>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-1746531278.png" style="width:3.12in"></p>
<figcaption>Student’s t critical-value table with the two-tail 0.05 column and df = 7 row highlighted, intersecting at the critical value 2.365, the value used for a two-tailed test/95% confidence interval at alpha = 0.05.</figcaption>
</figure>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Notice</strong></p>
<p>The two-tailed critical value is <em>farther</em> from zero than the one-tailed value<br>
— splitting 5% into two tails means each tail only gets 2.5%.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="key-idea-degrees-of-freedom-once-and-for-all" class="slide level2">
<h2>✅ Key Idea · Degrees of Freedom, Once and For All</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>What df means:</strong> the number of values that were free to vary once you estimated a mean. Estimate one mean from n numbers and you spend one df — the last value is pinned down by the others.</p>
<p><strong>So you lose one df for every mean you estimate.</strong></p>
<p>Our data: <strong>4 trees, one shady side and one sunny side each.</strong></p>
<ul>
<li><p><strong>One-sample t-test</strong> — one group, one mean estimated <strong>df = n − 1 = 4 − 1 = 3</strong> (4 shady tree means, compared to a fixed number like 15 mm)</p></li>
<li><p><strong>Two-sample t-test</strong> — two groups, <strong>two</strong> means estimated <strong>df = n₁ + n₂ − 2 = 4 + 4 − 2 = 6</strong> (8 tree means in total, minus one for each group mean)</p></li>
<li><p><strong>Paired t-test</strong> — you first collapse each tree to <strong>one difference</strong>, then it is a one-sample test on those differences <strong>df = n<sub>pairs</sub> − 1 = 4 − 1 = 3</strong> (4 differences, not 8 values)</p></li>
<li><p><strong>Welch’s t-test</strong> — the odd one out. df comes from the Welch–Satterthwaite equation, is usually <strong>not a whole number</strong>, and is always ≤ the Student’s df. Here: <strong>df ≈ 5.66</strong>.</p></li>
</ul>
</div><div class="column" style="width:45%;">
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 34%">
<col style="width: 30%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: left;">What n counts</th>
<th style="text-align: left;">df formula</th>
<th style="text-align: center;">Our df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">One-sample</td>
<td style="text-align: left;">trees in the one group</td>
<td style="text-align: left;">n − 1</td>
<td style="text-align: center;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Two-sample</td>
<td style="text-align: left;">trees in both groups</td>
<td style="text-align: left;">n₁ + n₂ − 2</td>
<td style="text-align: center;"><strong>6</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paired</td>
<td style="text-align: left;"><strong>differences</strong></td>
<td style="text-align: left;">n<sub>pairs</sub> − 1</td>
<td style="text-align: center;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Welch’s</td>
<td style="text-align: left;">both groups, penalised</td>
<td style="text-align: left;">Welch–Satterthwaite</td>
<td style="text-align: center;"><strong>≈ 5.66</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>The number that keeps changing is not arbitrary</strong></p>
<p>n is always <strong>trees</strong>, never needles. What changes is <em>how many means you had to estimate</em> to run the test.</p>
<p>The paired test has half the df of the two-sample test on the <em>identical</em> 8 numbers — because it only ever looks at 4 numbers, the differences.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="calculating-a-confidence-interval" class="slide level2">
<h2>Calculating a Confidence Interval</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Using a two-sided test:</p>
<p><span class="math display">\[\text{CI} = \bar{y} \pm t_{0.975,\,df} \cdot \frac{s}{\sqrt{n}}\]</span></p>
<p><strong>Our own shady-side trees — n = 4, so df = 3:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-label="1"></a>n_shady    <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(shady_df<span class="sc">$</span>needle_length_mm))</span>
<span id="cb18-2"><a aria-label="2"></a>mean_shady <span class="ot">&lt;-</span> <span class="fu">mean</span>(shady_df<span class="sc">$</span>needle_length_mm)</span>
<span id="cb18-3"><a aria-label="3"></a>se_shady   <span class="ot">&lt;-</span> <span class="fu">sd</span>(shady_df<span class="sc">$</span>needle_length_mm) <span class="sc">/</span> <span class="fu">sqrt</span>(n_shady)</span>
<span id="cb18-4"><a aria-label="4"></a>t_crit     <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n_shady <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb18-5"><a aria-label="5"></a></span>
<span id="cb18-6"><a aria-label="6"></a>mean_shady <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> t_crit <span class="sc">*</span> se_shady</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.91210 17.32978</code></pre>
</div>
</div>
<p>And the same interval, for free, from the function we sourced:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-label="1"></a><span class="fu">summary_stats</span>(shady_df<span class="sc">$</span>needle_length_mm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
      n  mean    sd    se ci_lower ci_upper
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1     4  14.1  2.02  1.01     10.9     17.3</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Four trees is a <em>wide</em> interval</strong></p>
<p>With <strong>df = 3</strong> the critical t is <strong>3.182</strong>, not 1.96 and not the 2.365 highlighted in the table image (that is df = 7).</p>
<p>Small n costs you twice: a bigger multiplier <em>and</em> a bigger standard error.</p>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-1746531278.png" style="width:3.12in"></p>
<figcaption>Student’s t critical-value table with the two-tail 0.05 column and df = 7 row highlighted, intersecting at the critical value 2.365, the value used for a two-tailed test/95% confidence interval at alpha = 0.05.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="applications-of-the-t-distribution" class="slide level2">
<h2>Applications of the t-Distribution</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Can assess confidence that the population mean is within a certain range</li>
<li>Can use the t-distribution to ask:
<ul>
<li>“What is the probability of getting a sample with mean = ȳ from a population with mean = µ?” <em>(1-sample t-test, df = n − 1)</em></li>
<li>“What is the probability that two samples came from the same population?” <em>(2-sample t-test, df = n₁ + n₂ − 2)</em></li>
<li>“Is the average <em>change within</em> a subject different from zero?” <em>(paired t-test, df = n<sub>pairs</sub> − 1)</em></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Try it yourself</strong></p>
<p>Before the next slide: which of these three questions does our pine needle design actually ask?</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-4-one-sample-t-test" class="slide level2 divider">
<h2>Part 4 · One-Sample T-Test</h2>
</section>
<section id="one-sample-t-test-question-prediction-hypotheses" class="slide level2 scrollable">
<h2>One-Sample T-Test — Question, Prediction, Hypotheses</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Question:</strong> Is the mean needle length on the shady side different from the 15 mm reported for this species?</p>
<p><strong>Prediction:</strong> Shady needles are shorter than 15 mm, because they are light-limited.</p>
<ul>
<li><strong>H₀:</strong> μ = 15 mm</li>
<li><strong>Hₐ:</strong> μ ≠ 15 mm (two-tailed)</li>
<li><strong>α</strong> = 0.05</li>
</ul>
<p><strong>Assumptions for a t-test:</strong></p>
<ol type="1">
<li>Data are normally distributed</li>
<li>Observations are independent</li>
<li>No significant outliers</li>
</ol>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Degrees of freedom here</strong></p>
<p>One group — the 4 shady tree means. One mean estimated.</p>
<p><strong>df = n − 1 = 4 − 1 = 3</strong></p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reference</strong></p>
<p>Whitlock &amp; Schluter, Ch. 11, covers the one-sample t-test as the simplest hypothesis test on a normally distributed variable.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="checking-normality-qq-plot" class="slide level2">
<h2>Checking Normality — QQ Plot</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-label="1"></a><span class="co"># The one-sample test is on the SHADY side, so that is the group</span></span>
<span id="cb22-2"><a aria-label="2"></a><span class="co"># whose normality we check -- not the two sides pooled.</span></span>
<span id="cb22-3"><a aria-label="3"></a><span class="fu">qqPlot</span>(shady_df<span class="sc">$</span>needle_length_mm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-12-1.png" alt="QQ-plot of shady-side needle length with a confidence envelope, used to check whether the data are approximately normally distributed." width="288"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4 1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-label="1"></a><span class="co"># The base R version -- same idea, no packages, no envelope</span></span>
<span id="cb24-2"><a aria-label="2"></a><span class="fu">qqnorm</span>(shady_df<span class="sc">$</span>needle_length_mm)</span>
<span id="cb24-3"><a aria-label="3"></a><span class="fu">qqline</span>(shady_df<span class="sc">$</span>needle_length_mm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-13-1.png" alt="Base R QQ-plot of shady-side needle length with a reference line added by qqline." width="288"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Notice</strong></p>
<p>Points that hug the line support normality; points that curve away — especially in the tails — are a warning sign.</p>
<p><code>qqPlot()</code> from <strong>car</strong> adds a shaded confidence envelope; base R’s <code>qqnorm()</code> + <code>qqline()</code> gives you the same picture without it. Either is fine.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ With 4 points, this is a sanity check, not proof</strong></p>
<p>Four points will look “fine” on almost any QQ plot.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="checking-normality-shapiro-wilk-test" class="slide level2">
<h2>Checking Normality — Shapiro-Wilk Test</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-label="1"></a><span class="fu">shapiro.test</span>(shady_df<span class="sc">$</span>needle_length_mm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  shady_df$needle_length_mm
W = 0.94326, p-value = 0.6743</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>H₀ for Shapiro-Wilk is “the data ARE normal.”</strong> A <em>non-significant</em> result (p &gt; 0.05) is what we’re hoping for — it means we fail to reject normality.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ With n = 4, this test proves almost nothing</strong></p>
<p>Shapiro-Wilk on four numbers has essentially no power — it will pass almost anything. A high p-value here is <strong>not</strong> evidence that the data are normal; it is evidence that we don’t have enough data to tell.</p>
<p>Run it, report it, but lean on the QQ plot, the biology, and the design.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Why the shady side only?</strong></p>
<p>We test the group the hypothesis is about. Pooling shady and sunny would mix two distributions with different means, which can look non-normal even when each group is perfectly normal.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="checking-for-outliers" class="slide level2">
<h2>Checking for Outliers</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-label="1"></a>box_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-15-1.png" alt="The boxplot with points of needle length by side of tree, repeated here as the outlier check before running the t-tests." width="307"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Reuse the plot you already made</strong></p>
<p><code>box_plot</code> was built once in Part 1 — no reason to retype it. Points beyond the whiskers are potential outliers; always look before you test.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="running-the-one-sample-t-test" class="slide level2 scrollable">
<h2>Running the One-Sample t-Test</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-label="1"></a>one_sample_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(shady_df<span class="sc">$</span>needle_length_mm, <span class="at">mu =</span> <span class="dv">15</span>)</span>
<span id="cb28-2"><a aria-label="2"></a></span>
<span id="cb28-3"><a aria-label="3"></a>one_sample_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  shady_df$needle_length_mm
t = -0.87183, df = 3, p-value = 0.4475
alternative hypothesis: true mean is not equal to 15
95 percent confidence interval:
 10.91210 17.32978
sample estimates:
mean of x 
 14.12094 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Read <code>df = 3</code> in that output</strong></p>
<p>R is telling you exactly what the Degrees of Freedom slide said: 4 shady trees, one mean estimated, <strong>df = 4 − 1 = 3</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Interpret it</strong></p>
<ol type="1">
<li>What was H₀? What was Hₐ?</li>
<li>What does the p-value tell us?</li>
<li>Reject or fail to reject at α = 0.05?</li>
<li>What does that mean for a botanist?</li>
</ol>
</div>
</div>
</div>
</div></div>
</section>
<section id="one-tailed-variation-the-same-test-one-direction" class="slide level2">
<h2>One-Tailed Variation — the Same Test, One Direction</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Our prediction was <strong>directional</strong>: shady needles are <em>shorter</em> than 15 mm. If we commit to that <strong>before</strong> collecting data, we can run a one-tailed test.</p>
<ul>
<li><strong>H₀:</strong> μ ≥ 15</li>
<li><strong>Hₐ:</strong> μ &lt; 15 — all 5% of α in the <em>lower</em> tail</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-label="1"></a>one_tailed_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(shady_df<span class="sc">$</span>needle_length_mm,</span>
<span id="cb30-2"><a aria-label="2"></a>                           <span class="at">mu =</span> <span class="dv">15</span>,</span>
<span id="cb30-3"><a aria-label="3"></a>                           <span class="at">alternative =</span> <span class="st">"less"</span>)</span>
<span id="cb30-4"><a aria-label="4"></a></span>
<span id="cb30-5"><a aria-label="5"></a>one_tailed_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  shady_df$needle_length_mm
t = -0.87183, df = 3, p-value = 0.2237
alternative hypothesis: true mean is less than 15
95 percent confidence interval:
     -Inf 16.49382
sample estimates:
mean of x 
 14.12094 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea</strong></p>
<p><code>alternative = "less"</code> or <code>"greater"</code> is the <em>only</em> thing that changed. Same data, same t, same <strong>df = 3</strong>.</p>
<p>Compare the two p-values:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: left;">Hₐ</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Two-tailed</td>
<td style="text-align: left;">μ ≠ 15</td>
<td style="text-align: right;">0.448</td>
</tr>
<tr class="even">
<td style="text-align: left;">One-tailed</td>
<td style="text-align: left;">μ &lt; 15</td>
<td style="text-align: right;">0.224</td>
</tr>
</tbody>
</table>
<p><strong>Exactly half.</strong> All of α now sits in one tail, so the observed t only has to beat one cutoff instead of two.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Notice the confidence interval changed too</strong></p>
<p>It now runs from <strong>−Inf</strong> to an upper bound. A one-tailed test makes no claim in the direction you ruled out.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="one-tailed-vs.-two-tailed-what-it-costs-you" class="slide level2">
<h2>One-Tailed vs.&nbsp;Two-Tailed — What It Costs You</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Remember the critical values from Part 3. At <strong>df = 3</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a aria-label="1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">3</span>)   <span class="co"># two-tailed, 2.5% in each tail</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.182446</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a aria-label="1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>,  <span class="at">df =</span> <span class="dv">3</span>)   <span class="co"># one-tailed, 5% in one tail</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.353363</code></pre>
</div>
</div>
<p>The one-tailed cutoff (<strong>2.353</strong>) is <em>closer to zero</em> than the two-tailed cutoff (<strong>3.182</strong>). That is the extra power — a smaller t will do.</p>
<p>But run it the other way and watch what happens:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a aria-label="1"></a><span class="fu">t.test</span>(shady_df<span class="sc">$</span>needle_length_mm, <span class="at">mu =</span> <span class="dv">15</span>,</span>
<span id="cb36-2"><a aria-label="2"></a>       <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  shady_df$needle_length_mm
t = -0.87183, df = 3, p-value = 0.7763
alternative hypothesis: true mean is greater than 15
95 percent confidence interval:
 11.74806      Inf
sample estimates:
mean of x 
 14.12094 </code></pre>
</div>
</div>
<p>Same data, same t = −0.87, and now <strong>p = 0.776</strong>.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ The rule that makes one-tailed tests honest</strong></p>
<p>You must pick the direction <strong>before you see the data</strong>, on biological grounds, and you must accept that a result in the <em>other</em> direction tells you nothing — no matter how big it is.</p>
<p>Choosing the tail after looking at your means is not a one-tailed test. It is a two-tailed test with the p-value secretly halved.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 When is one-tailed defensible?</strong></p>
<p>When the opposite result would lead to the <strong>same action</strong> as no result. A drug that makes patients worse and a drug that does nothing are both “do not approve.”</p>
<p>For our pine needles, “sunny is longer” and “shady is longer” are <em>both</em> interesting biology. <strong>Two-tailed is the honest default.</strong></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="visualizing-the-one-sample-test-t-scale" class="slide level2">
<h2>Visualizing the One-Sample Test — t Scale</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-20-1.png" alt="T-distribution curve with 3 degrees of freedom, the two-tailed rejection regions shaded red beyond the critical t-values, and a green line marking the observed t-statistic, which falls inside the non-rejection region." width="326"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea</strong></p>
<p>This curve is drawn with <strong>df = 3</strong>, straight out of <code>one_sample_model</code> — not from a textbook example. The critical value is 3.182, which is why a wide, short-tailed picture like this needs a big t to reach significance.</p>
<p>The green line (our observed t) sits <em>inside</em> the dashed lines — that is what “fail to reject” looks like.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="visualizing-the-one-sample-test-original-units" class="slide level2">
<h2>Visualizing the One-Sample Test — Original Units</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-21-1.png" alt="The same one-sample t-test re-plotted on the millimetre scale, with a blue line at the hypothesized mean of 15mm and a green line at the observed sample mean, and the rejection regions shaded red in each tail." width="326"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Notice</strong></p>
<p>Same test, same conclusion — just relabelled onto the millimetre scale instead of the t scale.</p>
<p>The blue line is H₀ (15 mm), the green line is our sample mean. The green line sits <strong>inside</strong> the dashed critical values, so 15 mm is a perfectly plausible population mean for these four trees.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="interpreting-the-one-sample-t-test" class="slide level2">
<h2>Interpreting the One-Sample T-Test</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Activity: interpret the t-test results</strong></p>
<ul>
<li>What does the p-value tell us?</li>
<li>Should we reject or fail to reject the null hypothesis?</li>
<li>Does the 95% CI from <code>summary_stats()</code> contain 15 mm — and does that agree with the p-value?</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>How to report this result in a scientific paper</strong></p>
<p>“A <strong>two-tailed</strong>, one-sample t-test at α = 0.05 showed that the mean needle length (… mm, SD = …) [was/was not] significantly different from the expected 15 mm, <strong>t(3)</strong> = …, p = …”</p>
<p>Two things you must always report: the <strong>degrees of freedom</strong>, in parentheses after <strong>t</strong>, and whether the test was <strong>one- or two-tailed</strong>.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-5-two-sample-t-test" class="slide level2 divider">
<h2>Part 5 · Two-Sample T-Test</h2>
</section>
<section id="two-sample-t-tests-the-question" class="slide level2">
<h2>Two-Sample T-Tests — the Question</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Question:</strong> Do needles differ in length between the sunny and shady sides?</p>
<p><strong>Prediction:</strong> Sunny needles are longer — more light, more growth.</p>
<ul>
<li><strong>H₀:</strong> μ<sub>shady</sub> = μ<sub>sunny</sub></li>
<li><strong>Hₐ:</strong> μ<sub>shady</sub> ≠ μ<sub>sunny</sub> (direction not specified)</li>
<li><strong>α</strong> = 0.05</li>
</ul>
<p>A two-sample t-test compares means from two <strong>independent</strong> groups.</p>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/two_branches.jpg" style="width:2.12in"></p>
<figcaption>Photo of two separate green pine branches side by side, each with needle clusters, representing the two independent samples (populations X and Y) being compared in a two-sample t-test.</figcaption>
</figure>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Degrees of freedom here</strong></p>
<p>Two groups, <strong>two</strong> means estimated from 8 tree means.</p>
<p><strong>df = n₁ + n₂ − 2 = 4 + 4 − 2 = 6</strong></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="two-sample-t-test-framework" class="slide level2">
<h2>Two-Sample T-Test Framework</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><span class="math display">\[t = \frac{\bar{x}_1 - \bar{x}_2}{S_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}} = \frac{\text{SIGNAL}}{\text{NOISE}}\]</span></p>
<p><strong>Where:</strong></p>
<ul>
<li>x̄₁, x̄₂: sample means of the two groups</li>
<li>s²ₚ: <strong>pooled variance</strong> = [(n₁−1)s₁² + (n₂−1)s₂²] / (n₁+n₂−2)</li>
<li>Sₚ = √s²ₚ: the <strong>pooled standard deviation</strong></li>
<li>Sₚ√(1/n₁ + 1/n₂): the <strong>standard error of the difference</strong> — the whole denominator</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>The df is sitting right inside the formula</strong></p>
<p>Look at the denominator of the pooled variance: <strong>n₁ + n₂ − 2</strong>. That <em>is</em> the degrees of freedom. It is the divisor that turns two sums of squares into one variance estimate, and the same number then indexes the t-distribution you compare your t to.</p>
<p>df is not a rule to memorise — it is whatever you divided by.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reference</strong></p>
<p>Whitlock &amp; Schluter, Ch. 12 — Comparing Two Means.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="checking-assumptions-normality-by-group" class="slide level2">
<h2>Checking Assumptions — Normality by Group</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a aria-label="1"></a>p_df <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a aria-label="2"></a>  <span class="fu">group_by</span>(side) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a aria-label="3"></a>  <span class="fu">summarize</span>(</span>
<span id="cb38-4"><a aria-label="4"></a>    <span class="at">shapiro_p =</span> <span class="fu">shapiro.test</span>(needle_length_mm)<span class="sc">$</span>p.value,</span>
<span id="cb38-5"><a aria-label="5"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  side  shapiro_p
  &lt;chr&gt;     &lt;dbl&gt;
1 shady     0.674
2 sunny     0.516</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Each group separately</strong></p>
<p>For a two-sample test the normality assumption is about the <em>residuals within each group</em>, so test each side on its own — never the pooled column.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="checking-assumptions-equal-variances" class="slide level2">
<h2>Checking Assumptions — Equal Variances</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a aria-label="1"></a><span class="fu">leveneTest</span>(needle_length_mm <span class="sc">~</span> <span class="fu">factor</span>(side), <span class="at">data =</span> p_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  0.6355 0.4557
       6               </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>H₀ for Levene’s test is “the variances are equal.”</strong></p>
<p>You <em>want</em> a non-significant result. If p &gt; 0.05, the standard (Student’s) t-test is fine. If p &lt; 0.05, use Welch’s.</p>
<p><code>leveneTest()</code> needs the grouping variable as a factor.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="conducting-the-two-sample-t-test" class="slide level2">
<h2>Conducting the Two-Sample T-Test</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Standard (Student’s) — equal variances</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a aria-label="1"></a>two_sample_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(needle_length_mm <span class="sc">~</span> side,</span>
<span id="cb42-2"><a aria-label="2"></a>                           <span class="at">data =</span> p_df, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-3"><a aria-label="3"></a></span>
<span id="cb42-4"><a aria-label="4"></a>two_sample_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  needle_length_mm by side
t = -0.85529, df = 6, p-value = 0.4252
alternative hypothesis: true difference in means between group shady and group sunny is not equal to 0
95 percent confidence interval:
 -4.221663  2.034788
sample estimates:
mean in group shady mean in group sunny 
           14.12094            15.21438 </code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><strong>Welch’s — unequal variances</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a aria-label="1"></a>welch_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(needle_length_mm <span class="sc">~</span> side,</span>
<span id="cb44-2"><a aria-label="2"></a>                      <span class="at">data =</span> p_df, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb44-3"><a aria-label="3"></a></span>
<span id="cb44-4"><a aria-label="4"></a>welch_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  needle_length_mm by side
t = -0.85529, df = 5.6627, p-value = 0.4271
alternative hypothesis: true difference in means between group shady and group sunny is not equal to 0
95 percent confidence interval:
 -4.267394  2.080519
sample estimates:
mean in group shady mean in group sunny 
           14.12094            15.21438 </code></pre>
</div>
</div>
</div></div>
</section>
<section id="standard-vs.-welchs-t-test" class="slide level2">
<h2>Standard vs.&nbsp;Welch’s t-Test</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Standard t-test (Student’s)</strong></p>
<ul>
<li><strong>Assumes equal variances</strong> between groups</li>
<li>Uses a <strong>pooled variance estimate</strong> combining both groups</li>
<li><strong>Higher power</strong> when the equal-variance assumption is met</li>
<li><strong>df = n₁ + n₂ − 2 = 6</strong> — a whole number, every time</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Welch’s t-test</strong></p>
<ul>
<li><strong>Does not assume equal variances</strong></li>
<li>Uses <strong>separate variance estimates</strong> for each group</li>
<li>More <strong>robust</strong> when group variances differ</li>
<li><strong>df from the Welch–Satterthwaite equation</strong> — typically <em>not</em> a whole number, and always smaller than n₁ + n₂ − 2. Here <strong>df ≈ 5.66</strong></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 The fractional df is the price of the robustness</strong> — Welch’s buys safety by spending degrees of freedom.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="interpreting-the-two-sample-t-test" class="slide level2">
<h2>Interpreting the Two-Sample T-Test</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>What can we conclude about needle lengths on the sunny vs.&nbsp;shady sides?</strong></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>How to report this result in a scientific paper</strong></p>
<p>“A two-tailed, two-sample t-test at α = 0.05 showed [a significant/no significant] difference in needle length between sunny (M = …, SD = …) and shady (M = …, SD = …) sides of pine trees, <strong>t(6)</strong> = …, p = …”</p>
<p>For Welch’s you report the fractional df exactly as R gives it: <strong>t(5.66)</strong> = …</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-26-1.png" alt="T-distribution curve with 6 degrees of freedom, red rejection regions in both tails beyond the critical t-values, and a dashed blue line marking the observed t-statistic, which falls well inside the non-rejection region." width="326"></p>
</figure>
</div>
</div>
</div>
<p><strong>df = 6</strong> — compare the shape of this curve to the df = 3 one in Part 4.</p>
</div></div>
</section>
<section id="part-6-paired-t-test" class="slide level2 divider">
<h2>Part 6 · Paired T-Test</h2>
</section>
<section id="what-does-a-paired-t-test-tell-us" class="slide level2">
<h2>What Does a Paired T-Test Tell Us?</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Paired t-test:</strong></p>
<ul>
<li>Compares two measurements from the same subject or matched pair</li>
<li>Tests whether the <strong>mean difference</strong> between paired observations equals zero</li>
<li>Uses the <em>differences</em> between pairs as the data</li>
<li>Generally more powerful, because it removes subject-to-subject variation from the noise</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Degrees of freedom here</strong></p>
<p>4 trees → <strong>4 differences</strong> → one mean difference estimated.</p>
<p><strong>df = n<sub>pairs</sub> − 1 = 4 − 1 = 3</strong></p>
<p>Not 6. The 8 numbers became 4 the moment you subtracted.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Order matters for the sign</strong></p>
<p><code>t.test(shady, sunny, paired = TRUE)</code> computes <strong>shady − sunny</strong>. Reverse the arguments and <code>t</code> flips sign — the p-value is identical, but the direction you report is backwards.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a aria-label="1"></a>p_wide_df <span class="ot">&lt;-</span> p_df <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a aria-label="2"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> side,</span>
<span id="cb46-3"><a aria-label="3"></a>              <span class="at">values_from =</span> needle_length_mm)</span>
<span id="cb46-4"><a aria-label="4"></a></span>
<span id="cb46-5"><a aria-label="5"></a><span class="co"># shady first, then sunny -- the SAME order the</span></span>
<span id="cb46-6"><a aria-label="6"></a><span class="co"># two-sample test used</span></span>
<span id="cb46-7"><a aria-label="7"></a>paired_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(p_wide_df<span class="sc">$</span>shady,</span>
<span id="cb46-8"><a aria-label="8"></a>                       p_wide_df<span class="sc">$</span>sunny,</span>
<span id="cb46-9"><a aria-label="9"></a>                       <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-10"><a aria-label="10"></a></span>
<span id="cb46-11"><a aria-label="11"></a>paired_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  p_wide_df$shady and p_wide_df$sunny
t = -2.7227, df = 3, p-value = 0.07238
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.3714897  0.1846147
sample estimates:
mean difference 
      -1.093438 </code></pre>
</div>
</div>
</div></div>
</section>
<section id="same-data-two-different-answers" class="slide level2">
<h2>Same Data, Two Different Answers</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Both tests used exactly the same 8 numbers</strong>, and both measured shady − sunny:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Two-sample</td>
<td style="text-align: right;">−0.855</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.425</td>
</tr>
<tr class="even">
<td style="text-align: left;">Paired</td>
<td style="text-align: right;">−2.723</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.072</td>
</tr>
</tbody>
</table>
<p>Same estimated difference (<strong>−1.09 mm</strong>, shady needles shorter). Same data. The p-value dropped by a factor of <strong>almost six</strong>.</p>
<p>Why?</p>
<ul>
<li>The <strong>two-sample</strong> test throws the pairing away. Tree-to-tree variation (some teams’ trees just have longer needles) lands in the <em>noise</em>, swamping the signal.</li>
<li>The <strong>paired</strong> test looks only at the shady − sunny difference <em>within each tree</em>, so tree-to-tree variation cancels out entirely.</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>And notice it did that on half the degrees of freedom</strong></p>
<p>3 instead of 6 — because it is working with 4 differences, not 8 values. A smaller df makes significance <em>harder</em> to reach. It still won by a mile, because the noise it removed mattered far more than the df it gave up.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>These data are paired by design</strong> — each team measured both sides of the <em>same</em> tree. The two-sample test is not just less powerful, it is answering a question our design never asked.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a aria-label="1"></a>slope_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="t_tests_lecture_files/figure-revealjs/t-tests-28-1.png" alt="The slope plot from Part 1, repeated here: each team's tree is a line joining its shady mean to its sunny mean, and all four lines slope the same way." width="307"></p>
</figure>
</div>
</div>
</div>
<p>Each line is one tree. All four shift the same way — that consistency is exactly what the paired test measures and the two-sample test cannot see.</p>
</div></div>
</section>
<section id="a-paired-test-is-a-one-sample-test" class="slide level2">
<h2>✅ A Paired Test <em>Is</em> a One-Sample Test</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Here is the idea that makes the df finally click. Treat the <strong>shady side as each tree’s own control</strong>, and compute one difference per tree:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a aria-label="1"></a>diff_df <span class="ot">&lt;-</span> p_wide_df <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a aria-label="2"></a>  <span class="fu">mutate</span>(<span class="at">difference =</span> sunny <span class="sc">-</span> shady)</span>
<span id="cb49-3"><a aria-label="3"></a></span>
<span id="cb49-4"><a aria-label="4"></a>diff_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  team       shady sunny difference
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1 botany      16.1  17.3      1.16 
2 grace_jace  15.4  15.5      0.146
3 one         13.2  14.2      0.968
4 waterbugs   11.7  13.8      2.10 </code></pre>
</div>
</div>
<p>Now throw away the pairing language entirely and run a plain <strong>one-sample t-test on those 4 differences, against μ = 0</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a aria-label="1"></a>diff_model <span class="ot">&lt;-</span> <span class="fu">t.test</span>(diff_df<span class="sc">$</span>difference, <span class="at">mu =</span> <span class="dv">0</span>)</span>
<span id="cb51-2"><a aria-label="2"></a></span>
<span id="cb51-3"><a aria-label="3"></a>diff_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  diff_df$difference
t = 2.7227, df = 3, p-value = 0.07238
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -0.1846147  2.3714897
sample estimates:
mean of x 
 1.093438 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Identical. Same t, same df, same p.</strong></p>
<p><code>t.test(sunny, shady, paired = TRUE)</code> and <code>t.test(sunny - shady, mu = 0)</code> are <strong>the same test</strong>. <code>paired = TRUE</code> is nothing more than a convenience that does the subtraction for you.</p>
<p>That is why the paired df is <strong>n<sub>pairs</sub> − 1 = 3</strong> and not n₁ + n₂ − 2 = 6: once you subtract, you genuinely only have <strong>four numbers</strong>. A one-sample test on four numbers has 3 df. Always.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Each tree is its own control</strong></p>
<p>The shady side accounts for everything about that particular tree — its genetics, its soil, its water, its team’s measuring technique. Subtracting removes all of it at once, and what is left is the effect of <em>sun</em>.</p>
<p>This is the same logic as a before/after design, and it is the seed of the blocked designs you will meet in ANOVA.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-7-assumptions-and-wrap-up" class="slide level2 divider">
<h2>Part 7 · Assumptions and Wrap-Up</h2>
</section>
<section id="assumptions-of-parametric-tests" class="slide level2 scrollable">
<h2>Assumptions of Parametric Tests</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Common assumptions for t-tests:</strong></p>
<ol type="1">
<li><strong>Normality</strong> — the data (or, for a paired test, the <strong>differences</strong>) come from a normally distributed population</li>
<li><strong>Equal variances</strong> — two-sample tests only</li>
<li><strong>Independence</strong> — observations are independent</li>
<li><strong>No outliers</strong> — extreme values can dominate a small sample</li>
</ol>
<p>What do we do if our data violate these?</p>
</div><div class="column" style="width:45%;">
<p><strong>Alternatives when assumptions are violated:</strong></p>
<ul>
<li>Data transformation (log, square root)</li>
<li>Non-parametric tests — Mann-Whitney U for two samples, Wilcoxon signed-rank for paired</li>
<li>Robust methods</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Note the paired case</strong></p>
<p>You check normality of the <strong>differences</strong>, not of the two groups. Which follows directly from the last slide — the differences <em>are</em> the data.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="summary-and-conclusions" class="slide level2 scrollable">
<h2>Summary and Conclusions</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>In this lecture we:</p>
<ol type="1">
<li>Went from question → prediction → H₀ / Hₐ → α, before looking at output</li>
<li>Tested assumptions — QQ plot, Shapiro-Wilk, Levene’s</li>
<li>Ran one-sample (two- and one-tailed), two-sample (Student’s and Welch’s), and paired t-tests</li>
<li>Saw that a paired test is a one-sample test on the differences</li>
<li>Learned to read and report <strong>t(df) = …, p = …</strong></li>
</ol>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Degrees of freedom — the one-line version</strong></p>
<ul>
<li>One-sample: <strong>n − 1</strong> = 3</li>
<li>Two-sample: <strong>n₁ + n₂ − 2</strong> = 6</li>
<li>Paired: <strong>n<sub>pairs</sub> − 1</strong> = 3</li>
<li>Welch’s: fractional, ≤ n₁ + n₂ − 2 ≈ 5.66</li>
</ul>
<p>n is <strong>trees</strong>, never needles. You lose one df per mean you estimate.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Key takeaways</strong></p>
<ul>
<li>Always check assumptions before you test</li>
<li>Plot the data before you test</li>
<li>Match the test to the <strong>design</strong>, not to the p-value you want</li>
<li>Non-parametric alternatives are coming up next</li>
</ul>
</div>
</div>
</div>
</div></div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/ecostats_2026");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>