<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Lecture: Correlation vs Linear Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-916d92ef29fae53263df6d6c2ab37a8f.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture: Correlation vs Linear Models – UMD Biostatistics">
<meta property="og:description" content="Correlation and simple linear regression as two halves of one idea: Pearson’s r and Spearman’s rho, the least-squares line, the sums-of-squares partition that turns a fitted line into an ANOVA table, and the residual diagnostics that decide whether any of it can be believed. Uses the Nazca booby, Indian rope trick, lion nose-pigmentation, prairie-biodiversity and Galapagos species-area datasets.">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture: Correlation vs Linear Models</h1>
  <p class="subtitle">Relationships</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry
</div>
</div>
</div>

</section>
<section id="where-we-left-off" class="slide level2">
<h2>Where We Left Off</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Covered last time:</p>
<ul>
<li>A design has two jobs: kill <strong>bias</strong>, shrink <strong>sampling error</strong></li>
<li>Controls, randomization and blinding; replication, balance and blocking</li>
<li>Natural versus manipulative experiments, and what each one licenses you to say</li>
<li><strong>Your design has already chosen your analysis</strong></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Where today sits on that map</strong></p>
<p>Last week ended with a table mapping designs onto analyses. Today is its <strong>first row</strong> — one continuous predictor, one continuous response.</p>
<p>Everything after today adds predictors or changes their type. The machinery stays the same.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-1-overview" class="slide level2 divider">
<h2>Part 1 · Overview</h2>
</section>
<section id="todays-objectives" class="slide level2">
<h2>Today’s Objectives</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Two techniques, one idea — a straight line through a cloud of points:</p>
<ul>
<li><strong>Correlation</strong> — how tightly do two variables move together?</li>
<li><strong>Regression</strong> — what equation predicts Y from X?</li>
<li>Assumptions for each, and what to do when they fail</li>
<li><strong>Sums of squares</strong> — how a fitted line becomes an ANOVA table</li>
</ul>
<p>This lecture runs over <strong>two class days</strong>: correlation first, regression second.</p>
<p><a href="data/booby_aggression.csv" class="btn btn-primary" download="booby_aggression.csv">📥 Booby data</a> <a href="data/rope_trick.csv" class="btn btn-primary" download="rope_trick.csv">📥 Rope trick data</a> <a href="data/lion_noses.csv" class="btn btn-primary" download="lion_noses.csv">📥 Lion data</a> <a href="data/10_correlation_linear_models.R" class="btn btn-primary" download="10_correlation_linear_models.R">📥 Script skeleton (.R)</a></p>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reading</strong></p>
<p>Whitlock &amp; Schluter, Ch. 16 (Correlation) and Ch. 17 (Regression).</p>
<p>Gotelli &amp; Ellison, Ch. 9 (Regression).</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="how-today-works" class="slide level2">
<h2>🗳️ How Today Works</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>🗳️ Six times over the two days, you make the call</strong></p>
<p>Six slides are marked <strong>🗳️ DECIDE</strong>. Each asks a multiple-choice question, and I will <em>not</em> tell you the answer on that slide.</p>
<p><strong>How it works:</strong> write your letter down — actually write it — then hold up fingers 1–4. If the room splits, turn to the person next to you, argue for ninety seconds, and we vote again. Nothing here is graded. The point is that you commit before you find out.</p>
</div>
</div>
</div>
</section>
<section id="part-2-correlation-vs.-regression" class="slide level2 divider">
<h2>Part 2 · Correlation vs.&nbsp;Regression</h2>
</section>
<section id="correlation-vs.-regression-whats-the-difference" class="slide level2">
<h2>Correlation vs.&nbsp;Regression — What’s the Difference?</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Correlation</strong></p>
<ul>
<li>Measures the <strong>strength and direction</strong> of a relationship</li>
<li>Both X and Y are measured; neither is manipulated</li>
<li>The variables are on equal footing — swap them and <em>r</em> is unchanged</li>
<li>One number, from −1 to +1</li>
</ul>
<p><strong>Regression</strong></p>
<ul>
<li>Produces an <strong>equation</strong> predicting Y from X</li>
<li>You <em>assume</em> a direction, X → Y, when you choose which is which</li>
<li>Swap X and Y and you get a <strong>different line</strong></li>
<li>Gives you a slope, an intercept, and predictions</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-02-1.png" alt="Two stacked scatterplots of the same lion data: the top panel shows the correlation view with a confidence ellipse and no predictor/response distinction, the bottom shows the regression view with a fitted line predicting age from proportion black." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="choosing-x-does-not-make-it-a-cause" class="slide level2">
<h2>Choosing X Does Not Make It a Cause</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Regression does not earn you causation</strong></p>
<p><code>lm(y ~ x)</code> will fit a slope to any two numeric columns you hand it, including ones with no causal link at all. Putting a variable on the right-hand side is a <strong>decision you made</strong>, not a finding.</p>
<p>What licenses a causal claim is the <strong>study design</strong> — manipulation, randomization, controls — not the model you fit afterwards.</p>
</div>
</div>
</div>
<p>Last week’s inference gradient, in one line: the same <code>lm()</code> output supports a weak claim from an observational survey and a strong claim from a randomized experiment. <strong>The design decides which one you are allowed to write.</strong></p>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Which do I report?</strong></p>
<ul>
<li>Both variables measured, no direction implied → <strong>correlation</strong></li>
<li>One variable predicts or sets the other, or you want predictions → <strong>regression</strong></li>
<li>Reporting both is fine; claiming cause from either is not</li>
</ul>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-3-correlation-analysis" class="slide level2 divider">
<h2>Part 3 · Correlation Analysis</h2>
</section>
<section id="what-is-correlation" class="slide level2">
<h2>What Is Correlation?</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Correlation</strong> measures the strength and direction of a <strong>linear</strong> relationship between two numerical variables. It runs from −1 to +1:</p>
<ul>
<li>+1 — perfect positive</li>
<li>0 — no <em>linear</em> relationship</li>
<li>−1 — perfect negative</li>
</ul>
<p>The <strong>Pearson correlation coefficient</strong>:</p>
<p><span class="math display">\[r = \frac{\sum_{i}(X_i - \bar{X})(Y_i - \bar{Y})}{\sqrt{\sum_{i}(X_i - \bar{X})^2 \sum_{i}(Y_i - \bar{Y})^2}}\]</span></p>
<p>which is just</p>
<p><span class="math display">\[r = \frac{\text{Covariance}(X, Y)}{s_X \cdot s_Y}\]</span></p>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-03-1.png" alt="Five stacked scatterplots illustrating correlation strength from perfect positive through strong positive, none, strong negative, to perfect negative, each titled with its correlation coefficient." width="288"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="decide-which-one-has-r-closest-to-zero" class="slide level2">
<h2>🗳️ DECIDE · Which One Has r Closest to Zero?</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p>Four datasets, plotted on the right. No correlation coefficients shown — on purpose.</p>
<p><strong>Which panel has the Pearson correlation closest to zero?</strong></p>
<p><strong>(a)</strong> Panel A</p>
<p><strong>(b)</strong> Panel B</p>
<p><strong>(c)</strong> Panel C</p>
<p><strong>(d)</strong> Panel D</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ Write your letter down, then vote.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-04-1.png" alt="Four unlabelled scatterplots: A a moderate positive linear cloud, B a tight symmetric arch, C a diffuse cloud, D a flat cloud with one distant high point." width="403"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="what-r-can-and-cannot-see" class="slide level2">
<h2>What r Can and Cannot See</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (b) — Panel B.</strong></p>
<p>Panel B is the most <em>tightly related</em> pair on the slide: give me x and I can tell you y almost exactly. Its correlation is near <strong>zero</strong> anyway, because the relationship is an arch, not a line.</p>
<p>Panel C looks like the messiest, so most rooms vote (c). It has a weak but genuine <em>linear</em> trend, so its r sits farther from zero than B’s.</p>
</div>
</div>
</div>
<p><strong>r measures one thing only: how close the points lie to a straight line.</strong> A perfect relationship with a curve in it reads as “no correlation.”</p>
<p>Panel D is the other warning — a single far-out point can manufacture a large r out of a cloud with no trend in it.</p>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-05-1.png" alt="The same four scatterplots, now labelled with their Pearson correlation coefficients, showing the arch panel has r near zero despite being the tightest relationship." width="403"></p>
</figure>
</div>
</div>
</div>
<p><strong>Always plot the data before you trust a correlation coefficient.</strong></p>
</div></div>
</section>
<section id="example-16.1-flipping-the-bird" class="slide level2">
<h2>Example 16.1 · Flipping the Bird</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Nazca boobies (<em>Sula granti</em>): do the visits a chick receives from non-parent adults predict how aggressive it is as an adult?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a>booby_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/booby_aggression.csv"</span>)</span>
<span id="cb1-2"><a aria-label="2"></a></span>
<span id="cb1-3"><a aria-label="3"></a><span class="fu">cor.test</span>(booby_df<span class="sc">$</span>visits_as_nestling,</span>
<span id="cb1-4"><a aria-label="4"></a>         booby_df<span class="sc">$</span>future_aggression)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  booby_df$visits_as_nestling and booby_df$future_aggression
t = 2.9603, df = 22, p-value = 0.007229
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1660840 0.7710999
sample estimates:
      cor 
0.5337225 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-07-1.png" alt="Scatterplot of Nazca booby adult aggression score against the number of nestling visits from non-parent adults, showing a positive trend." width="307"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="example-16.1-interpretation" class="slide level2">
<h2>Example 16.1 · Interpretation</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>r = 0.534</strong> — a moderate positive relationship, <strong>p = 0.00723</strong>.</p>
<ul>
<li>Square it for the variance explained: <strong>r² = 0.285</strong>, so about <strong>28.5%</strong> of the variation in one variable is accounted for by the other</li>
<li>Standard error: <span class="math inline">\(\text{SE}_r = \sqrt{\dfrac{1-r^2}{n-2}}\)</span> = 0.18</li>
<li>Tested with a t-test: <span class="math inline">\(t = r / SE_r\)</span>, df = n − 2</li>
</ul>
<p><strong>In words:</strong> boobies visited more often as nestlings tend to be more aggressive adults. Nothing here says the visits <em>caused</em> it.</p>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>🔮 Predict first</strong></p>
<p>Next we run Shapiro-Wilk on both booby variables, then look at their histograms and QQ plots.</p>
<p>If the formal test and the picture disagree at n = 24, which would you trust?</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="testing-assumptions-for-correlation" class="slide level2 scrollable">
<h2>Testing Assumptions for Correlation</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Pearson correlation assumes:</p>
<ol type="1">
<li><strong>Random sampling</strong> from the population</li>
<li><strong>Bivariate normality</strong> — each variable normal, and normal jointly</li>
<li><strong>A linear relationship</strong> — not a curve</li>
<li><strong>No extreme outliers</strong> driving the result</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="fu">shapiro.test</span>(booby_df<span class="sc">$</span>visits_as_nestling)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  booby_df$visits_as_nestling
W = 0.95783, p-value = 0.3965</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a><span class="fu">shapiro.test</span>(booby_df<span class="sc">$</span>future_aggression)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  booby_df$future_aggression
W = 0.91575, p-value = 0.04709</code></pre>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>H₀ is “these data ARE normal”</strong></p>
<p>A <strong>large</strong> p-value is the good outcome — the same backwards logic as Levene’s test.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="checking-the-same-assumptions-by-eye" class="slide level2">
<h2>Checking the Same Assumptions by Eye</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p>The two tests do <strong>not</strong> agree with each other:</p>
<ul>
<li>visits, <strong>p = 0.396</strong> — clean</li>
<li>aggression, <strong>p = 0.047</strong> — just under 0.05</li>
</ul>
<p>Now look at the pictures. No strong skew, points close to both QQ lines, and the scatterplot was straight rather than curved.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ This is the case the last slide asked you to predict</strong></p>
<p>At n = 24, a normality p of 0.047 is a coin-flip verdict, not evidence of a real problem. W&amp;S report <strong>Pearson’s r</strong> for these data, and so do we.</p>
<p>Compare that with the next dataset, where the test and the picture agree that something is wrong.</p>
</div>
</div>
</div>
</div><div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-10-1.png" alt="Four-panel figure for the booby data: histograms of nestling visits and adult aggression on the left, QQ plots of the same two variables on the right." width="403"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="when-the-assumption-fails-example-16.5" class="slide level2">
<h2>When the Assumption Fails — Example 16.5</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>W&amp;S Example 16.5: people who had seen the Indian rope trick were asked, years later, how impressive it was — on a subjective <strong>score</strong>.</p>
<p>That score is bounded and lumpy, and it fails Shapiro badly. Three options when normality fails:</p>
<ul>
<li><strong>Transform</strong> one or both variables (log, square root)</li>
<li>Switch to a <strong>rank-based</strong> correlation — Spearman’s ρ or Kendall’s τ</li>
<li>Hunt down the outlier that is doing the work</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-label="1"></a>rope_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rope_trick.csv"</span>)</span>
<span id="cb7-2"><a aria-label="2"></a></span>
<span id="cb7-3"><a aria-label="3"></a><span class="fu">shapiro.test</span>(rope_df<span class="sc">$</span>impressiveness)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  rope_df$impressiveness
W = 0.82319, p-value = 0.001517</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-12-1.png" alt="Scatterplot of the reported impressiveness score against years since the rope trick was witnessed, showing an increasing but lumpy relationship." width="307"></p>
</figure>
</div>
</div>
</div>
<p>The longer ago someone saw the trick, the more impressive they remember it being.</p>
</div></div>
</section>
<section id="spearmans-rho" class="slide level2">
<h2>Spearman’s Rho</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-label="1"></a><span class="fu">cor.test</span>(rope_df<span class="sc">$</span>years_since_seen,</span>
<span id="cb9-2"><a aria-label="2"></a>         rope_df<span class="sc">$</span>impressiveness,</span>
<span id="cb9-3"><a aria-label="3"></a>         <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  rope_df$years_since_seen and rope_df$impressiveness
S = 332.12, p-value = 2.571e-05
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.7843363 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Spearman replaces each value with its <strong>rank</strong> and correlates the ranks — so it needs no normality and is not thrown by one extreme value.</p>
<ul>
<li>Pearson <strong>r = 0.848</strong></li>
<li>Spearman <strong>ρ = 0.784</strong></li>
</ul>
<p>Square ρ the same way: <strong>ρ² = 0.615</strong> — about 61.5% of the variation <em>in the ranks</em>.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The cost of switching</strong></p>
<p>You keep an honest p-value and lose the original units. ρ is about ranks, so it can no longer be read as “score per year.”</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="decide-the-correlation-that-shrank" class="slide level2">
<h2>🗳️ DECIDE · The Correlation That Shrank</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>A colleague reports <strong>r = 0.82</strong> between body size and fecundity across a set of populations.</p>
<p>You repeat the study, carefully, at <strong>one site</strong> — where the animals are all close to the same size — and get <strong>r = 0.31</strong> from data that are every bit as clean.</p>
<p><strong>What is the most likely explanation?</strong></p>
<p><strong>(a)</strong> The original result was a false positive</p>
<p><strong>(b)</strong> Your sample size was too small</p>
<p><strong>(c)</strong> Restricting the range of X shrank r, with the underlying relationship unchanged</p>
<p><strong>(d)</strong> Measurement error in your study inflated r</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ One letter. Write it down.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The question to ask</strong></p>
<p><em>Did the relationship change — or did the slice of the world I looked at change?</em></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="two-things-that-move-r-without-touching-the-biology" class="slide level2">
<h2>Two Things That Move r Without Touching the Biology</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (c).</strong></p>
<p><strong>Range restriction.</strong> r depends on the spread of X you sampled. Look at a narrow slice of a real relationship and r falls, even though the slope is unchanged. This is why correlations from studies with different ranges cannot be compared head to head.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Attenuation</strong></p>
<p>Measurement error in X or Y pushes r <strong>toward zero</strong>, never away from it. The true correlation is usually <strong>stronger</strong> than the one you observed — so (d) has the direction backwards.</p>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-14-1.png" alt="Four stacked scatterplots: the full range of a relationship versus a restricted range with a much lower r, and true values versus values with measurement error added, showing attenuation." width="307"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="correlation-what-to-carry-forward" class="slide level2">
<h2>Correlation — What to Carry Forward</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>r measures straight-line association only</strong> — always plot first</li>
<li><strong>r² is the variance the two variables share</strong></li>
<li><strong>The range you sampled sets the ceiling on r</strong>; measurement error lowers it further</li>
<li><strong>Correlation does not imply causation.</strong> Three explanations always survive: X causes Y, Y causes X, or Z causes both</li>
<li><strong>The test:</strong> H₀ is ρ = 0, statistic t = r / SE(r), df = n − 2</li>
<li><strong>When normality fails</strong>, switch to rank-based Spearman’s ρ</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ End of the correlation half</strong></p>
<p>You can now run <code>cor.test()</code>, check its assumptions on the raw variables, switch to Spearman when they fail, and say what r and r² mean.</p>
<p>Next: the same cloud of points — but now we fit a <strong>line</strong> to it and ask what that line is made of.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-4-linear-regression-the-model" class="slide level2 divider">
<h2>Part 4 · Linear Regression — the Model</h2>
</section>
<section id="the-simple-linear-regression-model" class="slide level2">
<h2>The Simple Linear Regression Model</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Regression models the response Y as a straight-line function of the predictor X.</p>
<p>The <strong>population</strong> model: <span class="math inline">\(Y = \alpha + \beta X + \varepsilon\)</span></p>
<ul>
<li>α is the intercept — the value of Y when X = 0</li>
<li>β is the slope — the change in Y per one-unit change in X</li>
<li>ε is the error — the random deviation of a point from the line</li>
</ul>
<p>The <strong>sample</strong> equation: <span class="math inline">\(\hat{Y} = a + bX\)</span>, where a estimates α and b estimates β.</p>
<p><strong>Method of least squares:</strong> of all possible lines, take the one that makes</p>
<p><span class="math display">\[\sum_{i=1}^{n}(y_i - \hat{y}_i)^2\]</span></p>
<p>as small as possible — the sum of the squared <strong>vertical</strong> distances.</p>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-3360244964.png" class="tall-fig" style="width:2.29in" alt="Three candidate lines through the lion data with vertical residual segments labelled large, smaller and smallest deviations."></p>
<p>Least squares picks the third one.</p>
</div></div>
</section>
<section id="fitting-the-lion-model" class="slide level2">
<h2>Fitting the Lion Model</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p>Male lions accumulate black pigment on the nose as they age — so nose colour can age a lion in the field without anyone catching it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-label="1"></a>lion_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/lion_noses.csv"</span>)</span>
<span id="cb11-2"><a aria-label="2"></a></span>
<span id="cb11-3"><a aria-label="3"></a>lion_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(age_years <span class="sc">~</span> proportion_black,</span>
<span id="cb11-4"><a aria-label="4"></a>                 <span class="at">data =</span> lion_df)</span>
<span id="cb11-5"><a aria-label="5"></a><span class="fu">coef</span>(lion_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept) proportion_black 
       0.8790062       10.6471194 </code></pre>
</div>
</div>
<p>Read the formula as <strong>response ~ predictor</strong>.</p>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-16-1.png" alt="Scatterplot of lion age against proportion of black on the nose with the fitted regression line, annotated with the fitted equation and one point's residual drawn in red." width="364"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="reading-the-model-output" class="slide level2">
<h2>Reading the Model Output</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-label="1"></a><span class="fu">summary</span>(lion_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age_years ~ proportion_black, data = lion_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5449 -1.1117 -0.5285  0.9635  4.3421 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        0.8790     0.5688   1.545    0.133    
proportion_black  10.6471     1.5095   7.053 7.68e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.669 on 30 degrees of freedom
Multiple R-squared:  0.6238,    Adjusted R-squared:  0.6113 
F-statistic: 49.75 on 1 and 30 DF,  p-value: 7.677e-08</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><span class="math display">\[\widehat{\text{age}} = 0.88 + 10.65 \times \text{prop. black}\]</span></p>
<ul>
<li><strong>Estimate</strong> — the intercept and the slope</li>
<li><strong>Std. Error</strong> — how precisely each is pinned down</li>
<li><strong>t value</strong> — estimate ÷ SE, testing H₀: β = 0</li>
<li><strong>Multiple R-squared</strong> = 0.624 — the share of variation in age explained by nose colour</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Notice</strong></p>
<p>Correlating these same two variables and squaring r gives the <em>same</em> 0.624. Hold that thought — Part 5 explains why.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="decide-what-the-slope-and-intercept-say" class="slide level2">
<h2>🗳️ DECIDE · What the Slope and Intercept Say</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>The fitted line is <span class="math inline">\(\widehat{\text{age}} = 0.88 + 10.65 \times \text{prop. black}\)</span>.</p>
<p><strong>Which statement is correct?</strong></p>
<p><strong>(a)</strong> A lion’s nose darkens by 10.65 units for every year it ages</p>
<p><strong>(b)</strong> Going from a nose 10% black to one 20% black predicts about <strong>1.06 more years</strong> of age</p>
<p><strong>(c)</strong> A newborn lion is predicted to be 0.88 years old, so the model is wrong</p>
<p><strong>(d)</strong> 62.4% of lions are aged correctly by this equation</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ Write your letter down, then vote.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Ask yourself</strong></p>
<p><em>What are the units on this slope?</em></p>
<p>A slope is always <strong>units of Y per one unit of X</strong> — and here one unit of X is the whole range, from a clean nose to a fully black one.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="slope-and-intercept-in-words" class="slide level2">
<h2>Slope and Intercept, in Words</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (b).</strong></p>
<p>The slope is <strong>10.65 years per unit of proportion black</strong>, and one unit is the entire 0-to-1 range. A 0.1 change in blackness therefore predicts about <strong>1.06 years</strong>.</p>
<p><strong>(a)</strong> reverses the variables — that is the regression of blackness on age, a different line.</p>
<p><strong>(c)</strong> misreads the intercept: it is 0.88 years at proportion black = 0, and the youngest lion measured was 1.1 years old, so X = 0 sits <strong>outside the data</strong>. The intercept anchors the line; it is not a claim about newborns.</p>
<p><strong>(d)</strong> confuses R² with an accuracy rate. R² is variance explained, not the percentage of lions got right.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Extrapolation</strong></p>
<p>A fitted line says nothing about X values you never sampled, and the confidence band is <em>widest</em> exactly where you have no data.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 The habit to build</strong></p>
<p>Write every slope out as a sentence in the units of the data — “for every extra <strong><em>, Y changes by </em></strong>” — before you write a word about significance.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="calculating-the-slope-and-intercept-by-hand" class="slide level2">
<h2>Calculating the Slope and Intercept by Hand</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><span class="math display">\[b = \frac{\sum_i(X_i - \bar{X})(Y_i - \bar{Y})}{\sum_i(X_i - \bar{X})^2}
\qquad a = \bar{Y} - b\bar{X}\]</span></p>
<p>The numerator is a <strong>sum of cross-products</strong>; the denominator is a <strong>sum of squares</strong>. Both are the same kind of quantity the ANOVA table is built from in a moment.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-label="1"></a>x <span class="ot">&lt;-</span> lion_df<span class="sc">$</span>proportion_black</span>
<span id="cb15-2"><a aria-label="2"></a>y <span class="ot">&lt;-</span> lion_df<span class="sc">$</span>age_years</span>
<span id="cb15-3"><a aria-label="3"></a></span>
<span id="cb15-4"><a aria-label="4"></a>b <span class="ot">&lt;-</span> <span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x)) <span class="sc">*</span> (y <span class="sc">-</span> <span class="fu">mean</span>(y))) <span class="sc">/</span> <span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb15-5"><a aria-label="5"></a>a <span class="ot">&lt;-</span> <span class="fu">mean</span>(y) <span class="sc">-</span> b <span class="sc">*</span> <span class="fu">mean</span>(x)</span>
<span id="cb15-6"><a aria-label="6"></a><span class="fu">c</span>(<span class="at">intercept =</span> a, <span class="at">slope =</span> b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> intercept      slope 
 0.8790062 10.6471194 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Compare that with what <code>lm()</code> reported:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-label="1"></a><span class="fu">coef</span>(lion_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept) proportion_black 
       0.8790062       10.6471194 </code></pre>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Same answer, no magic</strong></p>
<p><code>lm()</code> is doing this arithmetic. Everything harder than this — multiple predictors, ANOVA, mixed models — is the same idea written in matrix form.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="making-predictions" class="slide level2">
<h2>Making Predictions</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-label="1"></a>new_lion <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">proportion_black =</span> <span class="fl">0.50</span>)</span>
<span id="cb19-2"><a aria-label="2"></a></span>
<span id="cb19-3"><a aria-label="3"></a><span class="fu">predict</span>(lion_model, new_lion, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr     upr
1 6.202566 5.388042 7.01709</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-label="1"></a><span class="fu">predict</span>(lion_model, new_lion, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr     upr
1 6.202566 2.698512 9.70662</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Both intervals sit on the same predicted age, and answer different questions:</p>
<ul>
<li><strong>Confidence interval</strong> — where the <em>mean</em> age of all lions with 50% black noses lies</li>
<li><strong>Prediction interval</strong> — where a <em>single</em> new lion’s age lies</li>
</ul>
<p>The prediction interval is always wider: it carries the scatter of individual lions <strong>plus</strong> the uncertainty in the line itself.</p>
<p>Both are narrowest at <span class="math inline">\(\bar{X}\)</span> and flare out toward the edges of the data.</p>
</div></div>
</section>
<section id="example-17.3-prairie-biodiversity-and-stability" class="slide level2">
<h2>Example 17.3 · Prairie Biodiversity and Stability</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Tilman et al.&nbsp;(2006): does a more diverse plant community produce <strong>more stable</strong> biomass? 161 plots, seeded with 1 to 16 species.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-label="1"></a>prairie_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/prairie_stability.csv"</span>)</span>
<span id="cb23-2"><a aria-label="2"></a></span>
<span id="cb23-3"><a aria-label="3"></a>prairie_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(biomass_stability) <span class="sc">~</span> species_number,</span>
<span id="cb23-4"><a aria-label="4"></a>                    <span class="at">data =</span> prairie_df)</span>
<span id="cb23-5"><a aria-label="5"></a><span class="fu">summary</span>(prairie_model)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept)    1.1982943 0.041298043 29.015766 2.075490e-65
species_number 0.0329259 0.004883691  6.742012 2.733315e-10</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-22-1.png" alt="Scatterplot of log biomass stability against the number of plant species with a fitted regression line and confidence band, showing stability increasing with diversity." width="307"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-prairie-model-interpretation" class="slide level2">
<h2>The Prairie Model — Interpretation</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>The hypothesis test is about the slope:</p>
<ul>
<li>H₀: β = 0 — species number has no effect on stability</li>
<li>H₁: β ≠ 0</li>
</ul>
<p><strong>Slope = 0.0329</strong> — log stability rises by about 0.033 per extra species, so a 16-species plot sits roughly 0.49 log units above a monoculture.</p>
<p><strong>p = 2.73e-10</strong> — strong evidence against a zero slope.</p>
<p><strong>R² = 0.222</strong> — diversity explains about 22.2% of the variation in stability. Real, and nowhere near the whole story.</p>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Significant ≠ large</strong></p>
<p>A tiny p-value alongside R² = 0.22 is completely ordinary in ecology.</p>
<p>The p-value says the slope is not zero. <strong>R² says how much of the world it accounts for.</strong> Report both.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-5-sums-of-squares-the-engine-of-everything-after-this" class="slide level2 divider">
<h2>Part 5 · Sums of Squares — the Engine of Everything After This</h2>
</section>
<section id="where-the-variation-goes" class="slide level2">
<h2>Where the Variation Goes</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Take <strong>one</strong> data point. Its distance from the overall mean <span class="math inline">\(\bar{y}\)</span> splits, exactly, into two pieces:</p>
<p><span class="math display">\[\underbrace{(y_i - \bar{y})}_{\text{total}} = \underbrace{(\hat{y}_i - \bar{y})}_{\text{explained}} + \underbrace{(y_i - \hat{y}_i)}_{\text{left over}}\]</span></p>
<p>Square those deviations and add them up over every point, and the same split holds for the whole dataset:</p>
<p><span class="math display">\[SS_{total} = SS_{regression} + SS_{residual}\]</span></p>
<ul>
<li><span class="math inline">\(SS_{regression}\)</span> — variation the line accounts for; <strong>df = 1</strong></li>
<li><span class="math inline">\(SS_{residual}\)</span> — variation it does not; <strong>df = n − 2</strong></li>
<li><span class="math inline">\(SS_{total}\)</span> — all of it; <strong>df = n − 1</strong></li>
</ul>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-23-1.png" alt="Lion scatterplot with the fitted line and a dashed line at the mean age; for one highlighted point a green segment runs from the mean to the fitted value and a red segment from the fitted value to the observation." width="412"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="decide-which-fit-has-the-bigger-sums-of-squares" class="slide level2">
<h2>🗳️ DECIDE · Which Fit Has the Bigger Sums of Squares?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Four fitted regressions, on the right.</p>
<p><strong>Which statement is true?</strong></p>
<p><strong>(a)</strong> <span class="math inline">\(SS_{regression}\)</span> is larger in <strong>(d)</strong> than in <strong>(c)</strong></p>
<p><strong>(b)</strong> <span class="math inline">\(SS_{residual}\)</span> is larger in <strong>(b)</strong> than in <strong>(a)</strong></p>
<p><strong>(c)</strong> <span class="math inline">\(SS_{total}\)</span> is larger in <strong>(a)</strong> than in <strong>(b)</strong></p>
<p><strong>(d)</strong> <span class="math inline">\(SS_{residual}\)</span> is zero in <strong>(c)</strong></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ One letter. Write it down, then argue it with your neighbour.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><img data-src="images/clipboard-217151541.png" style="width:3.12in" alt="Four scatterplots with fitted regression lines of differing steepness and scatter, each marked with an observed point, its prediction, and the mean of Y."></p>
</div></div>
</section>
<section id="reading-the-partition-off-a-picture" class="slide level2">
<h2>Reading the Partition Off a Picture</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (b).</strong></p>
<p><span class="math inline">\(SS_{residual}\)</span> is the scatter <strong>around the line</strong>, and the points in (b) sit farther off their line than those in (a).</p>
<p><strong>(a)</strong> is backwards: <span class="math inline">\(SS_{regression}\)</span> grows with how steeply the fitted line climbs, and (c) is steeper than (d).</p>
<p><strong>(c)</strong> is the trap — <span class="math inline">\(SS_{total}\)</span> does not depend on the fit at all. It is the spread of Y around its own mean, and the line has nothing to do with it.</p>
<p><strong>(d)</strong> would require every point to sit exactly on the line.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The three pictures to keep</strong></p>
<ul>
<li><span class="math inline">\(SS_{total}\)</span> → distance from the <strong>flat mean line</strong></li>
<li><span class="math inline">\(SS_{regression}\)</span> → how far the <strong>fitted line climbs away</strong> from that flat line</li>
<li><span class="math inline">\(SS_{residual}\)</span> → how far the <strong>points sit off</strong> the fitted line</li>
</ul>
</div>
</div>
</div>
<p>A fit is good when the line does a lot of climbing and the points stay close to it.</p>
</div></div>
</section>
<section id="computing-the-three-sums-of-squares" class="slide level2">
<h2>Computing the Three Sums of Squares</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-label="1"></a>fitted_age <span class="ot">&lt;-</span> <span class="fu">predict</span>(lion_model)</span>
<span id="cb25-2"><a aria-label="2"></a>mean_age   <span class="ot">&lt;-</span> <span class="fu">mean</span>(lion_df<span class="sc">$</span>age_years)</span>
<span id="cb25-3"><a aria-label="3"></a></span>
<span id="cb25-4"><a aria-label="4"></a>ss_total <span class="ot">&lt;-</span> <span class="fu">sum</span>((lion_df<span class="sc">$</span>age_years <span class="sc">-</span> mean_age)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb25-5"><a aria-label="5"></a>ss_reg   <span class="ot">&lt;-</span> <span class="fu">sum</span>((fitted_age <span class="sc">-</span> mean_age)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb25-6"><a aria-label="6"></a>ss_resid <span class="ot">&lt;-</span> <span class="fu">sum</span>((lion_df<span class="sc">$</span>age_years <span class="sc">-</span> fitted_age)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb25-7"><a aria-label="7"></a></span>
<span id="cb25-8"><a aria-label="8"></a><span class="fu">c</span>(<span class="at">total =</span> ss_total, <span class="at">regression =</span> ss_reg, <span class="at">residual =</span> ss_resid)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     total regression   residual 
 222.08719  138.54398   83.54321 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-label="1"></a>ss_reg <span class="sc">+</span> ss_resid          <span class="co"># does it add back up?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 222.0872</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>138.5 + 83.5 = 222.1</strong> — exactly.</p>
<p>And the share the line accounts for:</p>
<p><span class="math display">\[R^2 = \frac{SS_{regression}}{SS_{total}} = \frac{138.5}{222.1} = 0.624\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ This is where R² comes from</strong></p>
<p>R² is not a separate statistic. It is the <strong>regression sum of squares as a fraction of the total</strong> — and with one predictor it is exactly the correlation coefficient squared.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-same-numbers-straight-from-r" class="slide level2">
<h2>The Same Numbers, Straight from R</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-label="1"></a><span class="fu">anova</span>(lion_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: age_years
                 Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
proportion_black  1 138.544 138.544   49.75 7.677e-08 ***
Residuals        30  83.543   2.785                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Every number in that table you have now built by hand:</p>
<ul>
<li><strong>Sum Sq</strong> — the two sums of squares, 138.5 and 83.5</li>
<li><strong>Df</strong> — 1 for the predictor, n − 2 = 30 for the residual</li>
<li><strong>Mean Sq</strong> — Sum Sq ÷ Df</li>
<li><strong>F value</strong> — the ratio of those two mean squares</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>This table has a shape, not a topic</strong></p>
<p>The identical five columns show up for one-way ANOVA, two-way ANOVA, nested ANOVA and ANCOVA. Only the <strong>rows</strong> change.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="from-sums-of-squares-to-mean-squares" class="slide level2">
<h2>From Sums of Squares to Mean Squares</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>A sum of squares keeps growing as you add data, so it cannot be compared across studies. Divide by degrees of freedom and you get a <strong>mean square</strong> — a variance, which does not grow with n:</p>
<p><span class="math display">\[MS = \frac{SS}{df} \qquad F = \frac{MS_{regression}}{MS_{residual}}\]</span></p>
<ul>
<li><span class="math inline">\(MS_{residual}\)</span> = 2.785 — estimates the background variance σ²</li>
<li><span class="math inline">\(MS_{regression}\)</span> = 138.54 — estimates that <strong>same</strong> σ², <em>plus</em> whatever the X–Y relationship adds</li>
<li><strong>If the slope is truly zero, both estimate the same thing and F ≈ 1.</strong> Here F = <strong>49.75</strong></li>
</ul>
<p>Sums of squares add up. <strong>Mean squares do not.</strong></p>
</div><div class="column" style="width:40%;">
<p><img data-src="images/clipboard-77063277.png" style="width:3.12in" alt="ANOVA table for simple linear regression listing regression, residual and total rows with sum-of-squares, degrees-of-freedom, mean-square and expected-mean-square formulas."></p>
</div></div>
</section>
<section id="decide-you-double-the-sample-size" class="slide level2">
<h2>🗳️ DECIDE · You Double the Sample Size</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>You repeat the lion study and come back with <strong>64 lions instead of 32</strong>. The relationship is identical — same slope, same scatter around the line.</p>
<p><strong>Compared with the original analysis, what happens?</strong></p>
<p><strong>(a)</strong> <span class="math inline">\(SS_{total}\)</span> roughly doubles, and <span class="math inline">\(MS_{residual}\)</span> roughly doubles with it</p>
<p><strong>(b)</strong> <span class="math inline">\(SS_{total}\)</span> roughly doubles, but <span class="math inline">\(MS_{residual}\)</span> stays about the same</p>
<p><strong>(c)</strong> Both stay about the same — doubling n changes neither</p>
<p><strong>(d)</strong> <span class="math inline">\(SS_{total}\)</span> stays about the same and <span class="math inline">\(MS_{residual}\)</span> halves</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ Write your letter down. This one decides whether you can read the table.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The question to ask</strong></p>
<p><em>Which of these is a total, and which is an average?</em></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="why-mean-squares-exist-at-all" class="slide level2">
<h2>Why Mean Squares Exist At All</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (b).</strong></p>
<p><span class="math inline">\(SS_{total}\)</span> is a <strong>sum</strong> over every observation, so twice the data is roughly twice the sum. <span class="math inline">\(MS_{residual}\)</span> is that sum <strong>divided by its degrees of freedom</strong> — an average squared deviation — so it estimates the same σ² no matter how many lions you measure.</p>
<p>That is exactly why the table converts sums of squares into mean squares before testing anything. You cannot compare two sums built from different amounts of data; you can compare two variances.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 What doubling n actually buys</strong></p>
<p>σ² does not change, but the <strong>standard error of the slope</strong> shrinks with √n — so F rises and the confidence band tightens.</p>
<p>More data does not reduce the scatter in nature. It reduces your uncertainty about the line running through it.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-bridge-one-table-every-model-from-here" class="slide level2">
<h2>The Bridge · One Table, Every Model From Here</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>For the lion model, all of these are <strong>the same test</strong>:</p>
<div class="compact-table">
<table class="caption-top">
<thead>
<tr class="header">
<th>Route</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t on the slope</td>
<td>7.053</td>
</tr>
<tr class="even">
<td>t²</td>
<td>49.75</td>
</tr>
<tr class="odd">
<td>F from <code>anova()</code></td>
<td>49.75</td>
</tr>
<tr class="even">
<td>p, either way</td>
<td>7.68e-08</td>
</tr>
</tbody>
</table>
</div>
<p><strong>t² = F.</strong> The t-test on a slope and the F-test in the ANOVA table are one test asked two ways — and <span class="math inline">\(r^2 = SS_{reg}/SS_{total}\)</span> ties both back to the correlation half of this lecture.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Why this is the most important slide today</strong></p>
<p>Every analysis for the rest of the course is this same partition with more rows:</p>
<ul>
<li><strong>One-way ANOVA</strong> — groups instead of a slope</li>
<li><strong>Two-way ANOVA</strong> — a row per factor, plus interaction</li>
<li><strong>Nested ANOVA</strong> — a row per level of nesting</li>
<li><strong>ANCOVA</strong> — a slope row <em>and</em> a group row</li>
</ul>
<p>Learn to read this table once and you can read all of them.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-6-testing-regression-assumptions" class="slide level2 divider">
<h2>Part 6 · Testing Regression Assumptions</h2>
</section>
<section id="testing-regression-assumptions-overview" class="slide level2 scrollable">
<h2>Testing Regression Assumptions — Overview</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Simple linear regression assumes:</p>
<ol type="1">
<li><strong>Linearity</strong> — the true relationship is a straight line</li>
<li><strong>Independence</strong> — observations do not depend on each other</li>
<li><strong>Homoscedasticity</strong> — equal scatter at every value of X</li>
<li><strong>Normality</strong> — the residuals are normally distributed</li>
</ol>
<p>Stated formally: the error <span class="math inline">\(\varepsilon_i\)</span> is normal, with a mean of 0 and the <strong>same variance</strong>, at every value of x.</p>
</div><div class="column" style="width:45%;">
<p><img data-src="images/clipboard-2092034232.png" class="tall-fig" style="width:3.12in;height:3.22in" alt="Diagram of a regression line with small normal distributions drawn around it at two X values, showing Y is assumed normal with constant variance at every X."></p>
</div></div>
</section>
<section id="every-check-is-about-the-residuals" class="slide level2">
<h2>Every Check Is About the Residuals</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Every assumption check from here on uses the <strong>residuals</strong>, not the raw data. That is the single most common mix-up in regression.</p>
<p>The error <span class="math inline">\(\varepsilon_i\)</span> is estimated by the residual <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span> — the same red segment you have seen on every lion plot today, and the same quantity that got squared and summed to build <span class="math inline">\(SS_{residual}\)</span>.</p>
<p>Least squares already made these as small as possible. The diagnostics ask whether what is left over looks like random noise.</p>
</div><div class="column" style="width:45%;">
<p><img data-src="images/clipboard-1411052425.png" style="width:3.12in" alt="Scatterplot with a fitted least-squares line marking one observed point, its predicted value on the line, and the vertical residual between them."></p>
</div></div>
</section>
<section id="checking-linearity-residuals-vs.-fitted" class="slide level2">
<h2>Checking Linearity — Residuals vs.&nbsp;Fitted</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>What you want:</strong> a shapeless cloud, scattered evenly above and below the horizontal line at zero.</p>
<p><strong>What is a problem:</strong> any <em>curve</em> in the trend line. A U-shape or an arch means a straight line is the wrong shape for these data — the exact failure Panel B showed back in the correlation half.</p>
<p>The plot doubles as a <strong>homoscedasticity</strong> check: if the cloud fans out or funnels in from left to right, the variance is not constant.</p>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-26-1.png" alt="Residuals versus fitted values plot for the lion regression, used to check linearity and constant variance." width="326"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="checking-normality-qq-plot-of-residuals" class="slide level2">
<h2>Checking Normality — QQ Plot of Residuals</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>The QQ plot compares your residuals with what perfectly normal residuals would look like.</p>
<p><strong>What you want:</strong> points hugging the diagonal.</p>
<p><strong>What is a problem:</strong> systematic curvature, or points peeling away at the ends. Tails are where non-normality shows up first, and tails are what p-values depend on.</p>
<p>Note we check the residuals, <strong>not</strong> <code>age_years</code> itself. The raw ages are right-skewed, and that is allowed. It is the residuals that have to behave.</p>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-27-1.png" alt="Normal QQ plot of residuals from the lion regression, used to check the normality assumption." width="326"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="checking-normality-shapiro-wilk-on-residuals" class="slide level2">
<h2>Checking Normality — Shapiro-Wilk on Residuals</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-label="1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(lion_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(lion_model)
W = 0.93879, p-value = 0.0692</code></pre>
</div>
</div>
<p><strong><code>residuals(model)</code></strong> — not <code>lion_df$age_years</code>. Testing the raw response is a different, and usually wrong, question.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>H₀ is “the residuals ARE normal”</strong></p>
<p>So a <strong>large</strong> p-value is the good outcome.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Do not let this test overrule your eyes</strong></p>
<p>At small n it has almost no power to detect a real problem; at large n it flags departures far too small to matter. Read the QQ plot first and use the test to support it — not to replace it.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="what-violations-actually-look-like" class="slide level2 scrollable">
<h2>What Violations Actually Look Like</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p>When an assumption fails:</p>
<ol type="1">
<li><strong>Transform</strong> one or both variables (W&amp;S §17.6) — a log on a curved or fanning relationship fixes both problems more often than not</li>
<li><strong>Weighted least squares</strong> for heteroscedasticity</li>
<li>A <strong>non-linear model</strong> (§17.8), or a GLM in Week 11</li>
</ol>
</div><div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-29-1.png" alt="Three stacked scatterplots showing one assumption violation each: a curved relationship fitted with a straight line, variance increasing with x, and right-skewed residuals." width="364"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="decide-one-island" class="slide level2">
<h2>🗳️ DECIDE · One Island</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Gotelli &amp; Ellison’s Galápagos data: <strong>17 islands</strong>, plant species richness against island area, both log-transformed. The fit is solid — R² = 0.585, p = 3.50e-04.</p>
<p>Now <strong>one</strong> more point arrives: a large island reported with very few species (red).</p>
<p><strong>What does that single point do?</strong></p>
<p><strong>(a)</strong> Very little — one point in 18 cannot matter much</p>
<p><strong>(b)</strong> It raises R², because the range of X just got wider</p>
<p><strong>(c)</strong> It roughly <strong>halves</strong> R² and pushes p to the edge of significance</p>
<p><strong>(d)</strong> It can change R² but not the slope</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ One letter, before the next slide.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="correlation_linear_models_lecture_files/figure-revealjs/correlation-linear-models-30-1.png" alt="Log-log scatterplot of Galapagos island plant species richness against island area with a fitted line, plus one red point sitting far below the line at a large area." width="307"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="what-one-point-did" class="slide level2">
<h2>What One Point Did</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-label="1"></a>galap_plot <span class="ot">&lt;-</span> galap_df <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a aria-label="2"></a>  <span class="fu">mutate</span>(<span class="at">log_area =</span> <span class="fu">log10</span>(area_km2),</span>
<span id="cb33-3"><a aria-label="3"></a>         <span class="at">log_species =</span> <span class="fu">log10</span>(n_species))</span>
<span id="cb33-4"><a aria-label="4"></a></span>
<span id="cb33-5"><a aria-label="5"></a><span class="co"># a big island reported with very few species</span></span>
<span id="cb33-6"><a aria-label="6"></a>galap_bad <span class="ot">&lt;-</span> galap_plot <span class="sc">%&gt;%</span></span>
<span id="cb33-7"><a aria-label="7"></a>  <span class="fu">add_row</span>(<span class="at">log_area =</span> <span class="dv">3</span>, <span class="at">log_species =</span> <span class="fl">0.65</span>)</span>
<span id="cb33-8"><a aria-label="8"></a></span>
<span id="cb33-9"><a aria-label="9"></a>clean_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_species <span class="sc">~</span> log_area, galap_plot)</span>
<span id="cb33-10"><a aria-label="10"></a>bad_model   <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_species <span class="sc">~</span> log_area, galap_bad)</span>
<span id="cb33-11"><a aria-label="11"></a></span>
<span id="cb33-12"><a aria-label="12"></a><span class="fu">tibble</span>(<span class="at">data  =</span> <span class="fu">c</span>(<span class="st">"17 islands"</span>, <span class="st">"plus the suspect point"</span>),</span>
<span id="cb33-13"><a aria-label="13"></a>       <span class="at">slope =</span> <span class="fu">c</span>(<span class="fu">coef</span>(clean_model)[<span class="dv">2</span>], <span class="fu">coef</span>(bad_model)[<span class="dv">2</span>]),</span>
<span id="cb33-14"><a aria-label="14"></a>       <span class="at">r2    =</span> <span class="fu">c</span>(<span class="fu">summary</span>(clean_model)<span class="sc">$</span>r.squared,</span>
<span id="cb33-15"><a aria-label="15"></a>                 <span class="fu">summary</span>(bad_model)<span class="sc">$</span>r.squared))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  data                   slope    r2
  &lt;chr&gt;                  &lt;dbl&gt; &lt;dbl&gt;
1 17 islands             0.331 0.585
2 plus the suspect point 0.233 0.228</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (c).</strong></p>
<p>One point out of 18 cuts R² from 0.58 to 0.23 and moves p from 3.50e-04 to 0.0449 — from convincing to barely publishable. The slope drops too, so (d) is out.</p>
<p>It is <strong>influential</strong> because it lies far out in X <em>and</em> far off the trend. Cook’s distance flags it at once — that is what panel 4 of <code>plot(model)</code> is for.</p>
</div>
</div>
</div>
<p><strong>No diagnostic can tell you whether it is a typo or a real island.</strong> That takes going back to the data sheet.</p>
</div></div>
</section>
<section id="part-7-wrap-up" class="slide level2 divider">
<h2>Part 7 · Wrap-up</h2>
</section>
<section id="wrap-up" class="slide level2">
<h2>Wrap-up</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Over the two days you:</p>
<ul>
<li>Separated <strong>correlation</strong> from <strong>regression</strong>, and saw that neither earns causation</li>
<li>Computed <strong>Pearson’s r</strong>, squared it for variance explained, and tested it with <code>cor.test()</code></li>
<li>Switched to <strong>Spearman’s ρ</strong> when normality failed</li>
<li>Fitted a line with <code>lm()</code> and read the slope <strong>in the units of the data</strong></li>
<li>Built <span class="math inline">\(SS_{regression}\)</span> and <span class="math inline">\(SS_{residual}\)</span> by hand, watched them add to <span class="math inline">\(SS_{total}\)</span>, and turned them into mean squares and an F</li>
<li>Confirmed <strong>t² = F</strong> and <strong>r² = SS_reg / SS_total</strong></li>
<li>Checked all four assumptions <strong>on the residuals</strong>, and watched one influential island halve an R²</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The one idea to keep</strong></p>
<p>A line can be fitted to <em>any</em> two numeric columns. What makes it trustworthy lives in the <strong>residuals</strong>; what makes it interpretable lives in the <strong>sums of squares</strong>. Neither lives in the p-value.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Up next — Multiple Regression</strong></p>
<p>More than one predictor, predictors correlated with each other, and choosing between competing models. Same table, more rows.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="readings" class="slide level2">
<h2>Readings</h2>
<ul>
<li><strong>Whitlock &amp; Schluter</strong>, Ch. 16 — Correlation (§16.3 assumptions; §16.5 Spearman’s rank correlation), and Ch. 17 — Regression (§17.6 transformations; §17.8 non-linear relationships).</li>
<li><strong>Gotelli &amp; Ellison</strong>, Ch. 9 — Regression, for the variance-partitioning treatment and the Galápagos species–area example.</li>
<li>Tilman, D., Reich, P. B., &amp; Knops, J. M. H. (2006). Biodiversity and ecosystem stability in a decade-long grassland experiment. <em>Nature</em>, 441, 629–632.</li>
</ul>
</section>
<section id="getting-unstuck" class="slide level2 scrollable">
<h2>Getting unstuck</h2>
<p>When code breaks — and it will, that is normal:</p>
<ol type="1">
<li>Read the <strong>error message</strong> out loud; it usually names the line</li>
<li>Check the usual suspects: is <code>lm()</code> written <code>y ~ x</code> (response first)? Did you pass <code>residuals(model)</code> where a model was expected, or vice versa?</li>
<li><code>?function_name</code> opens the help page</li>
<li>Bring the <strong>exact error</strong> (copy-paste it) to class or office hours</li>
</ol>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea</strong></p>
<p>Every working scientist googles error messages daily. Getting stuck is not failing — it is the job.</p>
</div>
</div>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/ecostats_2026");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>