<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Lecture: Probability &amp; Inference</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-b8eef193cd4aecd129dcd97c8f413977.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture: Probability &amp; Inference – UMD Biostatistics">
<meta property="og:description" content="Probability distributions, the standard normal and t-distributions, Z-scores, confidence intervals, one- and two-tailed hypothesis testing, p-values, and Type I/II error — on the Arctic grayling length dataset.">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture: Probability &amp; Inference</h1>
  <p class="subtitle">Foundations of inference</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry
</div>
</div>
</div>

</section>
<section id="probability-and-statistical-inference" class="slide level2">
<h2>Probability and Statistical Inference</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Review of probability distributions</li>
<li>Standard normal distribution and Z-scores</li>
<li>Standard error and confidence intervals</li>
<li>Statistical inference fundamentals</li>
<li>Hypothesis testing principles</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-02-1.png" alt="Dodged histogram of Arctic grayling length in millimeters, colored by lake (I3 and I8), showing the distribution of fish lengths for each lake." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="practice-exercise-1-exploring-the-grayling-dataset" class="slide level2">
<h2>Practice Exercise 1: Exploring the Grayling Dataset</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 1: Exploring the Grayling Dataset</strong></p>
</div>
<div class="callout-content">
<p>Let’s explore the Arctic grayling data from lakes I3 and I8. Use the <code>grayling_df</code> data frame to create basic summary statistics.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a><span class="co"># Write your code here to explore the basic structure of the data</span></span>
<span id="cb1-2"><a aria-label="2"></a><span class="co"># also note plottig a box plot is really useful</span></span>
<span id="cb1-3"><a aria-label="3"></a></span>
<span id="cb1-4"><a aria-label="4"></a></span>
<span id="cb1-5"><a aria-label="5"></a><span class="co"># Calculate summary statistics</span></span>
<span id="cb1-6"><a aria-label="6"></a>grayling_summary <span class="ot">&lt;-</span> grayling_df <span class="sc">%&gt;%</span> </span>
<span id="cb1-7"><a aria-label="7"></a>  <span class="fu">group_by</span>(lake) <span class="sc">%&gt;%</span></span>
<span id="cb1-8"><a aria-label="8"></a>  <span class="fu">summarize</span>(</span>
<span id="cb1-9"><a aria-label="9"></a>    <span class="at">mean_length =</span> <span class="fu">mean</span>(length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-10"><a aria-label="10"></a>    <span class="at">sd_length =</span> <span class="fu">sd</span>(length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-11"><a aria-label="11"></a>    <span class="at">se_length =</span> sd_length<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(length_mm))),</span>
<span id="cb1-12"><a aria-label="12"></a>    <span class="at">count =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(length_mm)),</span>
<span id="cb1-13"><a aria-label="13"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb1-14"><a aria-label="14"></a>grayling_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  lake  mean_length sd_length se_length count
  &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
1 I3           266.      28.3      3.48    66
2 I8           363.      52.3      5.18   102</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="probability-distributions" class="slide level2">
<h2>Probability Distributions</h2>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="probability-distribution-functions">Probability Distribution Functions</h3>
<ul>
<li>A <strong>probability distribution</strong> describes the probability of different outcomes in an experiment</li>
<li>We’ve seen histograms of observed data</li>
<li>Theoretical distributions help us model and understand real-world data</li>
<li>We will focus on a <strong>standard normal distribution</strong> and a <strong>students</strong> <strong>t distribution</strong></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reference</strong></p>
<p>Gotelli &amp; Ellison, <em>A Primer of Ecological Statistics</em>, Ch. 2 — Random Variables and Probability Distributions.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-04-1.png" alt="The dodged histogram of Arctic grayling length by lake, repeated as context for introducing probability distributions." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-standard-normal-distribution" class="slide level2">
<h2>The Standard Normal Distribution</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>The standard normal distribution is crucial for understanding statistical inference:</p>
<ul>
<li>Has mean (μ) = 0 and standard deviation (σ) = 1</li>
<li>Symmetrical bell-shaped curve</li>
<li>Area under the curve = 1 (total probability)</li>
<li><strong>Approximately</strong>:
<ul>
<li>68% of data within ±1σ of the mean</li>
<li><strong>95% of data within ±2σ of the mean - really 1.96σ</strong></li>
<li>99.7% of data within ±3σ of the mean</li>
</ul></li>
</ul>
<p>Z-scores allow us to convert any <strong>normal distribution</strong> to the <strong>standard normal distribution.</strong></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reference</strong></p>
<p>Whitlock &amp; Schluter, <em>Analysis of Biological Data</em>, Ch. 10 — The Normal Distribution.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-05-1.png" alt="Standard normal density curve with vertical lines and labels marking -3 through 3 standard deviations from the mean." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="practice-exercise-2-calculating-z-scores-of-lake-i3" class="slide level2">
<h2>Practice Exercise 2: Calculating Z-scores of lake I3</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 2: Calculating Z-scores</strong></p>
</div>
<div class="callout-content">
<p>Let’s practice converting raw values to Z-scores using the Arctic grayling data.</p>
<p><strong>Z Score = (length - mean) / standard deviation</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="co"># Calculate the mean and standard deviation of fish lengths</span></span>
<span id="cb3-2"><a aria-label="2"></a>mean_length <span class="ot">&lt;-</span> <span class="fu">mean</span>(i3_df<span class="sc">$</span>length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-3"><a aria-label="3"></a>sd_length <span class="ot">&lt;-</span> <span class="fu">sd</span>(i3_df<span class="sc">$</span>length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-4"><a aria-label="4"></a></span>
<span id="cb3-5"><a aria-label="5"></a><span class="co"># Calculate Z-scores for fish lengths</span></span>
<span id="cb3-6"><a aria-label="6"></a>i3_df <span class="ot">&lt;-</span> i3_df <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a aria-label="7"></a>  <span class="fu">mutate</span>(<span class="at">z_score =</span> (length_mm <span class="sc">-</span> mean_length) <span class="sc">/</span> sd_length)</span>
<span id="cb3-8"><a aria-label="8"></a></span>
<span id="cb3-9"><a aria-label="9"></a><span class="co"># View the first few rows with Z-scores</span></span>
<span id="cb3-10"><a aria-label="10"></a><span class="fu">head</span>(i3_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
   site lake  species         length_mm mass_g z_score
  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;               &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1   113 I3    arctic grayling       266    135  0.0139
2   113 I3    arctic grayling       290    185  0.862 
3   113 I3    arctic grayling       262    145 -0.127 
4   113 I3    arctic grayling       275    160  0.332 
5   113 I3    arctic grayling       240    105 -0.905 
6   113 I3    arctic grayling       265    145 -0.0214</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-fish-data-as-a-z-score" class="slide level2">
<h2>The fish data as a z score</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>So if we plot this data what does it look like in a standard normal distributon?</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-07-1.png" alt="Histogram of z-scores for Lake I3 grayling lengths, showing the shape of the standardized length distribution." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="z-score-results" class="slide level2">
<h2>Z-score Results</h2>
<h3 id="how-to-get-area-under-1-std-dev">How to get area under 1 STD DEV?</h3>
<p>Proportion within 1 standard deviation = sum of absolute values of Z Scores that are less than or equal to 1 divided by the number in the sample…</p>
<p>Remember in a true normal distribution it is 68% within 1 std dev.</p>
<p>should be <strong>approximately (varies if distribution is not normal)</strong>:</p>
<ul>
<li>68% of data within ±1σ of the mean</li>
<li><strong>95% of data within ±2σ of the mean - really 1.96σ</strong></li>
<li>99.7% of data within ±3σ of the mean</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a><span class="co"># What proportion of fish are within 1 standard deviation of the mean?</span></span>
<span id="cb5-2"><a aria-label="2"></a>within_1sd <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">abs</span>(i3_df<span class="sc">$</span>z_score) <span class="sc">&lt;=</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(i3_df<span class="sc">$</span>z_score))</span>
<span id="cb5-3"><a aria-label="3"></a><span class="fu">cat</span>(<span class="st">"Proportion within 1 SD:"</span>, <span class="fu">round</span>(within_1sd <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion within 1 SD: 81.8 %</code></pre>
</div>
</div>
</section>
<section id="standard-normal-distribution---fish-data" class="slide level2">
<h2>Standard normal distribution - Fish Data</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>You want to know things about this population like</p>
<ul>
<li>probability of a fish having a certain length (e.g., &gt; 300 mm)</li>
<li>Can solve this by integrating the area under curve</li>
<li>But it is tedious to do every time</li>
<li>Instead
<ul>
<li>we can use the <em>standard normal distribution</em> (SND)</li>
<li>and can use the proportions from the density curve</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  mean_length
        &lt;dbl&gt;
1        266.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-09-1.png" alt="Histogram of Lake I3 grayling length in millimeters, with a red vertical line and label marking a length of 266 mm." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="standard-normal-distribution-properties" class="slide level2">
<h2>Standard normal distribution properties</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Standard Normal Distribution</p>
<ul>
<li>“benchmark” normal distribution with µ = 0, σ = 1</li>
<li>The Standard Normal Distribution is defined so that:
<ul>
<li><p>~68% of the curve area within +/- 1 σ of the mean,</p></li>
<li><p>~95% within +/- 2 σ of the mean,</p></li>
<li><p>~99.7% within +/- 3 σ of the mean</p></li>
</ul></li>
</ul>
<p>*remember σ = standard deviation</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-10-1.png" alt="Histogram of z-scores for Lake I3 grayling lengths, with vertical lines marking the mean and the ±1, ±2, and ±3 standard deviation boundaries, illustrating the z-distribution." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="using-z-tables" class="slide level2">
<h2>Using Z-tables</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Areas under curve of Standard Normal Distribution</p>
<ul>
<li>Have been calculated for a range of sample sizes</li>
<li>Can be looked up in z-table</li>
<li>No need to integrate</li>
<li>Any normally distributed data can be standardized
<ul>
<li><p>transformed into the standard normal distribution</p></li>
<li><p>a value can be looked up in a table</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-11-1.png" alt="The Lake I3 z-distribution histogram repeated, shown in the context of using z-tables to look up areas under the standard normal curve." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="z-score-formula" class="slide level2">
<h2>Z-score Formula</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Done by converting original data points to z-scores</p>
<ul>
<li>Z-scores calculated as:</li>
</ul>
<h3 id="textz-fracx_i-musigma"><span class="math inline">\(\text{Z = }\frac{x_i-\mu}{\sigma}\)</span></h3>
<ul>
<li>z = z-score for observation</li>
<li>xi = original observation</li>
<li>µ = mean of data distribution</li>
<li>σ = SD of data distribution</li>
</ul>
<p>So lets do this for a fish that is 300mm long and guess the probability of catching something larger</p>
<p>z = (300 - 265.61)/28.3 = 1.215194</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-12-1.png" alt="The Lake I3 z-distribution histogram repeated, shown alongside the worked z-score calculation for a 300 mm fish." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="z-score-example-from-table" class="slide level2">
<h2>Z-score example from table</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Done by converting original data points to z-scores</p>
<ul>
<li>Z-scores calculated as:</li>
</ul>
<h3 id="textz-fracx_i-musigma-1"><span class="math inline">\(\text{Z = }\frac{X_i-\mu}{\sigma}\)</span></h3>
<ul>
<li>z = z-score for observation</li>
<li>xi = original observation</li>
<li>µ = mean of data distribution</li>
<li>σ = SD of data distribution</li>
</ul>
<p>So lets do this for a fish that is 300mm long and guess the probability of catching something larger</p>
<ul>
<li>z = (300 - 265.61)/28.3 = 1.22</li>
<li>look up 1.2 on left and 0.02 on top to get 0.8888 in table</li>
<li>Means 88.9% is the area left of the curve <strong>and</strong></li>
<li>100 - 88.9 = 11.27% of fish are expected to be longer</li>
</ul>
<p><strong>At what point do you think its not likely to catch a larger fish - what percentage?</strong></p>
<p>do this the other way using that percent and why?</p>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-1995791111.png" width="380" height="367"></p>
<figcaption>Standard normal (Z) table giving the cumulative area to the left of z for z-values from 0.0 to 3.4 in rows and hundredths in columns, used to look up the proportion of a normal distribution below a given z-score.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="z-score-example-calculation-in-r" class="slide level2">
<h2>Z-score example calculation in r</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>We can use R to get these values easier…</p>
<p># For standard normal distribution (mean=0, sd=1):</p>
<ul>
<li>pnorm(z) # gives cumulative probability (area to the left)</li>
<li>qnorm(p) # gives z-value for a given probability</li>
<li>dnorm(z) # gives probability density</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-label="1"></a><span class="co"># Examples:</span></span>
<span id="cb8-2"><a aria-label="2"></a>z_value <span class="ot">&lt;-</span>  <span class="fl">1.22</span></span>
<span id="cb8-3"><a aria-label="3"></a>prob_left <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z_value)          <span class="co"># 0.975 (97.5% to the left)</span></span>
<span id="cb8-4"><a aria-label="4"></a>prob_right <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(z_value)     <span class="co"># 0.025 (2.5% to the right)</span></span>
<span id="cb8-5"><a aria-label="5"></a>prob_between <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="dv">2</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">2</span>)  <span class="co"># 0.95 (95% between ±1.96)</span></span>
<span id="cb8-6"><a aria-label="6"></a><span class="co"># To find z-value for a given probability:</span></span>
<span id="cb8-7"><a aria-label="7"></a>z_for_95_percent <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.888</span>)     <span class="co"># 1.96</span></span>
<span id="cb8-8"><a aria-label="8"></a><span class="fu">print</span>(prob_left)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8887676</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-label="1"></a><span class="fu">print</span>(prob_right)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1112324</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-label="1"></a><span class="fu">print</span>(prob_between)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9544997</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-label="1"></a><span class="fu">print</span>(z_for_95_percent)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.21596</code></pre>
</div>
</div>
</div></div>
</section>
<section id="we-can-now-use-this-for-fun-in-the-fish" class="slide level2">
<h2>We can now use this for fun in the fish</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Lets say we are interested in knowing at what point from I3 it is not likely to catch a larger fish?</p>
<p>Maybe we expect 95% of the time to catch a fish that is “common” but the 5% is the unlikely portion….</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-label="1"></a><span class="co"># Examples:</span></span>
<span id="cb16-2"><a aria-label="2"></a><span class="co"># What fish length corresponds to the top 5% (unlikely)?</span></span>
<span id="cb16-3"><a aria-label="3"></a>top_5_percent_z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.95</span>)  <span class="co"># z-score for 95th percentile</span></span>
<span id="cb16-4"><a aria-label="4"></a>unlikely_length <span class="ot">&lt;-</span> mean_length <span class="sc">+</span> (top_5_percent_z <span class="sc">*</span> sd_length)</span>
<span id="cb16-5"><a aria-label="5"></a></span>
<span id="cb16-6"><a aria-label="6"></a><span class="fu">cat</span>(<span class="st">"Only 5% of fish are longer than:"</span>, <span class="fu">round</span>(unlikely_length, <span class="dv">1</span>), <span class="st">"mm</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Only 5% of fish are longer than: 312.2 mm</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-label="1"></a><span class="fu">cat</span>(<span class="st">"This corresponds to z-score:"</span>, <span class="fu">round</span>(top_5_percent_z, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>This corresponds to z-score: 1.645 </code></pre>
</div>
</div>
</div></div>
</section>
<section id="what-this-means" class="slide level2">
<h2>What this means</h2>
<p>Given that we can: transform data to z-scores from standard normal distribution…</p>
<p>…figure out area under the curve (probability) associated with range of z-scores…</p>
<p>…can therefore figure out probability associated with a range of original data</p>
</section>
<section id="so-what-is-next" class="slide level2">
<h2>So what is next…</h2>
<p>We can look at Standard normal distributions and know probability of a value being in a range under the standard normal curve…</p>
<p>Previously we had calculated Standard Error and Confidence Intervals -</p>
<ul>
<li>Now can assess our confidence that the population mean is within a certain range<br>
</li>
<li>Can use t distribution to ask questions like:
<ul>
<li>“What is probability of getting sample with mean = ȳ from population with mean = µ?“ (1 sample t-test)<br>
</li>
<li>“What is the probability that two samples came from same population?” (2 sample t-test)</li>
</ul></li>
</ul>
</section>
<section id="when-population-σ-is-unknown" class="slide level2">
<h2>When Population σ is Unknown</h2>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="when-calculating-confidence-intervals-we-usually-dont-know-the-population-σ-standard-deviation-or-𝝁-population-mean">When calculating confidence intervals we usually DON’T know the population σ (standard deviation) or 𝝁 population mean</h3>
<ul>
<li>estimate it from the samples when don’t know the population σ or 𝝁</li>
<li>and when sample size is small &lt; ~30</li>
<li>can’t use the standard normal (z) distribution</li>
</ul>
<p><em>Instead, we use Student’s t distribution</em></p>
</div><div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-1052237789.png" width="239" height="307"></p>
<figcaption>Vintage photo of William Sealy Gosset (the statistician ‘Student’ who derived the t-distribution while working at the Guinness brewery), edited with a speech bubble saying ‘Cheers!’ and a pint of Guinness beer beside him, a humorous nod to why the t-test is called ‘Student’s t-test.’</figcaption>
</figure>
</div>
</div>
</section>
<section id="understanding-t-distribution" class="slide level2">
<h2>Understanding t-distribution</h2>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="when-sample-sizes-are-small-the-t-distribution-is-more-appropriate-than-the-normal-distribution.">When sample sizes are small, the <strong>t-distribution</strong> is more appropriate than the normal distribution.</h3>
<ul>
<li>Similar to normal distribution but with heavier tails</li>
<li>Shape depends on <strong>degrees of freedom</strong> (df = n-1)</li>
<li>With large df (&gt;30), approaches the normal distribution</li>
<li>Used for:
<ul>
<li><p>Small sample sizes</p></li>
<li><p>When population standard deviation is unknown</p></li>
<li><p>Calculating confidence intervals</p></li>
<li><p>Conducting t-tests</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-13-1.png" alt="Overlaid density curves comparing the standard normal distribution (dashed black) to t-distributions with 3, 10, and 30 degrees of freedom, showing the t-distribution's heavier tails at low degrees of freedom converging toward the normal curve as df increases." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="students-t-distribution-formula" class="slide level2">
<h2>Student’s t-distribution Formula</h2>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="to-calculate-ci-for-sample-from-unknown-population">To calculate CI for sample from “unknown” population:</h3>
<h3 id="textci-bary-pm-t-cdot-fracssqrtn"><span class="math inline">\(\text{CI} = \bar{y} \pm t \cdot \frac{s}{\sqrt{n}}\)</span></h3>
<p>Where:</p>
<ul>
<li>ȳ is sample mean</li>
<li>𝑛 is sample size</li>
<li>s is sample standard deviation</li>
<li>t t-value corresponding the probability of the CI</li>
<li>t in t-table for different degrees of freedom (n-1)</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-3203878802.png" width="380" height="392"></p>
<figcaption>Student’s t critical-value table with one-tail and two-tail probabilities across the columns and degrees of freedom down the rows, used to look up the t-value for a chosen confidence level and sample size.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="students-t-distribution-table" class="slide level2">
<h2>Student’s t-distribution Table</h2>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="here-is-a-t-table">Here is a t-table</h3>
<ul>
<li>Values of t that correspond to probabilities</li>
<li>Probabilities listed along top</li>
<li>Sample dfs are listed in the left-most column</li>
<li>Probabilities are given for one-tailed and two-tailed “questions”</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-3203878802.png" width="380" height="410"></p>
<figcaption>The same Student’s t critical-value table repeated, with probabilities along the top and degrees of freedom down the left column, illustrating how to read off a critical t-value for a given df and confidence level.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="one-tailed-questions" class="slide level2">
<h2>One-tailed Questions</h2>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="one-tailed-questions-area-of-distribution-left-or-right-of-a-certain-value">One-tailed questions: area of distribution left or (right) of a certain value</h3>
<ul>
<li>n=20 (df=19) - 90% of the observations found left</li>
<li>t= 1.328 (10% are outside)</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-1822465473.png" width="180" height="150"></p>
<figcaption>Bell-shaped t-distribution curve with the area to the left of t = 1.328 shaded, illustrating a one-tailed cutoff.</figcaption>
</figure>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-641796945.png" width="380" height="405"></p>
<figcaption>Student’s t critical-value table with the one-tail 0.10 column and df = 19 row highlighted, intersecting at the critical value 1.328, the value used for a one-tailed test with n = 20.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="two-tailed-questions" class="slide level2">
<h2>Two-tailed Questions</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Two-tailed questions refer to area between certain values</p>
<ul>
<li>n= 20 (df=19), 90% of the observations are between</li>
<li>t=-1.729 and t=1.729 (10% are outside)</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-2234740159.png" width="276" height="200"></p>
<figcaption>Bell-shaped t-distribution curve with both tails shaded beyond t = -1.729 and t = 1.729, illustrating a two-tailed cutoff.</figcaption>
</figure>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-1734806681.png" width="380" height="464"></p>
<figcaption>Student’s t critical-value table with the two-tail 0.10 column and df = 19 row highlighted, intersecting at the critical value 1.729, the value used for a two-tailed test with n = 20.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="t-distribution-ci-example" class="slide level2">
<h2>t-distribution CI Example</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Let’s calculate CIs again:</p>
<p>Use two-sided test</p>
<h3 id="textci-bary-pm-t-cdot-fracssqrtn-1"><span class="math inline">\(\text{CI} = \bar{y} \pm t \cdot \frac{s}{\sqrt{n}}\)</span></h3>
<ul>
<li>95% CI Sample A: = 272.8 ± 2.306 * (37.81/(9^0.5))</li>
<li>mean = 272.8, N = 20, and s = 37.81 - t is ?</li>
<li>CI = 29.06</li>
<li>The 95% CI is between 243.7 and 301.9</li>
<li>“The 95% CI for the population mean from sample A is 272.8 ± 29.06</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-3959630930.png"></p>
<figcaption>Student’s t critical-value table with the two-tail 0.05 column and df = 8 row highlighted, intersecting at the critical value 2.306, the value used to compute the 95% confidence interval in this worked example.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="practice-exercise-4-using-the-t-distribution" class="slide level2">
<h2>Practice Exercise 4: Using the t-distribution</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 4: Using the t-distribution</strong></p>
</div>
<div class="callout-content">
<p>Let’s compare confidence intervals using the normal approximation (z) versus the t-distribution for our fish data. I3 data and 10 fish Mean is 266.7 - sd is 17.12 - se is 5.41</p>
<p>## <span class="math inline">\(\text{CI} = \bar{y} \pm t \cdot \frac{s}{\sqrt{n}}\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-label="1"></a><span class="co"># Display results</span></span>
<span id="cb20-2"><a aria-label="2"></a><span class="fu">cat</span>(<span class="st">"Mean:"</span>, <span class="fu">round</span>(sample_mean, <span class="dv">1</span>), <span class="st">"mm</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb20-3"><a aria-label="3"></a>    <span class="st">"Standard deviation:"</span>, <span class="fu">round</span>(sample_sd, <span class="dv">2</span>), <span class="st">"mm</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb20-4"><a aria-label="4"></a>    <span class="st">"Standard error:"</span>, <span class="fu">round</span>(sample_se, <span class="dv">2</span>), <span class="st">"mm</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb20-5"><a aria-label="5"></a>    <span class="st">"95% CI using z:"</span>, <span class="fu">round</span>(z_ci_lower, <span class="dv">1</span>), <span class="st">"to"</span>, <span class="fu">round</span>(z_ci_upper, <span class="dv">1</span>), <span class="st">"mm</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb20-6"><a aria-label="6"></a>    <span class="st">"95% CI using t:"</span>, <span class="fu">round</span>(t_ci_lower, <span class="dv">1</span>), <span class="st">"to"</span>, <span class="fu">round</span>(t_ci_upper, <span class="dv">1</span>), <span class="st">"mm</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb20-7"><a aria-label="7"></a>    <span class="st">"t critical value:"</span>, <span class="fu">round</span>(t_crit, <span class="dv">3</span>), <span class="st">"vs z critical value: 1.96</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean: 269.2 mm
 Standard deviation: 11.59 mm
 Standard error: 3.67 mm
 95% CI using z: 262 to 276.4 mm
 95% CI using t: 260.9 to 277.5 mm
 t critical value: 2.262 vs z critical value: 1.96</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="intro-to-hypothesis-testing-one-tailed-the-numbers" class="slide level2 scrollable">
<h2>Intro to Hypothesis Testing (One-Tailed) — The Numbers</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Hypothesis testing is a systematic way to evaluate research questions using data.</p>
<p><strong>Key components:</strong></p>
<ol type="1">
<li><p><strong>Null hypothesis (H₀)</strong>: Typically assumes “no effect” or “no difference”</p></li>
<li><p><strong>Alternative hypothesis (Hₐ)</strong>: The claim we’re trying to support</p></li>
<li><p><strong>Statistical test</strong>: Method for evaluating evidence against H₀</p></li>
<li><p><strong>P-value</strong>: Probability of observing our results (or more extreme) if H₀ is true</p></li>
<li><p><strong>Significance level (α)</strong>: Threshold for rejecting H₀, typically 0.05</p></li>
</ol>
<p><strong>Decision rule</strong>: Reject H₀ if p-value &lt; α<br>
<br>
lets test if our sample mean of 320 is larger than 270 or not? Essentially we are looking at the confidence intervals!!! But we are only interested if it is larger</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reference</strong></p>
<p>Gotelli &amp; Ellison, Ch. 4 — Framing and Testing Hypotheses.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Summary of One-Tailed Hypothesis Test:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample mean: 320 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Hypothesized mean: 285 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size: 12 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard deviation: 42.15 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard error: 12.168 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: 2.876 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Critical t-value (one-tailed): 1.796 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Critical value: 306.85 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Decision: Reject Ho (sample mean falls in upper rejection region)</code></pre>
</div>
</div>
</div></div>
</section>
<section id="intro-to-hypothesis-testing-one-tailed-the-picture" class="slide level2 scrollable">
<h2>Intro to Hypothesis Testing (One-Tailed) — The Picture</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Hypothesis testing is a systematic way to evaluate research questions using data.</p>
<p><strong>Key components:</strong></p>
<ol type="1">
<li><p><strong>Null hypothesis (H₀)</strong>: Typically assumes “no effect” or “no difference”</p></li>
<li><p><strong>Alternative hypothesis (Hₐ)</strong>: The claim we’re trying to support</p></li>
<li><p><strong>Statistical test</strong>: Method for evaluating evidence against H₀</p></li>
<li><p><strong>P-value</strong>: Probability of observing our results (or more extreme) if H₀ is true</p></li>
<li><p><strong>Significance level (α)</strong>: Threshold for rejecting H₀, typically 0.05</p></li>
</ol>
<p><strong>Decision rule</strong>: Reject H₀ if p-value &lt; α<br>
<br>
lets test if our sample mean of 320 is larger than 270 or not? Essentially we are looking at the confidence intervals!!! But we are only interested if it is larger</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-17-1.png" alt="One-tailed t-test rejection region plot on the measurement scale, with a red shaded rejection region above the critical value, a blue vertical line at the hypothesized mean (285), and a green vertical line at the observed sample mean (320), which falls inside the rejection region." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="hypothesis-testing-two-tailed-the-numbers" class="slide level2 scrollable">
<h2>Hypothesis Testing (Two-Tailed) — The Numbers</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Hypothesis testing is a systematic way to evaluate research questions using data.</p>
<p><strong>Key components:</strong></p>
<ol type="1">
<li><strong>Null hypothesis (H₀)</strong>: Typically assumes “no effect” or “no difference”</li>
<li><strong>Alternative hypothesis (Hₐ)</strong>: The claim we’re trying to support</li>
<li><strong>Statistical test</strong>: Method for evaluating evidence against H₀</li>
<li><strong>P-value</strong>: Probability of observing our results (or more extreme) if H₀ is true</li>
<li><strong>Significance level (α)</strong>: Threshold for rejecting H₀, typically 0.05</li>
</ol>
<p><strong>Decision rule</strong>: Reject H₀ if p-value &lt; α</p>
<p>lets test if our sample mean of 320 is equal to 270 or not? Essentially we are looking at the confidence intervals!!!<br>
</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Summary of Hypothesis Test:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample mean: 320 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Hypothesized mean: 270 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard error: 12.603 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: 3.967 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Critical t-value (±): 2.306 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Critical values: 240.94 to 299.06 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Decision: Reject Ho (sample mean falls in rejection region)</code></pre>
</div>
</div>
</div></div>
</section>
<section id="hypothesis-testing-two-tailed-the-picture" class="slide level2 scrollable">
<h2>Hypothesis Testing (Two-Tailed) — The Picture</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Hypothesis testing is a systematic way to evaluate research questions using data.</p>
<p><strong>Key components:</strong></p>
<ol type="1">
<li><strong>Null hypothesis (H₀)</strong>: Typically assumes “no effect” or “no difference”</li>
<li><strong>Alternative hypothesis (Hₐ)</strong>: The claim we’re trying to support</li>
<li><strong>Statistical test</strong>: Method for evaluating evidence against H₀</li>
<li><strong>P-value</strong>: Probability of observing our results (or more extreme) if H₀ is true</li>
<li><strong>Significance level (α)</strong>: Threshold for rejecting H₀, typically 0.05</li>
</ol>
<p><strong>Decision rule</strong>: Reject H₀ if p-value &lt; α</p>
<p>lets test if our sample mean of 320 is equal to 270 or not? Essentially we are looking at the confidence intervals!!!</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-19-1.png" alt="Two-tailed t-test rejection region plot on the measurement scale, with red shaded rejection regions in both tails beyond the critical values, a blue vertical line at the hypothesized mean (270), and a green vertical line at the observed sample mean (320), which falls in the upper rejection region." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="practice-exercise-5-one-sample-t-test" class="slide level2 scrollable">
<h2>Practice Exercise 5: One-Sample t-Test</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 5: Lets practice a One-Sample t-Test</strong></p>
</div>
<div class="callout-content">
<p>Let’s perform a one-sample t-test to determine if the mean fish length in Lake I3 differs from 260 mm:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a aria-label="1"></a><span class="co"># get only lake I3</span></span>
<span id="cb40-2"><a aria-label="2"></a>i3_df <span class="ot">&lt;-</span> grayling_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lake<span class="sc">==</span><span class="st">"I3"</span>)</span>
<span id="cb40-3"><a aria-label="3"></a></span>
<span id="cb40-4"><a aria-label="4"></a><span class="co"># what is the mean</span></span>
<span id="cb40-5"><a aria-label="5"></a>i3_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(i3_df<span class="sc">$</span>length_mm, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb40-6"><a aria-label="6"></a><span class="fu">cat</span>(<span class="st">"Mean:"</span>, <span class="fu">round</span>(i3_mean, <span class="dv">1</span>), <span class="st">"mm</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean: 265.6 mm</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a aria-label="1"></a><span class="co"># Perform a one-sample t-test</span></span>
<span id="cb42-2"><a aria-label="2"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(i3_df<span class="sc">$</span>length_mm, <span class="at">mu =</span> <span class="dv">260</span>)</span>
<span id="cb42-3"><a aria-label="3"></a></span>
<span id="cb42-4"><a aria-label="4"></a><span class="co"># View the test results</span></span>
<span id="cb42-5"><a aria-label="5"></a>t_test_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  i3_df$length_mm
t = 1.6091, df = 65, p-value = 0.1124
alternative hypothesis: true mean is not equal to 260
95 percent confidence interval:
 258.6481 272.5640
sample estimates:
mean of x 
 265.6061 </code></pre>
</div>
</div>
<p>Interpret this test result by answering these questions:</p>
<ol type="1">
<li>What was the null hypothesis?</li>
<li>What was the alternative hypothesis?</li>
<li>What does the p-value tell us?</li>
<li>Should we reject or fail to reject the null hypothesis at α = 0.05?</li>
<li>What is the practical interpretation of this result for fish biologists?</li>
</ol>
</div>
</div>
</div>
</section>
<section id="practice-exercise-6-formulating-hypotheses" class="slide level2 scrollable">
<h2>Practice Exercise 6: Formulating Hypotheses</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 6: Formulating Hypotheses</strong></p>
</div>
<div class="callout-content">
<p>For the following research questions about Arctic grayling, write the null and alternative hypotheses:</p>
<ol type="1">
<li>Are fish in Lake I8 longer than fish in Lake I3?</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a aria-label="1"></a><span class="co"># Let's test one of these hypotheses: Are fish in Lake I8 longer than fish in Lake I3?</span></span>
<span id="cb44-2"><a aria-label="2"></a></span>
<span id="cb44-3"><a aria-label="3"></a><span class="co"># Perform an independent t-test</span></span>
<span id="cb44-4"><a aria-label="4"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(length_mm <span class="sc">~</span> lake, <span class="at">data =</span> grayling_df, </span>
<span id="cb44-5"><a aria-label="5"></a>                       <span class="at">alternative =</span> <span class="st">"less"</span>)  <span class="co"># H₀: μ_I3 ≥ μ_I8, H₁: μ_I3 &lt; μ_I8</span></span>
<span id="cb44-6"><a aria-label="6"></a></span>
<span id="cb44-7"><a aria-label="7"></a><span class="co"># Display the results</span></span>
<span id="cb44-8"><a aria-label="8"></a>t_test_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  length_mm by lake
t = -15.532, df = 161.63, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group I3 and group I8 is less than 0
95 percent confidence interval:
      -Inf -86.66138
sample estimates:
mean in group I3 mean in group I8 
        265.6061         362.5980 </code></pre>
</div>
</div>
<p>Based on this t-test, what can we conclude about the difference in fish length between the two lakes?</p>
</div>
</div>
</div>
</section>
<section id="understanding-p-values" class="slide level2">
<h2>Understanding P-values</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>A <strong>p-value</strong> is the probability of observing the sample result (or something more extreme) if the null hypothesis is true.</p>
<p><strong>Common interpretations:</strong></p>
<ul>
<li>- p &lt; 0.05: Strong evidence against H₀</li>
<li>- 0.05 ≤ p &lt; 0.10: Moderate evidence against H₀</li>
<li>- p ≥ 0.10: Insufficient evidence against H₀</li>
</ul>
<p><strong>Common misinterpretations:</strong></p>
<ul>
<li>- p-value is NOT the probability that H₀ is true</li>
<li>- p-value is NOT the probability that results occurred by chance</li>
<li>- Statistical significance ≠ practical significance</li>
<li>the smaller the p value does not necessarily mean much… use &lt; 0.05 even if is is 10^-16</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-22-1.png" alt="Standard normal density curve with a red dashed vertical line marking an observed test statistic (z = 2.1) and the area under the curve beyond it shaded blue to represent the p-value." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="type-i-and-type-ii-errors" class="slide level2">
<h2>Type I and Type II Errors</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>When making decisions based on hypothesis tests, two types of errors can occur:</p>
<p><strong>Type I Error (False Positive)</strong></p>
<ul>
<li>- Rejecting H₀ when it’s actually true</li>
<li>- Probability = α (significance level)</li>
<li>- “Finding an effect that isn’t real”</li>
</ul>
<p><strong>Type II Error (False Negative)</strong></p>
<ul>
<li>- Failing to reject H₀ when it’s actually false</li>
<li>- Probability = β - “Missing an effect that is real”</li>
</ul>
<p><strong>Statistical Power = 1 - β</strong></p>
<ul>
<li>- Probability of correctly rejecting a false H₀</li>
<li>- Increases with:
<ul>
<li><p>- Larger sample size</p></li>
<li><p>- Larger effect size</p></li>
<li><p>- Lower variability</p></li>
<li><p>- Higher α level</p></li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-23-1.png" alt="Overlapping density curves for a null distribution (black) centered at 0 and an alternative distribution (green) centered at 3, with the Type I error region shaded red beyond the critical value under the null curve, and the Type II error region shaded blue under the alternative curve below the critical value." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="type-i-and-type-ii-errors-what-it-means" class="slide level2">
<h2>Type I and Type II Errors — What It Means</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>What does it mean…
<ul>
<li><p>Black curve (Null Distribution): distribution of test statistics when Ho is true</p></li>
<li><p>Green curve (Alternative Distribution): distribution when Ha is true (is an effect)</p></li>
</ul></li>
<li>Red shaded area (Type I Error): probability of rejecting Ho when it’s actually tru
<ul>
<li>area under the null distribution (black curve) to the right α (p=0.05)</li>
</ul></li>
<li>Blue shaded area (Type II Error): probability of failing to reject Ho when alternative is actually true
<ul>
<li>area under alternative distribution (green curve) left of α (depends on effect size, sample size, etc.)</li>
</ul></li>
</ul>
<p>The Key Insight fundamental trade-off in hypothesis testing:</p>
<ul>
<li>as α value moves left or right, change balance between Type I and Type II errors</li>
<li>Moving left reduces Type II errors increases Type I errors, and vice versa</li>
<li>power (1 - β) area under the green curve RIGHT of dashed line</li>
<li>the probability of correctly detecting a real effect.</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-24-1.png" alt="The Type I and Type II error density-curve plot repeated, shown alongside the explanation of what the red and blue shaded regions mean." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="practice-exercise-7-interpreting-errors-and-power" class="slide level2 scrollable">
<h2>Practice Exercise 7: Interpreting Errors and Power</h2>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practice Exercise 7: Interpreting P-values and Errors</strong></p>
</div>
<div class="callout-content">
<p>Given the following scenarios, identify whether a Type I or Type II error might have occurred:</p>
<ol type="1">
<li><p>A researcher concludes that a new fishing regulation increased grayling size, when in fact it had no effect.</p></li>
<li><p>A study fails to detect a real decline in grayling population due to warming water, concluding there was no effect.</p></li>
<li><p>Let’s calculate the power of our t-test to detect a 30 mm difference in length between lakes:</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a aria-label="1"></a><span class="co"># Calculate power for detecting a 30 mm difference</span></span>
<span id="cb46-2"><a aria-label="2"></a><span class="co"># First determine parameters</span></span>
<span id="cb46-3"><a aria-label="3"></a>lake_I3 <span class="ot">&lt;-</span> grayling_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lake <span class="sc">==</span> <span class="st">"I3"</span>)</span>
<span id="cb46-4"><a aria-label="4"></a>lake_I8 <span class="ot">&lt;-</span> grayling_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lake <span class="sc">==</span> <span class="st">"I8"</span>) </span>
<span id="cb46-5"><a aria-label="5"></a></span>
<span id="cb46-6"><a aria-label="6"></a>n1 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(lake_I3)</span>
<span id="cb46-7"><a aria-label="7"></a>n2 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(lake_I8)</span>
<span id="cb46-8"><a aria-label="8"></a>sd_pooled <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((<span class="fu">var</span>(lake_I3<span class="sc">$</span>length_mm) <span class="sc">*</span> (n1<span class="dv">-1</span>) <span class="sc">+</span> </span>
<span id="cb46-9"><a aria-label="9"></a>                  <span class="fu">var</span>(lake_I8<span class="sc">$</span>length_mm) <span class="sc">*</span> (n2<span class="dv">-1</span>)) <span class="sc">/</span> </span>
<span id="cb46-10"><a aria-label="10"></a>                  (n1 <span class="sc">+</span> n2 <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb46-11"><a aria-label="11"></a></span>
<span id="cb46-12"><a aria-label="12"></a><span class="co"># Calculate power</span></span>
<span id="cb46-13"><a aria-label="13"></a>effect_size <span class="ot">&lt;-</span> <span class="dv">30</span> <span class="sc">/</span> sd_pooled  <span class="co"># Cohen's d</span></span>
<span id="cb46-14"><a aria-label="14"></a>df <span class="ot">&lt;-</span> n1 <span class="sc">+</span> n2 <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb46-15"><a aria-label="15"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb46-16"><a aria-label="16"></a>power <span class="ot">&lt;-</span> <span class="fu">power.t.test</span>(<span class="at">n =</span> <span class="fu">min</span>(n1, n2), </span>
<span id="cb46-17"><a aria-label="17"></a>                     <span class="at">delta =</span> effect_size,</span>
<span id="cb46-18"><a aria-label="18"></a>                     <span class="at">sd =</span> <span class="dv">1</span>,  <span class="co"># Using standardized effect size</span></span>
<span id="cb46-19"><a aria-label="19"></a>                     <span class="at">sig.level =</span> alpha,</span>
<span id="cb46-20"><a aria-label="20"></a>                     <span class="at">type =</span> <span class="st">"two.sample"</span>,</span>
<span id="cb46-21"><a aria-label="21"></a>                     <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb46-22"><a aria-label="22"></a></span>
<span id="cb46-23"><a aria-label="23"></a><span class="co"># Display results</span></span>
<span id="cb46-24"><a aria-label="24"></a>power</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 66
          delta = 0.6741298
             sd = 1
      sig.level = 0.05
          power = 0.9702076
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="summary" class="slide level2 scrollable">
<h2>Summary</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Key concepts covered:</strong></p>
<ol type="1">
<li><strong>Probability distributions</strong> model random phenomena
<ul>
<li>Normal distribution is especially important</li>
<li>Z-scores standardize measurements</li>
</ul></li>
<li><strong>Standard error</strong> measures precision of estimates
<ul>
<li>Decreases with larger sample sizes</li>
<li>Used to construct confidence intervals</li>
</ul></li>
<li><strong>Confidence intervals</strong> express uncertainty
<ul>
<li>Provide plausible range for parameters</li>
<li>95% CI: <code>mean ± 1.96 × SE</code></li>
</ul></li>
<li><strong>Hypothesis testing</strong> evaluates claims
<ul>
<li>Null vs.&nbsp;alternative hypotheses</li>
<li>P-values quantify evidence against H₀</li>
<li>Consider both statistical and practical significance</li>
</ul></li>
</ol>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="probability_inference_lecture_files/figure-revealjs/l04-26-1.png" alt="The Type I and Type II error density-curve plot repeated once more as a closing summary visual." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/ecostats_2026");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>