<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Nested / Multifactor ANOVA</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-b8eef193cd4aecd129dcd97c8f413977.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Nested / Multifactor ANOVA – UMD Biostatistics">
<meta property="og:description" content="Hands-on activity: nested and multifactor ANOVA.">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Nested / Multifactor ANOVA</h1>
  <p class="subtitle">Nested designs</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry 
</div>
</div>
</div>

</section>
<section id="lecture-13-data-overview" class="title-slide slide level1 center">
<h1>Lecture 13: Data Overview</h1>
<ul>
<li>The <strong>u_df</strong> dataframe contains observations with the following variables:
<ul>
<li><strong>patch</strong>: Random patches (1-16) where treatments were applied</li>
<li><strong>treat</strong>: Urchin density treatment - none, low, medium, high</li>
<li><strong>quad</strong>: Replicate quadrats within each patch: treatment combination</li>
<li><strong>algae</strong>: Percentage cover of filamentous algae (response variable)</li>
</ul></li>
</ul>
<div class="cell" data-collapese="true">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  treat      n  mean    sd    se   min   max
  &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 none      20  39.2 28.7  6.41      0    83
2 low       20  21.6 25.1  5.62      0    79
3 medium    20  19   25.7  5.74      0    71
4 high      20   1.3  3.18 0.711     0    13</code></pre>
</div>
</div>
</section>

<section id="plots" class="title-slide slide level1 center">
<h1>Plots</h1>

<img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-1-1.png" width="576" class="r-stretch"></section>

<section id="nested-anova-analysis" class="title-slide slide level1 center">
<h1>Nested ANOVA Analysis</h1>
<p>In this experimental design, patch is nested within treat because each patch received only one treatment level. This is a hierarchical design where the effect of patches must be considered within each treatment. Following the approach used in Quinn &amp; Keough (2002), we’ll use a traditional nested ANOVA.</p>
</section>

<section id="nested-anova-with-base-r" class="title-slide slide level1 center">
<h1>nested Anova with base R</h1>
<div class="cell" data-collapese="true">
<div class="cell-output cell-output-stdout">
<pre><code>
Error: treat:patch
          Df Sum Sq Mean Sq F value Pr(&gt;F)  
treat      3  14429    4810   2.717 0.0913 .
Residuals 12  21242    1770                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
          Df Sum Sq Mean Sq F value Pr(&gt;F)
Residuals 64  19110   298.6               </code></pre>
</div>
</div>
</section>

<section id="nested-anova-with-afex-package" class="title-slide slide level1 center">
<h1>Nested ANOVA with AFEX package</h1>
<ul>
<li>Using afex package (recommended for unbalanced designs)</li>
<li>The afex package is specifically designed for ANOVA with Type III SS
<ul>
<li>handles nested designs well</li>
</ul></li>
</ul>
<div class="cell" data-collapese="true">
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: algae
      num Df den Df    MSE      F     ges  Pr(&gt;F)  
treat      3     12 354.03 2.7171 0.40451 0.09126 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>

<section id="mixed-model-anova-with-random-effects" class="title-slide slide level1 center">
<h1>Mixed Model ANOVA with random effects</h1>
<ul>
<li>BOBYQA (Bound Optimization BY Quadratic Approximation)
<ul>
<li>optimization algorithm used in mixed-effects modeling</li>
<li>finds the best parameter values that maximize the likelihood function</li>
<li>especially useful when fitting complex models</li>
</ul></li>
<li>So the way to code
<ul>
<li>fixed effects is to put in the variable name</li>
<li><strong>random effects can be coded in a range of ways</strong>
<ul>
<li>samples within a larger grouping - treatment and subsample…</li>
<li><img data-src="images/paste-1.png" width="357"></li>
<li><strong>RANDOM INTERCEPT - FIXED SLOPE - <code>+ (1|random)</code></strong>
<ul>
<li>so color ~ fixed + (1|group)</li>
</ul></li>
<li><strong>RANDOM INTERCEPT - RANDOM SLOPE - <code>+ (fixed|random)</code></strong>
<ul>
<li>so color ~ fixed + (fixed|group)</li>
<li>equivalent to <code>algae ~ treat + (1 + fixed | random)</code></li>
</ul></li>
</ul></li>
<li><strong>Nested Design</strong> - such that a sample can exist only within a larger grouping</li>
<li><img data-src="images/paste-2.png" width="478">
<ul>
<li><strong>RANDOM INTERCEPT - FIXED SLOPE -</strong> <code>y ~ color + (1|green_box/grey_box)</code></li>
<li><code>y ~ color + (1 | greenbox) + (1 | green_box:grey_box)</code>. It models random variation in the intercept for each patch, and also for each quadrat within each patch</li>
<li><strong>RANDOM INTERCEPT - RANDOM SLOPE</strong> <code>y ~ color + (color|green_box/grey_box)</code></li>
</ul></li>
<li>Fully crossed design
<ul>
<li><img data-src="images/paste-3.png" width="492">
<ul>
<li>crossed design <strong>random intercept and random slope</strong>
<ul>
<li>y ~ color + (1 | green_box) + (1 | gray_box)</li>
</ul></li>
<li>crossed design <strong>random intercept and random slope</strong><br>
<code>y~ color + (color|green_box) + (color|gray_box)</code>
<ul>
<li><code>(color | green_box)</code> is shorthand for <code>(1 + color | green_box)</code>. This part of the formula specifies a random intercept and a random slope for the <code>color</code> variable within the levels of <code>green_box</code>.</li>
<li><code>(color | gray_box)</code> is shorthand for <code>(1 + color | gray_box)</code>. Similarly, this specifies a random intercept and a random slope for <code>color</code> within the levels of <code>gray_box</code></li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<div class="cell" data-collapese="true">
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: algae ~ treat + (1 | patch)
   Data: u_df
Control: lmerControl(calc.derivs = FALSE)

REML criterion at convergence: 682.2

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.9808 -0.3106 -0.1093  0.2831  2.5910 

Random effects:
 Groups   Name        Variance Std.Dev.
 patch    (Intercept) 294.3    17.16   
 Residual             298.6    17.28   
Number of obs: 80, groups:  patch, 16

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)   
(Intercept)   39.200      9.408  12.000   4.167  0.00131 **
treatlow     -17.650     13.305  12.000  -1.327  0.20934   
treatmedium  -20.200     13.305  12.000  -1.518  0.15485   
treathigh    -37.900     13.305  12.000  -2.849  0.01466 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) tretlw trtmdm
treatlow    -0.707              
treatmedium -0.707  0.500       
treathigh   -0.707  0.500  0.500</code></pre>
</div>
</div>
</section>

<section id="mixed-model-anova-with-random-effects-1" class="title-slide slide level1 center">
<h1>Mixed Model ANOVA with Random Effects</h1>
<ul>
<li><strong>METHOD 1 - the F-distribution with estimated degrees of freedom</strong>
<ul>
<li>Accounts for the uncertainty in variance component estimation</li>
<li>More conservative (higher p-values)</li>
<li>Better for small samples</li>
</ul></li>
<li><strong>METHOD 2 - the Chi Square</strong>
<ul>
<li>Assumes variance components are known (not estimated)</li>
<li>More liberal (lower p-values)</li>
<li>Assumes large samples</li>
</ul></li>
<li><strong>Relationship between these tests is</strong>
<ul>
<li>Chi-square = F × numerator df</li>
</ul></li>
<li><strong>Why Different Results?</strong>
<ul>
<li>F-test accounts for denominator df (12 in your case) - reflects sample size</li>
<li>Chi-square assumes infinite denominator df - assumes large samples</li>
</ul></li>
<li><strong>Rule of Thumb</strong>
<ul>
<li>under 100 observations or &lt; 20 random effect levels: Use F-test</li>
<li>over 500 observations and &gt; 50 random effect levels: Chi-square is okay</li>
<li>In between: F-test is safer</li>
</ul></li>
</ul>
<div class="cell" data-collapese="true">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type III Wald F tests with Kenward-Roger df)

Response: algae
                  F Df Df.res   Pr(&gt;F)   
(Intercept) 17.3616  1     12 0.001307 **
treat        2.7171  3     12 0.091262 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>

<section id="alternative-method-to-do-the-mixed-model-anova" class="title-slide slide level1 center">
<h1>Alternative method to do the mixed model ANOVA</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type III Wald chisquare tests)

Response: algae
              Chisq Df Pr(&gt;Chisq)    
(Intercept) 17.3616  1  0.0000309 ***
treat        8.1513  3    0.04299 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>

<section id="lecture-13-anova-results" class="title-slide slide level1 center">
<h1>Lecture 13: ANOVA Results</h1>
<p>The nested ANOVA model is specified as:</p>
<p><span class="math inline">\(algae_{ijk} = \mu + \alpha_i + \beta_{j(i)} + \epsilon_{ijk}\)</span></p>
<p>Where:</p>
<ul>
<li>- <span class="math inline">\(\mu\)</span> is the overall mean</li>
<li>- <span class="math inline">\(\alpha_i\)</span> is the fixed effect of treatment <span class="math inline">\(i\)</span></li>
<li>- <span class="math inline">\(\beta_{j(i)}\)</span> is the random effect of patch <span class="math inline">\(j\)</span> nested within treatment <span class="math inline">\(i\)</span></li>
<li>- <span class="math inline">\(\epsilon_{ijk}\)</span> is the residual error for quadrat <span class="math inline">\(k\)</span> in patch <span class="math inline">\(j\)</span> within treatment <span class="math inline">\(i\)</span></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type III Wald F tests with Kenward-Roger df)

Response: algae
                  F Df Df.res   Pr(&gt;F)   
(Intercept) 17.3616  1     12 0.001307 **
treat        2.7171  3     12 0.091262 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>

<section id="lecture-13-assumption-tests" class="title-slide slide level1 center">
<h1>Lecture 13 Assumption Tests</h1>
<p>Creates all 4 diagnostic plots automatically</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-5-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-6-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-7-1.png" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    DHARMa nonparametric dispersion test via sd of residuals fitted vs.
    simulated

data:  simulationOutput
dispersion = 1.0497, p-value = 0.68
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-8-1.png" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    DHARMa outlier test based on exact binomial test with approximate
    expectations

data:  simulation_output
outliers at both margin(s) = 0, observations = 80, p-value = 1
alternative hypothesis: true probability of success is not equal to 0.007968127
95 percent confidence interval:
 0.00000000 0.04506404
sample estimates:
frequency of outliers (expected: 0.00796812749003984 ) 
                                                     0 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-9-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</section>

<section id="cooks-influence-plot-using-car" class="title-slide slide level1 center">
<h1>Cooks influence plot using car</h1>
<p>this will tell you if there are outliers greater than the standard 0.5 cooks distance</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-10-1.png" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       StudRes       Hat        CookD
1  -0.09869848 0.1746972 0.0005155059
2  -0.09869848 0.1746972 0.0005155059
27  2.85206412 0.1746972 0.4304585311
59  2.42281033 0.1746972 0.3106358546</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-11-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Groups   Name        Std.Dev.
 patch    (Intercept) 17.156  
 Residual             17.280  </code></pre>
</div>
</div>
</section>

<section id="lecture-13-post-hoc-comparisons" class="title-slide slide level1 center">
<h1>Lecture 13: Post-hoc Comparisons</h1>
<p>Although the main effect of treatment was not significant in the nested ANOVA (p = r format(p_treat, digits=3)), we can still examine the mean differences between treatments to understand patterns in the data. However, we should interpret these with caution given the lack of statistical significance at the α = 0.05 level.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> treat  emmean   SE df lower.CL upper.CL
 none     39.2 9.41 12    18.70     59.7
 low      21.6 9.41 12     1.05     42.0
 medium   19.0 9.41 12    -1.50     39.5
 high      1.3 9.41 12   -19.20     21.8

Warning: EMMs are biased unless design is perfectly balanced 
Confidence level used: 0.95 </code></pre>
</div>
</div>
</section>

<section id="lecture-13-tukey-pairwise-comparisons" class="title-slide slide level1 center">
<h1>Lecture 13: Tukey Pairwise Comparisons</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> contrast      estimate   SE df t.ratio p.value
 none - low       17.65 13.3 12   1.327  0.7557
 none - medium    20.20 13.3 12   1.518  0.6356
 none - high      37.90 13.3 12   2.849  0.0848
 low - medium      2.55 13.3 12   0.192  1.0000
 low - high       20.25 13.3 12   1.522  0.6331
 medium - high    17.70 13.3 12   1.330  0.7534

P value adjustment: sidak method for 6 tests </code></pre>
</div>
</div>
</section>

<section id="lecture-13-letter-display" class="title-slide slide level1 center">
<h1>Lecture 13: Letter Display</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> treat  emmean   SE df lower.CL upper.CL .group
 high      1.3 9.41 12   -19.20     21.8  a    
 medium   19.0 9.41 12    -1.50     39.5  a    
 low      21.6 9.41 12     1.05     42.0  a    
 none     39.2 9.41 12    18.70     59.7  a    

Warning: EMMs are biased unless design is perfectly balanced 
Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 4 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Interpretation of Treatment Comparisons The mean algae cover for the Control treatment (1.30%) appears considerably lower than for the reduced urchin density treatments (66% Density: 21.55%, 33% Density: 19.00%, Removed: 39.20%). While the visual pattern suggests an inverse relationship between urchin density and algae cover, with complete removal showing the highest algae cover, the nested ANOVA showed that these differences were not statistically significant at the α = 0.05 level (p = xxxx). The high variability among patches within treatments likely contributed to the lack of statistical significance for the treatment effect.</p>
</div>
</div>
</div>
</section>

<section id="lecture-13-visualization" class="title-slide slide level1 center">
<h1>Lecture 13: Visualization</h1>

<img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-16-1.png" width="576" class="r-stretch"></section>

<section id="lecture-13-means-plot" class="title-slide slide level1 center">
<h1>Lecture 13: Means Plot</h1>
<ul>
<li>text</li>
</ul>

<img data-src="nested_anova_activity_files/figure-revealjs/unnamed-chunk-17-1.png" width="576" class="r-stretch"></section>

<section id="lecture-13-discussion" class="title-slide slide level1 center">
<h1>Lecture 13: Discussion</h1>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Scientific Interpretation Our nested ANOVA analysis revealed substantial spatial heterogeneity in algae cover, with significant variation among patches within each treatment (p &lt; 0.001). Surprisingly, the effect of urchin density treatments on filamentous algae cover was not statistically significant at the α = 0.05 level (p = 0.091), despite apparent trends in the data. The descriptive statistics show a pattern where algae cover appears to increase as urchin density decreases, with the Control treatment (mean = 1.3%) showing minimal algae cover compared to reduced density treatments (66% Density: 21.55%, 33% Density: 19.00%, and Removed: 39.20%). This pattern suggests a potential density-dependent relationship between urchin grazing and algal abundance, but the high variability among patches masked the treatment effect. The substantial variance component associated with patches nested within treatments (294.31, approximately 39.5% of total variance) underscores the importance of spatial heterogeneity in structuring algal communities. This finding highlights the necessity of accounting for spatial variability when designing and analyzing ecological field experiments. From an ecological perspective, these results suggest that while sea urchins may influence algal communities through grazing, local environmental factors and patch-specific conditions play a dominant role in determining algae cover. This has important implications for ecosystem management, as it indicates that the effects of urchin density manipulations may be context-dependent and influenced by local environmental conditions.</p>
</div>
</div>
</div>
</section>

<section id="comparison-with-traditional-nested-anova" class="title-slide slide level1 center scrollable">
<h1>Comparison with Traditional Nested ANOVA</h1>
<p>The linear mixed model approach provides similar results to the traditional nested ANOVA approach. The main advantage of the mixed model is the more elegant handling of random effects and the extensive diagnostic tools available through packages like DHARMa.</p>
<p>The mixed model approach confirms that:</p>
<ol type="1">
<li>Treatment effects are not significant (p = 0.091)</li>
</ol>
<p>In both methods, the key ecological finding is the strong spatial heterogeneity in algal cover that overrides the grazing effect of urchins at different densities.</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/ecostats_2026");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>