<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Lecture: Analysis of Variance (ANOVA)</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-916d92ef29fae53263df6d6c2ab37a8f.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture: Analysis of Variance (ANOVA) – UMD Biostatistics">
<meta property="og:description" content="One-way ANOVA as regression with a categorical predictor: partitioning sums of squares, the F-ratio, assumptions and diagnostics, setting the reference level with fct_relevel(), post-hoc testing, reporting, and the non-parametric route when assumptions genuinely fail. Uses the fiddler crab claw-radiator experiment and a nematode lifespan dataset.">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture: Analysis of Variance (ANOVA)</h1>
  <p class="subtitle">Single-factor ANOVA</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry
</div>
</div>
</div>

</section>
<section id="where-we-left-off" class="slide level2">
<h2>Where We Left Off</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Covered last time — Multiple Regression:</p>
<ul>
<li>Partial slopes, and why they are conditional</li>
<li>Collinearity, and saying “these data cannot separate them”</li>
<li>Interactions</li>
<li><strong>Factors, dummy variables, and <code>fct_relevel()</code></strong></li>
<li>Model comparison with adjusted R² and AIC</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea from last lecture</strong></p>
<p>You already built an ANOVA table for a regression, and you already turned a categorical predictor into dummy variables.</p>
<p>Today every predictor is categorical. <strong>The machinery does not change at all</strong> — only the name on the front does.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-1-overview" class="slide level2 divider">
<h2>Part 1 · Overview</h2>
</section>
<section id="todays-objectives" class="slide level2">
<h2>Today’s Objectives</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>One-way ANOVA, end to end:</p>
<ul>
<li>Why ANOVA <em>is</em> regression with a categorical predictor</li>
<li>Partitioning variance, and the F-ratio</li>
<li>Assumptions and diagnostics</li>
<li>Setting the reference level on purpose</li>
<li>Post-hoc tests — which pairs actually differ</li>
<li>Reporting results</li>
<li>What to do when the assumptions genuinely fail</li>
</ul>
<p><a href="data/fiddler_crabs.csv" class="btn btn-primary" download="fiddler_crabs.csv">📥 Crab data</a> <a href="data/nematode_lifespan.csv" class="btn btn-primary" download="nematode_lifespan.csv">📥 Nematode data</a></p>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reading</strong></p>
<p>Whitlock &amp; Schluter, Ch. 15 — Comparing Means of More Than Two Groups.</p>
<p>Gotelli &amp; Ellison, Ch. 10 — The Analysis of Variance.</p>
</div>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Continuous X</th>
<th style="text-align: left;">Categorical X</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Continuous Y</strong></td>
<td style="text-align: left;">Regression</td>
<td style="text-align: left;"><strong>ANOVA</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Categorical Y</strong></td>
<td style="text-align: left;">Logistic</td>
<td style="text-align: left;">Contingency</td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section id="the-study-does-a-big-claw-act-as-a-radiator" class="slide level2">
<h2>The Study · Does a Big Claw Act as a Radiator?</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>A male fiddler crab has one hugely enlarged claw. Darnell &amp; Munguia asked whether it doubles as a <strong>heat radiator</strong>, dumping heat so the crab can stay out foraging in the sun.</p>
<p>Four groups of <strong>21 crabs each</strong>, body temperature above ambient measured in the field:</p>
<ul>
<li><code>intact male</code> — the control</li>
<li><code>male major removed</code> — the big claw taken off</li>
<li><code>male minor removed</code> — a small claw taken off, the <strong>procedural control</strong></li>
<li><code>female</code> — never had a major claw at all</li>
</ul>
<p>If the big claw sheds heat, removing it should make males <strong>hotter</strong>.</p>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a>crab_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/fiddler_crabs.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a aria-label="2"></a>  <span class="fu">mutate</span>(<span class="at">crab_type =</span> <span class="fu">factor</span>(crab_type))</span>
<span id="cb1-3"><a aria-label="3"></a></span>
<span id="cb1-4"><a aria-label="4"></a><span class="fu">count</span>(crab_df, crab_type)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  crab_type              n
  &lt;fct&gt;              &lt;int&gt;
1 female                21
2 intact male           21
3 male major removed    21
4 male minor removed    21</code></pre>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>A balanced design</strong></p>
<p>Equal n in every group — which makes the degrees-of-freedom arithmetic below clean, and the test robust.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="how-today-works" class="slide level2">
<h2>🗳️ How Today Works</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>🗳️ Six times today, you make the call</strong></p>
<p>Six slides are marked <strong>🗳️ DECIDE</strong>. Each asks a multiple-choice question, and I will <em>not</em> tell you the answer on that slide.</p>
<p><strong>How it works:</strong> write your letter down — actually write it — then hold up fingers 1–4. If the room splits, turn to the person next to you, argue for ninety seconds, and we vote again. Nothing here is graded. The point is that you commit before you find out.</p>
</div>
</div>
</div>
</section>
<section id="part-2-anova-is-regression" class="slide level2 divider">
<h2>Part 2 · ANOVA Is Regression</h2>
</section>
<section id="same-machinery-different-predictor" class="slide level2">
<h2>Same Machinery, Different Predictor</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Regression</strong></p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1X_i + \varepsilon_i\]</span></p>
<ul>
<li>X is continuous</li>
<li>H₀: β₁ = 0</li>
<li>One slope</li>
</ul>
<p><strong>ANOVA</strong></p>
<p><span class="math display">\[Y_{ij} = \mu + A_i + \varepsilon_{ij}\]</span></p>
<ul>
<li><span class="math inline">\(A_i\)</span> is the effect of group i</li>
<li>H₀: μ₁ = μ₂ = … = μₖ</li>
<li>One coefficient per group, minus one</li>
</ul>
</div><div class="column" style="width:50%;">
<p>Both:</p>
<ul>
<li>Partition total variation into <strong>explained</strong> and <strong>left over</strong></li>
<li>Divide each sum of squares by its degrees of freedom</li>
<li>Test with an <strong>F-ratio</strong> of the two mean squares</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The same <code>lm()</code> call</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="co"># regression</span></span>
<span id="cb3-2"><a aria-label="2"></a><span class="fu">lm</span>(absorbance <span class="sc">~</span> nitrate, <span class="at">data =</span> df)</span>
<span id="cb3-3"><a aria-label="3"></a></span>
<span id="cb3-4"><a aria-label="4"></a><span class="co"># ANOVA</span></span>
<span id="cb3-5"><a aria-label="5"></a><span class="fu">lm</span>(body_temp_c <span class="sc">~</span> crab_type, <span class="at">data =</span> df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The only difference is that <code>crab_type</code> is a factor, so R builds dummy variables for you — exactly as it did last week.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="decide-why-not-just-run-all-the-t-tests" class="slide level2">
<h2>🗳️ DECIDE · Why Not Just Run All the t-tests?</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>With four crab groups there are <strong>six</strong> possible pairwise t-tests. Suppose every group really has the same mean, and you run all six at α = 0.05.</p>
<p><strong>What is the chance you get at least one “significant” result?</strong></p>
<p><strong>(a)</strong> 5% — that is what α = 0.05 means</p>
<p><strong>(b)</strong> About 12%</p>
<p><strong>(c)</strong> About 26%</p>
<p><strong>(d)</strong> 30% — 6 × 5%</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ Write your letter down, then vote.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The question to ask</strong></p>
<p><em>What is the chance of getting no false positives in six independent tries?</em></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-multiple-comparisons-problem" class="slide level2">
<h2>The Multiple-Comparisons Problem</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (c) — about 26%.</strong></p>
<p><span class="math display">\[1 - (1 - 0.05)^6 = 0.265\]</span></p>
<p>Each test has a 95% chance of behaving. Six in a row behave only 73.5% of the time, so you have roughly a <strong>one in four</strong> chance of at least one false positive — before you have learned anything.</p>
<p><strong>(d)</strong> is the common guess. Adding probabilities overshoots, because the ways of being wrong overlap.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>ANOVA’s job is to ask one question first:</strong> <em>is there any difference at all among these groups?</em></p>
<p>One test, one α, one p-value. Only if it rejects do you go looking for <strong>which</strong> groups differ — and then you use a post-hoc method that controls the error rate across that whole family of comparisons.</p>
<p>With 10 groups there are 45 pairs, and the chance of at least one false positive is over <strong>90%</strong>.</p>
</div></div>
</section>
<section id="part-3-the-logic" class="slide level2 divider">
<h2>Part 3 · The Logic</h2>
</section>
<section id="anovas-question" class="slide level2">
<h2>ANOVA’s Question</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Even if every group had the same true mean, the sample means would differ, just from sampling error.</p>
<p>ANOVA asks whether the sample means differ <strong>more than sampling error alone would produce</strong>:</p>
<ul>
<li><strong><span class="math inline">\(MS_{among}\)</span></strong> — how spread out the group means are</li>
<li><strong><span class="math inline">\(MS_{within}\)</span></strong> — how spread out individuals are inside their own group</li>
</ul>
<p><span class="math display">\[F = \frac{MS_{among}}{MS_{within}}\]</span></p>
<ul>
<li><strong>H₀:</strong> μ₁ = μ₂ = μ₃ = μ₄</li>
<li><strong>H₁:</strong> at least one mean differs</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="analysis_of_variance_lecture_files/figure-revealjs/analysis-of-variance-03-1.png" alt="Jittered scatterplot of fiddler crab body temperature by crab type, with a large diamond marking each group mean and error bars showing the confidence interval of the mean." width="307"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="where-the-variation-goes" class="slide level2">
<h2>Where the Variation Goes</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p>Every point’s distance from the <strong>grand mean</strong> splits into two pieces, exactly as in regression:</p>
<p><span class="math display">\[\underbrace{(Y_{ij} - \bar{Y})}_{\text{total}} = \underbrace{(\bar{Y}_i - \bar{Y})}_{\text{among}} + \underbrace{(Y_{ij} - \bar{Y}_i)}_{\text{within}}\]</span></p>
<p>Square and sum over every observation:</p>
<p><span class="math display">\[SS_{total} = SS_{among} + SS_{within}\]</span></p>
<p>The dashed line is the grand mean; the coloured bars are the group means.</p>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="analysis_of_variance_lecture_files/figure-revealjs/analysis-of-variance-04-1.png" alt="Three stacked panels showing the ANOVA partition on the crab data: total variation as each point's deviation from the grand mean, among-group variation as each group mean's deviation from the grand mean, and within-group variation as each point's deviation from its own group mean." width="364"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-4-partitioning-the-sum-of-squares" class="slide level2 divider">
<h2>Part 4 · Partitioning the Sum of Squares</h2>
</section>
<section id="the-sums-of-squares" class="slide level2">
<h2>The Sums of Squares</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><span class="math display">\[SS_{total} = \sum_{i}\sum_{j}(Y_{ij} - \bar{Y})^2\]</span></p>
<p><span class="math display">\[SS_{among} = \sum_{i} n_i(\bar{Y}_i - \bar{Y})^2\]</span></p>
<p><span class="math display">\[SS_{within} = \sum_{i}\sum_{j}(Y_{ij} - \bar{Y}_i)^2\]</span></p>
<p>with <strong>a</strong> groups and <span class="math inline">\(n_i\)</span> observations in group i:</p>
<ul>
<li><span class="math inline">\(df_{among} = a - 1\)</span> = 3</li>
<li><span class="math inline">\(df_{within} = N - a\)</span> = 80</li>
<li><span class="math inline">\(df_{total} = N - 1\)</span> = 83</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Note the <span class="math inline">\(n_i\)</span></strong></p>
<p>Each group mean’s deviation is weighted by that group’s <strong>own</strong> sample size. With a balanced design every <span class="math inline">\(n_i\)</span> is the same and it simplifies to <span class="math inline">\(n\sum(\bar{Y}_i - \bar{Y})^2\)</span> — but only then.</p>
<p>Our design is balanced at n = 21, so both forms agree here.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="computing-them-by-hand" class="slide level2">
<h2>Computing Them by Hand</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-label="1"></a>grand_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(crab_df<span class="sc">$</span>body_temp_c)</span>
<span id="cb4-2"><a aria-label="2"></a></span>
<span id="cb4-3"><a aria-label="3"></a>crab_parts <span class="ot">&lt;-</span> crab_df <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a aria-label="4"></a>  <span class="fu">group_by</span>(crab_type) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a aria-label="5"></a>  <span class="fu">mutate</span>(<span class="at">group_mean =</span> <span class="fu">mean</span>(body_temp_c)) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a aria-label="6"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb4-7"><a aria-label="7"></a></span>
<span id="cb4-8"><a aria-label="8"></a>ss_total  <span class="ot">&lt;-</span> <span class="fu">sum</span>((crab_parts<span class="sc">$</span>body_temp_c <span class="sc">-</span> grand_mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb4-9"><a aria-label="9"></a>ss_among  <span class="ot">&lt;-</span> <span class="fu">sum</span>((crab_parts<span class="sc">$</span>group_mean  <span class="sc">-</span> grand_mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb4-10"><a aria-label="10"></a>ss_within <span class="ot">&lt;-</span> <span class="fu">sum</span>((crab_parts<span class="sc">$</span>body_temp_c <span class="sc">-</span> crab_parts<span class="sc">$</span>group_mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb4-11"><a aria-label="11"></a></span>
<span id="cb4-12"><a aria-label="12"></a><span class="fu">c</span>(<span class="at">total =</span> ss_total, <span class="at">among =</span> ss_among, <span class="at">within =</span> ss_within)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   total    among   within 
6.108929 2.641310 3.467619 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-label="1"></a>ss_among <span class="sc">+</span> ss_within</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.108929</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>2.641 + 3.468 = 6.109</strong> — exactly, as it must.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The same identity as regression</strong></p>
<ul>
<li><span class="math inline">\(SS_{among}\)</span> here is <span class="math inline">\(SS_{regression}\)</span> there</li>
<li><span class="math inline">\(SS_{within}\)</span> here is <span class="math inline">\(SS_{residual}\)</span> there</li>
</ul>
<p>Different names, same partition, same arithmetic.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-anova-table-from-r" class="slide level2">
<h2>The ANOVA Table from R</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-label="1"></a>crab_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_temp_c <span class="sc">~</span> crab_type, <span class="at">data =</span> crab_df)</span>
<span id="cb8-2"><a aria-label="2"></a></span>
<span id="cb8-3"><a aria-label="3"></a><span class="fu">anova</span>(crab_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: body_temp_c
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
crab_type  3 2.6413 0.88044  20.312 6.997e-10 ***
Residuals 80 3.4676 0.04335                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Every number is one you just built:</p>
<ul>
<li><strong>Sum Sq</strong> — 2.64 and 3.47</li>
<li><strong>Df</strong> — a − 1 = 3, N − a = 80</li>
<li><strong>Mean Sq</strong> — Sum Sq ÷ Df</li>
<li><strong>F value</strong> — the ratio of those two mean squares</li>
</ul>
<p><strong>F = 20.31, p = 7.00e-10.</strong></p>
</div></div>
</section>
<section id="decide-what-does-that-f-tell-you" class="slide level2">
<h2>🗳️ DECIDE · What Does That F Tell You?</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>The ANOVA returns <strong>F = 20.31, p = 7.00e-10</strong>.</p>
<p><strong>What have you just learned?</strong></p>
<p><strong>(a)</strong> All four crab types have different mean temperatures</p>
<p><strong>(b)</strong> At least one crab type differs from at least one other</p>
<p><strong>(c)</strong> Removing the major claw raises body temperature</p>
<p><strong>(d)</strong> The major claw explains 43.2% of the variation in temperature, so the radiator hypothesis is supported</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ One letter. Write it down.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The question to ask</strong></p>
<p><em>What was the null hypothesis, exactly?</em></p>
<p>A test can only tell you about the hypothesis it tested.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="what-f-does-and-does-not-say" class="slide level2">
<h2>What F Does and Does Not Say</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (b).</strong></p>
<p>H₀ was “all four means are equal.” Rejecting it says <strong>at least one</strong> differs — not which, not how many, and not in which direction.</p>
<p><strong>(a)</strong> claims far more than the test supports. <strong>(c)</strong> is a directional claim about one specific pair; that needs a post-hoc comparison, and Part 8 shows it is not even true. <strong>(d)</strong> misreads R²: 0.432 is the variance explained by <strong>crab type</strong>, which bundles sex and two surgeries together, not by the claw alone.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ The most common ANOVA mistake</strong></p>
<p>Reporting a significant F and then describing whichever group means look farthest apart, as though the F test had said so.</p>
<p><strong>It did not.</strong> The F test is an entry ticket, not an answer.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-5-the-f-ratio" class="slide level2 divider">
<h2>Part 5 · The F-Ratio</h2>
</section>
<section id="what-f-actually-is" class="slide level2">
<h2>What F Actually Is</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><span class="math display">\[F = \frac{MS_{among}}{MS_{within}}\]</span></p>
<ul>
<li><span class="math inline">\(MS_{within}\)</span> estimates the background variance σ² — pooled from inside the groups, where the treatment cannot reach</li>
<li><span class="math inline">\(MS_{among}\)</span> estimates that <strong>same</strong> σ², <em>plus</em> anything real that separates the group means</li>
<li><strong>If H₀ is true, both estimate σ² and F ≈ 1</strong></li>
</ul>
<p>Here F = <strong>20.31</strong> — the group means are 20 times further apart than within-group noise alone can explain.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Why F is never negative</strong></p>
<p>It is a ratio of two variances, and a variance is a sum of <strong>squares</strong>. The direction of a difference disappears the moment you square it — which is why a significant F cannot tell you which way anything went.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="f-and-t-are-the-same-test" class="slide level2">
<h2>F and t Are the Same Test</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Take just two of the four groups — intact males and females — and test them both ways:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-label="1"></a>crab_two <span class="ot">&lt;-</span> crab_df <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a aria-label="2"></a>  <span class="fu">filter</span>(crab_type <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"intact male"</span>, <span class="st">"female"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a aria-label="3"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb10-4"><a aria-label="4"></a></span>
<span id="cb10-5"><a aria-label="5"></a><span class="fu">t.test</span>(body_temp_c <span class="sc">~</span> crab_type,</span>
<span id="cb10-6"><a aria-label="6"></a>       <span class="at">data =</span> crab_two, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>statistic</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       t 
5.958321 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-label="1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(body_temp_c <span class="sc">~</span> crab_type,</span>
<span id="cb12-2"><a aria-label="2"></a>         <span class="at">data =</span> crab_two))[<span class="dv">1</span>, <span class="st">"F value"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35.50158</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>t = 5.958</strong>, so <strong>t² = 35.5</strong> — and <strong>F = 35.5</strong>.</p>
<p>Identical, with identical p-values.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ ANOVA generalises the t-test</strong></p>
<p>With two groups they are the same test. With three or more, the t-test has nowhere to go and ANOVA does.</p>
<p>This is the same <strong>t² = F</strong> identity you proved on a regression slope in Week 6.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="variance-explained" class="slide level2">
<h2>Variance Explained</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><span class="math display">\[R^2 = \frac{SS_{among}}{SS_{total}} = \frac{2.64}{6.11} = 0.432\]</span></p>
<p>Crab type accounts for about <strong>43.2%</strong> of the variation in body temperature. The rest is individual crabs being individual crabs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-label="1"></a><span class="fu">summary</span>(crab_model)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4323687</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Significant and partial, at the same time</strong></p>
<p>p = 7.00e-10 says the group differences are not noise. R² = 0.43 says they explain under half of what is going on.</p>
<p>Both are true, and a results section should carry both.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-6-assumptions-and-diagnostics" class="slide level2 divider">
<h2>Part 6 · Assumptions and Diagnostics</h2>
</section>
<section id="the-three-assumptions" class="slide level2 scrollable">
<h2>The Three Assumptions</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>One-way ANOVA assumes:</p>
<ol type="1">
<li><strong>Independence</strong> — observations do not depend on each other. This one comes from the <strong>design</strong>, and no plot can rescue it</li>
<li><strong>Normality</strong> — of the <strong>residuals</strong>, not of the raw response</li>
<li><strong>Equal variance</strong> (homoscedasticity) across groups</li>
</ol>
<p>ANOVA is fairly robust to mild departures from 2 and 3 <strong>when the design is balanced</strong>, which is one more reason to plan for equal n.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Normality of what?</strong></p>
<p>Not <code>body_temp_c</code>. Not each group separately. <strong>The residuals of the fitted model</strong> — exactly as in regression.</p>
<p>A response that looks bimodal because the groups differ is perfectly fine; that is the effect you are testing.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-four-diagnostic-plots" class="slide level2 scrollable">
<h2>The Four Diagnostic Plots</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p>The same four panels you read for a regression:</p>
<ol type="1">
<li><strong>Residuals vs fitted</strong> — with a factor, the points stack in vertical columns, one per group. You are looking for <strong>equal spread</strong> in each column</li>
<li><strong>QQ plot</strong> — residuals against normal</li>
<li><strong>Scale-location</strong> — same check, easier to see</li>
<li><strong>Residuals vs leverage</strong> — influential points</li>
</ol>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="analysis_of_variance_lecture_files/figure-revealjs/analysis-of-variance-09-1.png" alt="Four standard diagnostic plots for the crab ANOVA model: residuals versus fitted values, normal QQ plot, scale-location, and residuals versus leverage." width="345"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="levenes-test-equal-variances" class="slide level2">
<h2>Levene’s Test — Equal Variances</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-label="1"></a><span class="fu">leveneTest</span>(body_temp_c <span class="sc">~</span> crab_type, <span class="at">data =</span> crab_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  3  0.1587 0.9238
      80               </code></pre>
</div>
</div>
<p>H₀ is <strong>“the variances are equal”</strong>, so a <strong>large</strong> p-value is the good outcome — the same backwards logic as Shapiro-Wilk.</p>
</div><div class="column" style="width:45%;">
<p>p = 0.924 — nothing to worry about.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Levene vs Bartlett</strong></p>
<p>Bartlett’s test is more powerful but assumes normality itself. Levene’s works on absolute deviations from the group median, so it is far more robust. Use Levene.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="shapiro-wilk-normality-of-the-residuals" class="slide level2">
<h2>Shapiro-Wilk — Normality of the Residuals</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-label="1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(crab_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(crab_model)
W = 0.97566, p-value = 0.112</code></pre>
</div>
</div>
<p>Note what goes inside: <strong><code>residuals(crab_model)</code></strong>.</p>
</div><div class="column" style="width:45%;">
<p>p = 0.112 — the residuals are consistent with normal.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Do not let the test overrule the plot</strong></p>
<p>At small n it cannot detect real problems; at large n it flags departures too small to matter. The QQ plot is the primary evidence.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="one-call-for-all-of-it" class="slide level2">
<h2>One Call for All of It</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p><code>performance::check_model()</code> draws every assumption check in one labelled panel, with a plain-English caption on each.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-label="1"></a><span class="fu">check_model</span>(crab_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Useful for a quick look. Still worth knowing what each panel is, which is why we did them one at a time first.</p>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="analysis_of_variance_lecture_files/figure-revealjs/analysis-of-variance-12-1.png" alt="The performance package's check_model output for the crab ANOVA, showing posterior predictive check, linearity, homogeneity of variance, influential observations and normality of residuals in one labelled panel." width="384"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-7-the-reference-level-again" class="slide level2 divider">
<h2>Part 7 · The Reference Level, Again</h2>
</section>
<section id="r-sorts-alphabetically-still" class="slide level2">
<h2>R Sorts Alphabetically — Still</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Read the file without thinking about it and the four crab types become a factor in <strong>alphabetical</strong> order:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-label="1"></a><span class="fu">levels</span>(crab_df<span class="sc">$</span>crab_type)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "female"             "intact male"        "male major removed"
[4] "male minor removed"</code></pre>
</div>
</div>
<p>So the reference is <strong>female</strong> — and every coefficient in the model becomes “compared with a female crab.”</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ That is the wrong baseline for this experiment</strong></p>
<p>The question is what happens when you <strong>remove a claw from a male</strong>. The comparison that answers it is against an <strong>intact male</strong>, not against a female.</p>
<p>The model fits identically either way. The output only answers your question if you tell it what your question was.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="decide-which-crab-is-the-control" class="slide level2">
<h2>🗳️ DECIDE · Which Crab Is the Control?</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>You are about to set the reference level deliberately.</p>
<p><strong>Which level should it be, and why?</strong></p>
<p><strong>(a)</strong> <code>female</code> — keep R’s default; the model fit is identical anyway</p>
<p><strong>(b)</strong> <code>intact male</code> — the untouched version of the animals that were manipulated</p>
<p><strong>(c)</strong> <code>male minor removed</code> — it is the procedural control, so it accounts for the surgery</p>
<p><strong>(d)</strong> It makes no difference, because the F-test and R² do not change</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ Careful — two of these are true statements. Only one is the right decision.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The question to ask</strong></p>
<p><em>Which single comparison do I most want to read straight off the coefficient table?</em></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="fct_relevel-saying-what-you-meant" class="slide level2 scrollable">
<h2><code>fct_relevel()</code> · Saying What You Meant</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (b).</strong></p>
<ol start="4" type="a">
<li><p>is <em>true</em> — F, R², and the ANOVA table are identical whichever level is the reference. That is not a reason to accept a default chosen by spelling.</p></li>
<li><p>is tempting and it is the right <strong>comparison</strong> to make eventually — but as the baseline it hides the very contrast the experiment was built around.</p></li>
</ol>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-label="1"></a>crab_df <span class="ot">&lt;-</span> crab_df <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a aria-label="2"></a>  <span class="fu">mutate</span>(<span class="at">crab_type =</span> <span class="fu">fct_relevel</span>(crab_type, <span class="st">"intact male"</span>))</span>
<span id="cb23-3"><a aria-label="3"></a></span>
<span id="cb23-4"><a aria-label="4"></a>crab_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_temp_c <span class="sc">~</span> crab_type, <span class="at">data =</span> crab_df)</span>
<span id="cb23-5"><a aria-label="5"></a></span>
<span id="cb23-6"><a aria-label="6"></a><span class="fu">summary</span>(crab_model)<span class="sc">$</span>coefficients <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                    1.286      0.045  28.300    0.000
crab_typefemale                0.390      0.064   6.077    0.000
crab_typemale major removed    0.129      0.064   2.001    0.049
crab_typemale minor removed   -0.076      0.064  -1.186    0.239</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Now every row reads as “<strong>degrees hotter than an intact male</strong>”:</p>
<ul>
<li><code>female</code> <strong>+0.39</strong> — clearly hotter</li>
<li><code>male major removed</code> <strong>+0.13</strong></li>
<li><code>male minor removed</code> <strong>-0.08</strong></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 The habit</strong></p>
<p>Set the reference in the same line that creates the factor. <code>fct_relevel(x, "control")</code> moves one level to the front and leaves the rest alone.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-8-post-hoc-testing" class="slide level2 divider">
<h2>Part 8 · Post-Hoc Testing</h2>
</section>
<section id="what-post-hoc-tests-are-for" class="slide level2">
<h2>What Post-Hoc Tests Are For</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>The F-test said <em>something</em> differs. Post-hoc tests say <strong>what</strong>, while keeping the family-wide error rate at α.</p>
<ul>
<li><strong>Planned (a priori) comparisons</strong> — a small number of contrasts you committed to <strong>before</strong> seeing the data. More powerful, because there are fewer of them</li>
<li><strong>Unplanned (post-hoc) comparisons</strong> — all pairs, after the fact. Safer, less powerful</li>
</ul>
<p><strong>Tukey’s HSD</strong> is the standard for all pairwise comparisons with equal n.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Deciding after you look is not a plan</strong></p>
<p>Choosing which comparisons to make <em>because they looked big</em> re-introduces exactly the multiple-comparisons problem the correction exists to solve.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="tukeys-hsd" class="slide level2">
<h2>Tukey’s HSD</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-label="1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(crab_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = crab_model)

$crab_type
                                             diff         lwr         upr
female-intact male                     0.39047619  0.22189182  0.55906056
male major removed-intact male         0.12857143 -0.04001294  0.29715579
male minor removed-intact male        -0.07619048 -0.24477484  0.09239389
male major removed-female             -0.26190476 -0.43048913 -0.09332040
male minor removed-female             -0.46666667 -0.63525103 -0.29808230
male minor removed-male major removed -0.20476190 -0.37334627 -0.03617754
                                          p adj
female-intact male                    0.0000002
male major removed-intact male        0.1962212
male minor removed-intact male        0.6375171
male major removed-female             0.0006106
male minor removed-female             0.0000000
male minor removed-male major removed 0.0108312</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Each row is one pair: the difference in means, a confidence interval, and a p-value <strong>already adjusted</strong> for the whole family of six comparisons.</p>
<p>A pair differs when its interval excludes zero.</p>
</div></div>
</section>
<section id="decide-reading-the-tukey-output" class="slide level2">
<h2>🗳️ DECIDE · Reading the Tukey Output</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>The radiator hypothesis predicts that a male whose <strong>major claw was removed</strong> should run <strong>hotter</strong> than an intact male.</p>
<p>Tukey gives <code>male major removed − intact male</code> a difference of <strong>+0.129</strong> with an adjusted <strong>p = 0.196</strong>.</p>
<p><strong>What should you conclude?</strong></p>
<p><strong>(a)</strong> The hypothesis is supported — the difference is in the predicted direction</p>
<p><strong>(b)</strong> The hypothesis fails — removing the major claw did not significantly change temperature</p>
<p><strong>(c)</strong> The hypothesis is supported, because females are significantly hotter than every male group</p>
<p><strong>(d)</strong> Nothing can be concluded, because the overall ANOVA was significant</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ One letter, then argue it with your neighbour.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The question to ask</strong></p>
<p><em>Which comparison does the hypothesis actually make a prediction about?</em></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="what-tukey-actually-found" class="slide level2">
<h2>What Tukey Actually Found</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (b).</strong></p>
<p>Removing the major claw moved temperature by 0.13 °C, adjusted p = 0.2 — not distinguishable from zero. The direction is right and the evidence is not there.</p>
<p><strong>(c)</strong> is the trap: females <em>are</em> hotter than every male group, but females differ from males in many ways besides the claw. That comparison cannot test a claw-removal hypothesis.</p>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<p><strong>What did differ</strong> (adjusted p):</p>
<div class="compact-table">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">female − intact male</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">major removed − intact</td>
<td style="text-align: right;">0.196</td>
</tr>
<tr class="odd">
<td style="text-align: left;">minor removed − intact</td>
<td style="text-align: right;">0.638</td>
</tr>
<tr class="even">
<td style="text-align: left;">major − minor removed</td>
<td style="text-align: right;">0.011</td>
</tr>
</tbody>
</table>
</div>
<p>The big effect in this dataset is <strong>sex</strong>, not surgery.</p>
</div></div>
</section>
<section id="estimated-marginal-means" class="slide level2">
<h2>Estimated Marginal Means</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><code>emmeans</code> gives the same comparisons with more control — any contrast you like, any adjustment method:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-label="1"></a><span class="fu">emmeans</span>(crab_model, pairwise <span class="sc">~</span> crab_type,</span>
<span id="cb27-2"><a aria-label="2"></a>        <span class="at">adjust =</span> <span class="st">"tukey"</span>)<span class="sc">$</span>contrasts</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                estimate     SE df t.ratio p.value
 intact male - female                     -0.3905 0.0643 80  -6.077 &lt;0.0001
 intact male - male major removed         -0.1286 0.0643 80  -2.001  0.1962
 intact male - male minor removed          0.0762 0.0643 80   1.186  0.6375
 female - male major removed               0.2619 0.0643 80   4.076  0.0006
 female - male minor removed               0.4667 0.0643 80   7.263 &lt;0.0001
 male major removed - male minor removed   0.2048 0.0643 80   3.187  0.0108

P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Why <code>emmeans</code> and not just <code>TukeyHSD()</code></strong></p>
<p><code>TukeyHSD()</code> only does all-pairs on a balanced <code>aov</code>. <code>emmeans</code> handles unbalanced designs, covariates, several factors and <strong>planned contrasts</strong> — and it is what you will use from Week 9 onward.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-9-reporting" class="slide level2 divider">
<h2>Part 9 · Reporting</h2>
</section>
<section id="reporting-an-anova" class="slide level2">
<h2>Reporting an ANOVA</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>A results sentence needs the <strong>test, the statistic with both df, the p-value, and the direction</strong> — then the post-hoc detail.</p>
<blockquote>
<p>Body temperature differed among crab types (one-way ANOVA, F<sub>3,80</sub> = 20.31, p &lt; 0.001, R² = 0.43). Females were warmer than intact males by 0.39 °C (Tukey HSD, adjusted p &lt; 0.001), but removing the major claw did not detectably change male temperature (0.13 °C, adjusted p = 0.2).</p>
</blockquote>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ What that sentence does</strong></p>
<ul>
<li>Names the test</li>
<li>Gives <strong>both</strong> degrees of freedom</li>
<li>Reports effect size, not just p</li>
<li>States the post-hoc method <strong>and</strong> that its p-values are adjusted</li>
<li>Reports the non-significant comparison the hypothesis was about, rather than quietly dropping it</li>
</ul>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-10-when-the-assumptions-fail" class="slide level2 divider">
<h2>Part 10 · When the Assumptions Fail</h2>
</section>
<section id="a-second-dataset-nematode-lifespan" class="slide level2">
<h2>A Second Dataset · Nematode Lifespan</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>The crab data behaved. Most data do not.</p>
<p>Here are <strong>200 nematodes</strong>, 50 in each of four treatments, exposed to a parasite as larvae, as adults, as both, or to <strong>water</strong> as a control. The response is lifespan in days.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-label="1"></a>worm_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/nematode_lifespan.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a aria-label="2"></a>  <span class="fu">mutate</span>(<span class="at">treatment =</span> <span class="fu">fct_relevel</span>(treatment, <span class="st">"water"</span>))</span>
<span id="cb29-3"><a aria-label="3"></a></span>
<span id="cb29-4"><a aria-label="4"></a><span class="fu">count</span>(worm_df, treatment)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  treatment       n
  &lt;fct&gt;       &lt;int&gt;
1 water          50
2 adult          50
3 larva          50
4 larva+adult    50</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="analysis_of_variance_lecture_files/figure-revealjs/analysis-of-variance-18-1.png" alt="Boxplots with jittered points of nematode lifespan by treatment, showing unequal spread between groups and a long tail in the larva-plus-adult group." width="307"></p>
</figure>
</div>
</div>
</div>
<p>Note that the <strong><code>water</code> control sorts last alphabetically</strong> — another reason to relevel on purpose.</p>
</div></div>
</section>
<section id="these-assumptions-genuinely-fail" class="slide level2">
<h2>These Assumptions Genuinely Fail</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-label="1"></a>worm_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(lifespan_days <span class="sc">~</span> treatment, <span class="at">data =</span> worm_df)</span>
<span id="cb31-2"><a aria-label="2"></a></span>
<span id="cb31-3"><a aria-label="3"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(worm_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(worm_model)
W = 0.97626, p-value = 0.001808</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-label="1"></a><span class="fu">leveneTest</span>(lifespan_days <span class="sc">~</span> treatment, <span class="at">data =</span> worm_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value    Pr(&gt;F)    
group   3  22.481 1.493e-12 ***
      196                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<ul>
<li>Shapiro-Wilk <strong>p = 0.00181</strong> — residuals are not normal</li>
<li>Levene <strong>p = 1.49e-12</strong> — variances are nowhere near equal</li>
</ul>
<p>Look back at the boxplots: group SDs run from 3.3 to 8.7 days.</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Nothing here is simulated</strong></p>
<p>This is the published dataset, unmodified. Real data fails these tests routinely.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="decide-what-do-you-do-now" class="slide level2">
<h2>🗳️ DECIDE · What Do You Do Now?</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>An ANOVA on these data returns <strong>F = 15.25, p = 5.87e-09</strong> — but the residuals are non-normal and the variances are unequal.</p>
<p><strong>What is the right next step?</strong></p>
<p><strong>(a)</strong> Report the ANOVA — it is significant, and ANOVA is robust</p>
<p><strong>(b)</strong> Drop the group with the biggest variance and re-run</p>
<p><strong>(c)</strong> Try a transformation, and if that fails use a rank-based test such as Kruskal-Wallis</p>
<p><strong>(d)</strong> Report nothing — the data cannot be analysed</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>✍️ Write your letter down, then vote.</strong></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>The question to ask</strong></p>
<p><em>Is the problem with the data, or with the test I chose for it?</em></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="the-kruskal-wallis-test" class="slide level2">
<h2>The Kruskal-Wallis Test</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The answer is (c).</strong></p>
<p>Transform first — a log or square root often fixes both problems at once, and keeps you in a framework that extends to more factors. If it does not, move to a rank-based test.</p>
<p><strong>(b)</strong> is data deletion to make a test pass, which is not a repair.</p>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-label="1"></a><span class="fu">kruskal.test</span>(lifespan_days <span class="sc">~</span> treatment, <span class="at">data =</span> worm_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  lifespan_days by treatment
Kruskal-Wallis chi-squared = 29.463, df = 3, p-value = 1.79e-06</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>Kruskal-Wallis replaces every value by its <strong>rank</strong> and asks whether the rank totals differ more than chance — so it needs no normality and is not thrown by unequal spread.</p>
<p><strong>χ² = 29.46, df = 3, p = 1.79e-06.</strong></p>
<p>The conclusion survives. What changes is that you can now defend it.</p>
</div></div>
</section>
<section id="dunns-test-the-post-hoc-for-ranks" class="slide level2">
<h2>Dunn’s Test — the Post-Hoc for Ranks</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Kruskal-Wallis has the same limit as F: it says <em>something</em> differs, not what. <strong>Dunn’s test</strong> is its post-hoc.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a aria-label="1"></a><span class="fu">dunnTest</span>(lifespan_days <span class="sc">~</span> treatment,</span>
<span id="cb37-2"><a aria-label="2"></a>         <span class="at">data =</span> worm_df, <span class="at">method =</span> <span class="st">"bh"</span>)<span class="sc">$</span>res <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a aria-label="3"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">signif</span>(.x, <span class="dv">3</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Comparison      Z  P.unadj    P.adj
1       water - adult -3.120 1.78e-03 2.67e-03
2       water - larva  0.917 3.59e-01 4.31e-01
3       adult - larva  4.040 5.32e-05 1.60e-04
4 water - larva+adult -3.510 4.56e-04 9.11e-04
5 adult - larva+adult -0.381 7.03e-01 7.03e-01
6 larva - larva+adult -4.420 9.76e-06 5.85e-05</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Which adjustment?</strong></p>
<p><code>"bonferroni"</code> is the strictest and costs the most power. <code>"bh"</code> (Benjamini-Hochberg) controls the <strong>false discovery rate</strong> instead, and is the usual choice when you have more than a handful of comparisons.</p>
</div>
</div>
</div>
<p><code>pairwise.wilcox.test()</code> does a similar job; Dunn’s is preferred because it uses the same ranking as the Kruskal-Wallis it follows.</p>
</div></div>
</section>
<section id="which-test-should-you-use" class="slide level2">
<h2>Which Test Should You Use?</h2>
<div class="compact-table">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Situation</th>
<th style="text-align: left;">Parametric route</th>
<th style="text-align: left;">Non-parametric route</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Compare 2 groups</td>
<td style="text-align: left;">t-test</td>
<td style="text-align: left;">Mann-Whitney U / Wilcoxon rank-sum</td>
</tr>
<tr class="even">
<td style="text-align: left;">Compare 3+ groups</td>
<td style="text-align: left;"><strong>one-way ANOVA</strong></td>
<td style="text-align: left;"><strong>Kruskal-Wallis</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Post-hoc, all pairs</td>
<td style="text-align: left;">Tukey HSD, <code>emmeans</code></td>
<td style="text-align: left;">Dunn’s test, pairwise Wilcoxon</td>
</tr>
<tr class="even">
<td style="text-align: left;">What it compares</td>
<td style="text-align: left;">means</td>
<td style="text-align: left;">mean ranks (≈ medians)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Needs</td>
<td style="text-align: left;">normal residuals, equal variance</td>
<td style="text-align: left;">neither</td>
</tr>
<tr class="even">
<td style="text-align: left;">Costs you</td>
<td style="text-align: left;">nothing, when assumptions hold</td>
<td style="text-align: left;">power, and the original units</td>
</tr>
</tbody>
</table>
</div>
<p><strong>Try a transformation before you give up the parametric route</strong> — it keeps your effect sizes interpretable and extends to the multi-factor designs coming in Week 9.</p>
</section>
<section id="reporting-a-non-parametric-result" class="slide level2">
<h2>Reporting a Non-Parametric Result</h2>
<div class="columns">
<div class="column" style="width:55%;">
<blockquote>
<p>Nematode lifespan differed among parasite-exposure treatments (Kruskal-Wallis χ²<sub>3</sub> = 29.46, p &lt; 0.001). A Kruskal-Wallis test was used because the residuals of the equivalent ANOVA were non-normal (Shapiro-Wilk p = 0.00181) and variances were unequal (Levene p = 1.49e-12). Dunn’s tests with Benjamini-Hochberg adjustment showed that larva-exposed worms outlived worms exposed as adults or as both.</p>
</blockquote>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Say <em>why</em> you went non-parametric</strong></p>
<p>A reader cannot tell whether you chose a rank test because your data required it or because it gave you the answer you wanted — unless you show the assumption checks that made the decision.</p>
<p>Report the numbers that drove the choice, not just the choice.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="wrap-up" class="slide level2">
<h2>Wrap-up</h2>
<p>Today you:</p>
<ul>
<li>Saw that ANOVA <strong>is</strong> regression with a categorical predictor — the same <code>lm()</code>, the same partition, the same F</li>
<li>Worked out why six t-tests carry a <strong>26%</strong> chance of a false positive, and what ANOVA does about it</li>
<li>Built <span class="math inline">\(SS_{among}\)</span> and <span class="math inline">\(SS_{within}\)</span> by hand and matched them to <code>anova()</code></li>
<li>Confirmed <strong>t² = F</strong> on a two-group subset, for the second time this term</li>
<li>Checked independence, normality and equal variance — the last two <strong>on the residuals</strong></li>
<li>Set the reference level with <strong><code>fct_relevel()</code></strong> so the coefficients answered the experiment’s question</li>
<li>Used <strong>Tukey HSD</strong> to find which pairs differ, and learned that the claw-removal comparison was not one of them</li>
<li>Moved to <strong>Kruskal-Wallis and Dunn’s test</strong> on a dataset whose assumptions genuinely failed</li>
</ul>
</section>
<section id="the-three-things-to-carry-out-of-here" class="slide level2">
<h2>The Three Things to Carry Out of Here</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ A significant F is an entry ticket</strong></p>
<p>It says at least one group differs. It never says which, how many, or in which direction. Everything past that comes from post-hoc comparisons you planned or corrected for.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Assumptions live in the residuals</strong></p>
<p>Except independence, which lives in the <strong>design</strong> — and no plot will ever show it to you.</p>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Set the reference level</strong></p>
<p><code>fct_relevel(x, "control")</code>, in the line that makes the factor. The fit never changes; the readability always does.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Up next — Two-Way ANOVA</strong></p>
<p>Two factors at once, and the thing that only exists when you have two: the <strong>interaction</strong>.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="readings" class="slide level2">
<h2>Readings</h2>
<ul>
<li><strong>Whitlock &amp; Schluter</strong>, Ch. 15 — Comparing Means of More Than Two Groups (§15.4 assumptions and transformations; §15.5 planned and unplanned comparisons; §15.6 the Kruskal-Wallis test).</li>
<li><strong>Gotelli &amp; Ellison</strong>, Ch. 10 — The Analysis of Variance.</li>
<li>Darnell, M. Z., &amp; Munguia, P. (2011). Thermoregulation as an alternate function of the sexually dimorphic fiddler crab claw. <em>The American Naturalist</em>, 178(3), 419–428.</li>
</ul>
</section>
<section id="getting-unstuck" class="slide level2 scrollable">
<h2>Getting unstuck</h2>
<p>When code breaks — and it will, that is normal:</p>
<ol type="1">
<li>Read the <strong>error message</strong> out loud; it usually names the line</li>
<li>Check the usual suspects: is your grouping column a <strong>factor</strong>? Did you pass <code>residuals(model)</code> to <code>shapiro.test()</code> rather than the raw response? Is <code>car</code> loaded for <code>leveneTest()</code>, <code>FSA</code> for <code>dunnTest()</code>?</li>
<li><code>?function_name</code> opens the help page</li>
<li>Bring the <strong>exact error</strong> (copy-paste it) to class or office hours</li>
</ol>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea</strong></p>
<p>Every working scientist googles error messages daily. Getting stuck is not failing — it is the job.</p>
</div>
</div>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/ecostats_2026");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>