<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bill Perry">
<meta name="description" content="One-way ANOVA and its connection to regression: partitioning sums of squares, the F-ratio, assumptions and diagnostics, post-hoc testing, reporting, and non-parametric alternatives (Kruskal-Wallis, Dunn’s test) — on a circadian-rhythm light-treatment dataset.">

<title>Lecture: Analysis of Variance (ANOVA) – UMD Biostatistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ffe4ec66b3b2e5a5f7bab576e98f0639.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-9cb2c6106ae76130f99fe6462eb270ca.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-ffe4ec66b3b2e5a5f7bab576e98f0639.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../css/main.css">
<meta property="og:title" content="Lecture: Analysis of Variance (ANOVA) – UMD Biostatistics">
<meta property="og:description" content="One-way ANOVA and its connection to regression: partitioning sums of squares, the F-ratio, assumptions and diagnostics, post-hoc testing, reporting, and non-parametric alternatives (Kruskal-Wallis, Dunn’s test) — on a circadian-rhythm light-treatment dataset.">
<meta property="og:image" content="https://wlperry.github.io/ecostats_2026/content/analysis_of_variance/images/clipboard-2698541257.png">
<meta property="og:site_name" content="UMD Biostatistics">
<meta property="og:image:height" content="466">
<meta property="og:image:width" content="716">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Lecture: Analysis of Variance (ANOVA)</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/course-hex.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../../images/course-hex.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://wlperry.github.io/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">← Back to Homepage</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Course Information</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Helpful Links</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Course Materials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lectures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../activities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../vignettes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vignettes</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="analysis_of_variance_lecture.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="analysis_of_variance_lecture.pptx"><i class="bi bi-file-slides"></i>Powerpoint</a></li><li><a href="analysis_of_variance_lecture.slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lecture: Analysis of Variance (ANOVA)</h1>
<p class="subtitle lead">Single-factor ANOVA</p>
  <div class="quarto-categories">
    <div class="quarto-category">ANOVA</div>
  </div>
  </div>

<div>
  <div class="description">
    One-way ANOVA and its connection to regression: partitioning sums of squares, the F-ratio, assumptions and diagnostics, post-hoc testing, reporting, and non-parametric alternatives (Kruskal-Wallis, Dunn’s test) — on a circadian-rhythm light-treatment dataset.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bill Perry </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="where-we-left-off" class="level2">
<h2 class="anchored" data-anchor-id="where-we-left-off">Where We Left Off</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Covered last time — Multiple Regression:</p>
<ul>
<li>The MLR model, regression parameters</li>
<li>Analysis of variance for regression</li>
<li>Null hypotheses, explained variance</li>
<li>Assumptions and diagnostics</li>
<li>Collinearity, interactions, dummy variables</li>
<li>Model selection, importance of predictors</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>✅ Key idea from last lecture</strong></p>
<p>You already built an ANOVA table for a regression — you just called it “analysis of variance for regression.” Today we apply the exact same machinery to categorical predictors.</p>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-2698541257.png" class="img-fluid figure-img" width="300"></p>
<figcaption>XKCD comic ‘Linear Regression’: a scatterplot of scattered points with a nearly flat fitted regression line labeled R-squared = 0.06 next to the same points connected into a constellation-like stick figure labeled ‘Rexthor, the Dog-Bearer’, captioned ‘I don’t trust linear regressions when it’s harder to guess the direction of the correlation from the scatter plot than to find new constellations on it.’</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="part-1-anova-overview" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-1-anova-overview">Part 1 · ANOVA Overview</h2>
</section>
<section id="todays-objectives" class="level2">
<h2 class="anchored" data-anchor-id="todays-objectives">Today’s Objectives</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>ANOVA:</strong> analysis of variance, single-factor today, multi-factor to come.</p>
<ul>
<li>Predictor variables: fixed</li>
<li>The ANOVA model</li>
<li>Analysis and partitioning of variance</li>
<li>Null hypothesis</li>
<li>Assumptions and diagnostics</li>
<li>Post-hoc tests — Tukey and others</li>
<li>Reporting the results</li>
<li>Mixed-model ANOVA — random effects</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>📖 Reference</strong></p>
<p>Gotelli &amp; Ellison, <em>A Primer of Ecological Statistics</em>, Ch. 10 — The Analysis of Variance, is the core reference for this lecture.</p>
</div>
</div>
</div><div class="column" style="width:40%;">
<p>What if the response is continuous and the predictor(s) categorical?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Continuous X</th>
<th style="text-align: left;">Categorical X</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Continuous Y</strong></td>
<td style="text-align: left;">Regression</td>
<td style="text-align: left;">ANOVA</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Categorical Y</strong></td>
<td style="text-align: left;">Logistic regression</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="part-2-anova-and-regression-connection" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-2-anova-and-regression-connection">Part 2 · ANOVA and Regression Connection</h2>
</section>
<section id="anova-and-regression-connection" class="level2">
<h2 class="anchored" data-anchor-id="anova-and-regression-connection">ANOVA and Regression Connection</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Both regression and ANOVA:</strong></p>
<ul>
<li>Partition the total variation in Y</li>
<li>Use F-tests for significance, where one MS is divided by another</li>
</ul>
<p><strong>Regression:</strong></p>
<ul>
<li>Form: <span class="math inline">\(Y = \beta_0 + \beta_1X + \varepsilon\)</span> — Y is the response, β₀ the intercept, β₁ the slope, X the predictor, ε the error</li>
<li>Test: <span class="math inline">\(H_0: \beta_1 = 0\)</span> — rejecting means X significantly predicts Y</li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>ANOVA:</strong></p>
<ul>
<li>Form: <span class="math inline">\(Y_{ij} = \mu + A_i + \varepsilon_{ij}\)</span> — <span class="math inline">\(Y_{ij}\)</span> is observation j in group i, μ the grand mean, <span class="math inline">\(A_i\)</span> the effect of group i, ε the error</li>
<li>Test: <span class="math inline">\(H_0: \mu_1 = \mu_2 = ... = \mu_k\)</span> — rejecting means at least one group differs</li>
</ul>
</div>
</div>
</section>
<section id="the-same-partitioning-two-kinds-of-predictor" class="level2">
<h2 class="anchored" data-anchor-id="the-same-partitioning-two-kinds-of-predictor">The Same Partitioning, Two Kinds of Predictor</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>General method for partitioning variation in a continuous dependent variable:</p>
<ul>
<li>One or more continuous (and categorical) predictors → <strong>regression</strong></li>
<li>One or more categorical predictors → <strong>ANOVA</strong></li>
<li>Categorical predictor variables represent groups or experimental treatments</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" alt="Two stacked plots: a scatterplot of absorbance versus nitrate concentration with a fitted regression line and equation, above a jittered scatterplot of phase shift by light treatment group with mean points and confidence-interval error bars, illustrating that regression and ANOVA both partition variation but with a continuous versus categorical predictor." width="345"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="anova-as-regression" class="level2">
<h2 class="anchored" data-anchor-id="anova-as-regression">ANOVA as Regression</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>ANOVA as regression</strong></p>
<p>With one categorical variable, ANOVA is equivalent to regression with dummy variables. In fact, when we run ANOVAs we use the same code as for regression!</p>
<p><code>regression: model &lt;- lm(response ~ predictor, data = df)</code> <code>anova: model &lt;- lm(response ~ factor, data = df)</code></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" alt="Jittered scatterplot of a simulated response variable by three nutrient treatment groups (No, Low, High), with diamond points marking each group's mean and confidence-interval error bars, illustrating a one-way ANOVA setup." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="part-3-anova-goals-and-logic" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-3-anova-goals-and-logic">Part 3 · ANOVA Goals and Logic</h2>
</section>
<section id="anova-goals" class="level2">
<h2 class="anchored" data-anchor-id="anova-goals">ANOVA Goals</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>ANOVA aims to compare means of groups:</p>
<ul>
<li>Attributes contribution of predictors + “error” to variability</li>
<li>Tests H₀ that population (random effects) or group (fixed effects) means are equal</li>
<li>Single factor (1-way) and multifactor (2-, 3-way designs)
<ul>
<li>Single factor: one factor with more than two levels</li>
</ul></li>
<li>Multifactor: two or three factors with two or more levels each — examines variation due to factors <strong>AND</strong> their interaction</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" alt="Jittered scatterplot of circadian phase shift by light treatment (Control, Knees, Eyes), with diamond points marking each group's mean and confidence-interval error bars." width="288"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="analysis-of-variance" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-variance">Analysis of Variance</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><em>Analysis of variance</em> is the most powerful approach known for simultaneously testing if the means of k groups are equal — it works by assessing whether individuals chosen from different groups are, on average, more different than individuals chosen from the same group.</p>
<p>The null hypothesis of ANOVA is that the population means μᵢ are the same for all treatments.</p>
<ul>
<li><strong>H₀:</strong> μ₁ = μ₂ = … = μₖ</li>
<li><strong>H₁:</strong> at least one μᵢ is different from the others</li>
</ul>
<p>Rejecting H₀ in ANOVA is evidence that the mean of at least one group is different from the others — it does <strong>not</strong> indicate <em>which</em> means differ.</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" alt="The circadian phase shift by light treatment plot repeated, shown alongside the ANOVA null and alternative hypothesis statements." width="288"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="anova-logic" class="level2">
<h2 class="anchored" data-anchor-id="anova-logic">ANOVA Logic</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Even if all groups had the same true mean, the data would likely show different sample means for each group due to sampling error.</p>
<p>The key insight of ANOVA: we can estimate how much variation among group means ought to be present from sampling error alone if H₀ is true. ANOVA lets us determine whether there is more variance among the sample means than expected by chance alone. If so, we infer real differences among the population means.</p>
<p>Two key measures of variation are calculated and compared:</p>
<ol type="1">
<li><strong>Group mean square (<span class="math inline">\(MS_{groups}\)</span>)</strong> — variation among subjects from different groups</li>
<li><strong>Error mean square (<span class="math inline">\(MS_{error}\)</span>)</strong> — variation among subjects within the same group</li>
</ol>
<p><span class="math display">\[F = \frac{MS_{groups}}{MS_{error}}\]</span></p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" alt="Three stacked plots illustrating ANOVA's variance partitioning: total variation as each point's deviation from the grand mean, among-groups variation as each group mean's deviation from the grand mean, and within-groups variation as each point's deviation from its own group mean." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="part-4-partitioning-the-sum-of-squares" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-4-partitioning-the-sum-of-squares">Part 4 · Partitioning the Sum of Squares</h2>
</section>
<section id="partitioning-the-sum-of-squares" class="level2">
<h2 class="anchored" data-anchor-id="partitioning-the-sum-of-squares">Partitioning the Sum of Squares</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>The total variation in Y can be expressed as a sum of squares:</p>
<p><span class="math display">\[SS_{total} = \sum_{i=1}^{a}\sum_{j=1}^{n}(Y_{ij} - \bar{Y})^2\]</span></p>
<p>This can be partitioned into two components:</p>
<ol type="1">
<li><strong>Among Groups (Treatment):</strong> <span class="math inline">\(SS_{among} = n\sum_{i=1}^{a}(\bar{Y}_i - \bar{Y})^2\)</span></li>
<li><strong>Within Groups (Error):</strong> <span class="math inline">\(SS_{within} = \sum_{i=1}^{a}\sum_{j=1}^{n}(Y_{ij} - \bar{Y}_i)^2\)</span></li>
</ol>
<p>These components are additive: <span class="math inline">\(SS_{total} = SS_{among} + SS_{within}\)</span></p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" alt="The three-panel total/among/within variance partitioning figure repeated, shown alongside the sum-of-squares formulas it illustrates." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="a-worked-sum-of-squares-example" class="level2">
<h2 class="anchored" data-anchor-id="a-worked-sum-of-squares-example">A Worked Sum-of-Squares Example</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = phase_shift ~ treatment, data = circ_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.27857 -0.36125  0.03857  0.61147  1.06571 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    -0.30875    0.24888  -1.241  0.22988   
treatmentEyes  -1.24268    0.36433  -3.411  0.00293 **
treatmentKnees -0.02696    0.36433  -0.074  0.94178   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7039 on 19 degrees of freedom
Multiple R-squared:  0.4342,    Adjusted R-squared:  0.3746 
F-statistic: 7.289 on 2 and 19 DF,  p-value: 0.004472</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: phase_shift
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
treatment  2 7.2245  3.6122  7.2894 0.004472 **
Residuals 19 9.4153  0.4955                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Key connection to regression</strong></p>
<p>This is the same partitioning we saw in regression analysis:</p>
<p><span class="math display">\[SS_{total} = SS_{regression} + SS_{residual}\]</span></p>
<ul>
<li><span class="math inline">\(SS_{among}\)</span> in ANOVA = <span class="math inline">\(SS_{regression}\)</span> in regression</li>
<li><span class="math inline">\(SS_{within}\)</span> in ANOVA = <span class="math inline">\(SS_{residual}\)</span> in regression</li>
</ul>
<p>Both measure how much variation is explained by our model vs.&nbsp;unexplained (error).</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-anova-table" class="level2">
<h2 class="anchored" data-anchor-id="the-anova-table">The ANOVA Table</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>The ANOVA table organizes all computations leading to a test of the null hypothesis of no differences among population means.</p>
<ul>
<li><strong>Source of variation</strong> — what is being tested</li>
<li><strong>Sum of squares</strong> — total variation for each source</li>
<li><strong>df</strong> — degrees of freedom for each source</li>
<li><strong>Mean squares</strong> — sum of squares divided by df</li>
<li><strong>F-ratio</strong> — ratio of mean squares, used to test significance</li>
<li><strong>P-value</strong> — probability of observing our results if H₀ is true</li>
</ul>
<p><strong>Example:</strong> for a one-way ANOVA with 3 groups and 4 replicates per group: df(treatments) = a − 1 = 2, df(error) = a(n − 1) = 3(4 − 1) = 9, df(total) = an − 1 = 11</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = phase_shift ~ treatment, data = circ_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.27857 -0.36125  0.03857  0.61147  1.06571 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    -0.30875    0.24888  -1.241  0.22988   
treatmentEyes  -1.24268    0.36433  -3.411  0.00293 **
treatmentKnees -0.02696    0.36433  -0.074  0.94178   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7039 on 19 degrees of freedom
Multiple R-squared:  0.4342,    Adjusted R-squared:  0.3746 
F-statistic: 7.289 on 2 and 19 DF,  p-value: 0.004472</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: phase_shift
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
treatment  2 7.2245  3.6122  7.2894 0.004472 **
Residuals 19 9.4153  0.4955                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  treatment   Mean    SD     N
  &lt;fct&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
1 Control   -0.309 0.618     8
2 Eyes      -1.55  0.706     7
3 Knees     -0.336 0.791     7</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="comparing-anova-and-regression-tables" class="level2">
<h2 class="anchored" data-anchor-id="comparing-anova-and-regression-tables">Comparing ANOVA and Regression Tables</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>ANOVA table:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th>df</th>
<th>SS</th>
<th>MS</th>
<th>F</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treatment</td>
<td>a-1</td>
<td>SS_treatment</td>
<td>MS_treatment</td>
<td>F</td>
<td>p</td>
</tr>
<tr class="even">
<td>Error</td>
<td>a(n-1)</td>
<td>SS_error</td>
<td>MS_error</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>a*n-1</td>
<td>SS_total</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Is equivalent to an ANOVA table from a regression model:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th>df</th>
<th>SS</th>
<th>MS</th>
<th>F</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td>k</td>
<td>SS_regression</td>
<td>MS_regression</td>
<td>F</td>
<td>p</td>
</tr>
<tr class="even">
<td>Error</td>
<td>n-k-1</td>
<td>SS_residual</td>
<td>MS_residual</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>n-1</td>
<td>SS_total</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Where k = number of predictor/dummy variables = a − 1, and a = treatment groups/levels of factors.</p>
</div>
</div>
</section>
<section id="part-5-the-f-ratio" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-5-the-f-ratio">Part 5 · The F-Ratio</h2>
</section>
<section id="the-f-ratio" class="level2">
<h2 class="anchored" data-anchor-id="the-f-ratio">The F-Ratio</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><span class="math display">\[F = \frac{MS_{among}}{MS_{error}}\]</span></p>
<ul>
<li>Under H₀ (all means equal): the F-ratio should be approximately 1</li>
<li>Larger F-ratios suggest among-group variance exceeds what’s expected by chance</li>
<li>With the circadian rhythm data: F = 7.29, p = 0.004 — we reject H₀</li>
<li>The F-ratio follows an F-distribution with (a − 1) and a(n − 1) df</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Metric                    Value
  &lt;chr&gt;                     &lt;dbl&gt;
1 F-observed                 7.29
2 F-critical (alpha = 0.05)  3.52</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" alt="F-distribution curve with 2 and 19 degrees of freedom, with the rejection region beyond the critical F-value shaded red and a dashed blue line marking the critical F-value." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="connection-of-an-f-test-to-a-t-test" class="level2">
<h2 class="anchored" data-anchor-id="connection-of-an-f-test-to-a-t-test">Connection of an F-Test to a T-Test</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>An ANOVA with two groups (a = 2) is equivalent to a t-test — why F = t²? Both test the same hypothesis: are the means of two groups different?</p>
<ul>
<li><strong>The t-statistic:</strong> <span class="math inline">\(t = \frac{\bar{X}_1 - \bar{X}_2}{SE_{difference}}\)</span> — measures how many standard errors apart the two means are, and can be + or −</li>
<li><strong>The F-statistic:</strong> <span class="math inline">\(F = \frac{MS_B}{MS_W}\)</span> — the ratio of variance <em>between</em> groups to variance <em>within</em> groups</li>
<li>Unlike t, F is always non-negative (it’s a ratio of squared quantities)</li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>The mathematical connection:</strong></p>
<ul>
<li>Both measure the same signal-to-noise ratio — numerators capture the difference between groups (signal), denominators capture variability within groups (noise)</li>
<li>With two groups: <span class="math inline">\(MS_B\)</span> relates directly to <span class="math inline">\((\bar{X}_1 - \bar{X}_2)^2\)</span>, and <span class="math inline">\(MS_W\)</span> relates to the pooled variance</li>
<li><strong>Degrees of freedom match up too:</strong> t-test df = n₁ + n₂ − 2; F-test df₁ = 1 (numerator), df₂ = n₁ + n₂ − 2 (denominator)</li>
<li>An F-distribution with df₁ = 1 is the square of a t-distribution with df₂</li>
</ul>
</div>
</div>
</section>
<section id="why-this-matters-anova-generalizes-the-t-test" class="level2">
<h2 class="anchored" data-anchor-id="why-this-matters-anova-generalizes-the-t-test">Why This Matters — ANOVA Generalizes the T-Test</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Shows ANOVA is actually a <em>generalization</em> of the t-test</li>
<li>When a = 2, you get the same result either way</li>
<li>But ANOVA extends naturally to comparing three or more groups — you can’t do that directly with a t-test without running into multiple-comparison problems</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Using circ_data (Control vs Knees groups):
 t-statistic: 0.0741 
 t^2: 0.0055 
 F-statistic: 0.0055 
 Difference (should be ~0): 0 </code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="f-ratio-confirmed-on-the-full-model" class="level2">
<h2 class="anchored" data-anchor-id="f-ratio-confirmed-on-the-full-model">F-Ratio, Confirmed on the Full Model</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><span class="math display">\[F = \frac{MS_{among}}{MS_{error}}\]</span></p>
<ul>
<li>Under H₀ (all means equal), the F-ratio should be ≈ 1</li>
<li>Larger F-ratios suggest among-group variance exceeds chance</li>
<li>With the circadian rhythm data: F₂,₁₉ = 7.29, p = 0.004 — we reject H₀</li>
<li>The F-ratio follows an F-distribution with (a − 1) and a(n − 1) df</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = phase_shift ~ treatment, data = circ_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.27857 -0.36125  0.03857  0.61147  1.06571 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    -0.30875    0.24888  -1.241  0.22988   
treatmentEyes  -1.24268    0.36433  -3.411  0.00293 **
treatmentKnees -0.02696    0.36433  -0.074  0.94178   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7039 on 19 degrees of freedom
Multiple R-squared:  0.4342,    Adjusted R-squared:  0.3746 
F-statistic: 7.289 on 2 and 19 DF,  p-value: 0.004472</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: phase_shift
          Sum Sq Df F value   Pr(&gt;F)   
treatment 7.2245  2  7.2894 0.004472 **
Residuals 9.4153 19                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" alt="The circadian phase shift by light treatment plot repeated once more, shown alongside the F-ratio result confirmed on the full three-group model." width="288"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="part-6-variance-explained-r²" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-6-variance-explained-r²">Part 6 · Variance Explained — R²</h2>
</section>
<section id="variance-explained-r²" class="level2">
<h2 class="anchored" data-anchor-id="variance-explained-r²">Variance Explained: R²</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>R² summarizes the contribution of group differences to total variation:</p>
<p><span class="math display">\[R^2 = \frac{SS_{among}}{SS_{total}}\]</span></p>
<p>This is interpreted as the “fraction of the variation in Y that is explained by groups.” For the circadian rhythm data:</p>
<p><span class="math display">\[R^2 = \frac{7.224}{16.639} = 0.43\]</span></p>
<p>43% of the total variation in phase shift is explained by differences in light treatment, with the remaining 57% unexplained.</p>
<p><strong>Connection to regression:</strong> this is exactly the same calculation as R² in regression, <span class="math inline">\(R^2 = SS_{regression}/SS_{total}\)</span>.</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" alt="Two stacked plots: a filled-rectangle diagram showing the percentage of variance explained (blue) versus unexplained (grey) by treatment, and a scatterplot of phase shift against treatment group coded as a number with a fitted regression line and R-squared label, showing ANOVA as a regression view." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="part-7-assumptions-and-diagnostics" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-7-assumptions-and-diagnostics">Part 7 · Assumptions and Diagnostics</h2>
</section>
<section id="anova-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="anova-assumptions">ANOVA Assumptions</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>ANOVA has the same assumptions as the two-sample t-test, but applied to all k groups:</p>
<ul>
<li><strong>Random samples</strong> from corresponding populations</li>
<li><strong>Normality</strong> — Y values are normally distributed in each population</li>
<li><strong>Homogeneity of variance</strong> — variance is the same in all populations</li>
<li><strong>Independence</strong> — observations are independent</li>
</ul>
</div><div class="column" style="width:40%;">
<p><strong>Checking assumptions:</strong></p>
<ul>
<li>Normality: QQ plots, histogram of residuals, Shapiro-Wilk test</li>
<li>Homogeneity: plot residuals vs.&nbsp;predicted values or x-values</li>
<li>Independence: examine the experimental design</li>
</ul>
<p><strong>If assumptions are violated:</strong> transform Y (e.g., log, square root), use robust or non-parametric alternatives, or use generalized linear models (GLMs).</p>
</div>
</div>
</section>
<section id="the-four-standard-diagnostic-plots" class="level2">
<h2 class="anchored" data-anchor-id="the-four-standard-diagnostic-plots">The Four Standard Diagnostic Plots</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" alt="Four standard regression diagnostic plots for the ANOVA model, hand-built with ggplot2: residuals vs. fitted, normal Q-Q, scale-location, and residuals vs. leverage." width="345"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>🖐 Notice</strong></p>
<p>These are the same four diagnostic views R gives you automatically from <code>plot(model)</code> — here built by hand with <code>ggplot2</code> + <code>broom::fortify()</code> so we can style them consistently.</p>
</div>
</div>
</div>
</div>
</section>
<section id="a-newer-way-to-check-the-performance-package" class="level2">
<h2 class="anchored" data-anchor-id="a-newer-way-to-check-the-performance-package">A Newer Way to Check — the <code>performance</code> Package</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="diagnostics_2.png" class="img-fluid figure-img" style="width:4in"></p>
<figcaption>Multi-panel model diagnostic figure generated by performance::check_model(), including residual, normality, homogeneity of variance, and collinearity panels with built-in reference bands.</figcaption>
</figure>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>✅ Key idea</strong></p>
<p><code>check_model()</code> from the <code>performance</code> package builds all the standard diagnostic panels — plus a few extra (e.g., collinearity) — in one call, with built-in guidance on what “good” looks like for each panel.</p>
</div>
</div>
</div>
</div>
</section>
<section id="levenes-test" class="level2">
<h2 class="anchored" data-anchor-id="levenes-test">Levene’s Test</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Levene’s test of homogeneity of variance.</p>
<ul>
<li>Null hypothesis: variances are homogeneous</li>
<li>So you <em>want</em> a non-significant result here</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  2  0.1586 0.8545
      19               </code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="shapiro-wilk-test" class="level2">
<h2 class="anchored" data-anchor-id="shapiro-wilk-test">Shapiro-Wilk Test</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Shapiro-Wilk normality test.</p>
<ul>
<li>Null hypothesis: the data are normally distributed</li>
<li>So you <em>want</em> a non-significant result here</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(circ_model)
W = 0.95893, p-value = 0.468</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="shared-assumptions-with-regression" class="level2">
<h2 class="anchored" data-anchor-id="shared-assumptions-with-regression">Shared Assumptions with Regression</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>ANOVA and regression share virtually identical assumptions, because they are both linear models:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Assumption</th>
<th>ANOVA</th>
<th>Regression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linearity</td>
<td>Each group has its own mean; effects are additive (no interaction in one-way ANOVA)</td>
<td>Relationship between X and Y is linear</td>
</tr>
<tr class="even">
<td>Normality</td>
<td>Residuals are normal</td>
<td>Residuals are normal</td>
</tr>
<tr class="odd">
<td>Equal variance</td>
<td>Variance is the same across all groups</td>
<td>Variance is the same across all X values</td>
</tr>
<tr class="even">
<td>Independence</td>
<td>Observations are independent</td>
<td>Observations are independent</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="part-8-post-hoc-testing" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-8-post-hoc-testing">Part 8 · Post-Hoc Testing</h2>
</section>
<section id="anova-post-hoc-testing-overview" class="level2">
<h2 class="anchored" data-anchor-id="anova-post-hoc-testing-overview">ANOVA Post-Hoc Testing — Overview</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>When ANOVA rejects H₀, we need to determine which groups differ.</p>
<ul>
<li><strong>Unplanned (post hoc) comparisons:</strong> used when no specific comparisons were planned; must adjust for multiple testing. Common methods: Tukey-Kramer, Bonferroni, Scheffé, Sidak</li>
<li><strong>Planned comparisons:</strong> have strong prior justification, use pooled variance from all groups, have higher precision than separate t-tests</li>
<li><strong>Example:</strong> Tukey’s HSD to compare all pairs of treatments in the circadian rhythm data</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> contrast        estimate    SE df t.ratio p.value
 Control - Eyes     1.243 0.364 19   3.411  0.0079
 Control - Knees    0.027 0.364 19   0.074  0.9970
 Eyes - Knees      -1.216 0.376 19  -3.231  0.0117

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment emmean    SE df lower.CL upper.CL .group
 Eyes      -1.551 0.266 19    -2.25   -0.855  a    
 Knees     -0.336 0.266 19    -1.03    0.361   b   
 Control   -0.309 0.249 19    -0.96    0.343   b   

Confidence level used: 0.95 
Conf-level adjustment: sidak method for 3 estimates 
P value adjustment: tukey method for comparing a family of 3 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="post-hoc-testing-planned-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-testing-planned-comparisons">Post-Hoc Testing — Planned Comparisons</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>When ANOVA rejects H₀, we need to determine which groups differ.</p>
<ul>
<li><strong>Unplanned (post hoc) comparisons:</strong> used when no specific comparisons were planned; must adjust for multiple testing. Common methods: Tukey-Kramer, Bonferroni, Scheffé</li>
<li><strong>Planned comparisons:</strong> have strong prior justification, use pooled variance from all groups, have higher precision than separate t-tests</li>
<li><strong>Example:</strong> using Tukey’s HSD to compare all pairs of treatments</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Control" "Eyes"    "Knees"  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast         estimate    SE df t.ratio p.value
 control vs eyes     1.243 0.364 19   3.411  0.0029
 control vs knees    0.027 0.364 19   0.074  0.9418</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="comparison-of-post-hoc-tests" class="level2">
<h2 class="anchored" data-anchor-id="comparison-of-post-hoc-tests">Comparison of Post-Hoc Tests</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>The main post-hoc tests:</strong></p>
<ul>
<li><strong>Tukey-Kramer (HSD):</strong> compares all possible pairs of group means, controls family-wise error rate, most powerful when comparing ALL pairwise combinations</li>
<li><strong>Bonferroni:</strong> adjusts α by dividing by the number of comparisons (α/k); very conservative; best for a small number of <em>planned</em> comparisons</li>
<li><strong>Sidak:</strong> similar to Bonferroni but slightly less conservative: 1−(1−α)^(1/k); gives slightly more power</li>
<li><strong>Dunnett’s Test:</strong> specifically for comparing treatment groups to a control; more powerful than the others for that specific job</li>
</ul>
<p>The key tradeoff is between power (detecting real differences) and Type I error control (avoiding false positives). More conservative tests give better error control but less power.</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tukey_result <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(circ_model, <span class="st">"treatment"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>bonferroni_result <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(circ_model, <span class="st">"treatment"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>sidak_result <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(circ_model, <span class="st">"treatment"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">adjust =</span> <span class="st">"sidak"</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>dunnett_result <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(circ_model, <span class="st">"treatment"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">contrast</span>(<span class="at">method =</span> <span class="st">"trt.vs.ctrl"</span>, <span class="at">ref =</span> <span class="dv">1</span>, <span class="at">adjust =</span> <span class="st">"dunnett"</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>all_methods <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(tukey_result) <span class="sc">|&gt;</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(contrast, estimate, SE, p.value) <span class="sc">|&gt;</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Method =</span> <span class="st">"Tukey"</span>),</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(bonferroni_result) <span class="sc">|&gt;</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(contrast, estimate, SE, p.value) <span class="sc">|&gt;</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Method =</span> <span class="st">"Bonferroni"</span>),</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(sidak_result) <span class="sc">|&gt;</span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(contrast, estimate, SE, p.value) <span class="sc">|&gt;</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Method =</span> <span class="st">"Sidak"</span>)</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>all_methods <span class="sc">|&gt;</span></span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(contrast, Method, p.value) <span class="sc">|&gt;</span></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Method, <span class="at">values_from =</span> p.value) <span class="sc">|&gt;</span></span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Tukey)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  contrast          Tukey Bonferroni   Sidak
  &lt;chr&gt;             &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1 Control - Eyes  0.00787    0.00879 0.00877
2 Eyes - Knees    0.0117     0.0132  0.0131 
3 Control - Knees 0.997      1       1.000  </code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="post-hoc-visualization" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-visualization">Post-Hoc Visualization</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>When ANOVA rejects H₀, we need to determine which groups differ.</p>
<ul>
<li><strong>Unplanned comparisons:</strong> used when no specific comparisons were planned; must adjust for multiple testing. Common methods: Tukey-Kramer, Bonferroni, Scheffé</li>
<li><strong>Planned comparisons:</strong> have strong prior justification, use pooled variance, higher precision than separate t-tests</li>
<li><strong>Example:</strong> Tukey’s HSD to compare all pairs of treatments</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" alt="Estimated marginal mean phase shift by treatment with 95% confidence interval error bars, connected by a line." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="significance-groups-plot" class="level2">
<h2 class="anchored" data-anchor-id="significance-groups-plot">Significance Groups Plot</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>When ANOVA rejects H₀, we need to determine which groups differ.</p>
<ul>
<li><strong>Unplanned comparisons:</strong> used when no specific comparisons were planned; must adjust for multiple testing. Common methods: Tukey-Kramer, Bonferroni, Scheffé</li>
<li><strong>Planned comparisons:</strong> have strong prior justification, use pooled variance, higher precision than separate t-tests</li>
<li><strong>Example:</strong> Tukey’s HSD to compare all pairs of treatments</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" alt="Jittered scatterplot of phase shift by treatment with mean points and confidence-interval error bars, and Tukey compact-letter-display labels below each group showing which groups share a letter (not significantly different)." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="part-9-reporting-results" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-9-reporting-results">Part 9 · Reporting Results</h2>
</section>
<section id="reporting-anova-results" class="level2">
<h2 class="anchored" data-anchor-id="reporting-anova-results">Reporting ANOVA Results</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Formal scientific writing example:</strong></p>
<p>“The effect of light treatment on circadian rhythm phase shift was analyzed using a one-way ANOVA. There was a significant effect of treatment on phase shift (F(2, 19) = 7.29, p = 0.004, η² = 0.43). Post-hoc comparisons using Tukey’s HSD test indicated that the mean phase shift for the Eyes treatment (M = −1.55 h, SD = 0.71) was significantly different from both the Control treatment (M = −0.31 h, SD = 0.62) and the Knees treatment (M = −0.34 h, SD = 0.79). However, the Control and Knees treatments did not significantly differ from each other. These results suggest that light exposure to the eyes, but not to the knees, impacts circadian rhythm phase shifts.”</p>
</div><div class="column" style="width:40%;">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Key ANOVA principles</strong></p>
<ol type="1">
<li>Compares means across multiple groups simultaneously</li>
<li>Both ANOVA and regression are special cases of the General Linear Model — ANOVA with categorical predictors = regression with dummy variables</li>
<li>Both partition variance into explained and unexplained components: <span class="math inline">\(SS_{Total} = SS_{Between} + SS_{Within}\)</span></li>
<li>Fixed effects target specific groups of interest (most common); random effects sample from a larger population</li>
</ol>
</div>
</div>
</div>
</div>
</section>
<section id="part-10-non-parametric-alternatives" class="level2 divider">
<h2 class="divider anchored" data-anchor-id="part-10-non-parametric-alternatives">Part 10 · Non-Parametric Alternatives</h2>
</section>
<section id="overview-of-non-parametric-tests" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-non-parametric-tests">Overview of Non-Parametric Tests</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Common non-parametric alternatives to ANOVA</strong> — these make fewer assumptions about the data distribution.</p>
<ol type="1">
<li><strong>Kruskal-Wallis test</strong> — non-parametric alternative to one-way ANOVA; tests for differences in median ranks; works with ordinal or continuous data. Assumptions: independent observations, similar distribution shapes</li>
<li><strong>Mood’s median test</strong> (not covered here) — tests whether medians differ across groups; more robust but less powerful than Kruskal-Wallis; good for highly skewed data</li>
</ol>
</div><div class="column" style="width:40%;">
<p><strong>When to use non-parametric tests:</strong></p>
<ul>
<li>Small sample sizes</li>
<li>Heavily skewed data</li>
<li>Legitimate outliers present</li>
<li>Very unequal variances</li>
<li>Ordinal (ranked) data</li>
<li>Assumption checks clearly fail</li>
</ul>
<p><strong>Trade-offs:</strong> fewer assumptions and more robust to outliers, but less statistical power and testing medians/ranks rather than means.</p>
</div>
</div>
</section>
<section id="the-kruskal-wallis-h-test" class="level2">
<h2 class="anchored" data-anchor-id="the-kruskal-wallis-h-test">The Kruskal-Wallis H Test</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>The most common non-parametric alternative to one-way ANOVA.</p>
<p><strong>What it does:</strong> ranks all observations from smallest to largest, compares the sum of ranks between groups, tests if groups come from the same distribution.</p>
<p><strong>Hypotheses:</strong> H₀ — all groups have the same distribution (same median); H₁ — at least one group differs.</p>
<p><strong>Test statistic:</strong></p>
<p><span class="math display">\[H = \frac{12}{N(N+1)} \sum_{i=1}^{k} n_i (\bar{R}_i - \bar{R})^2 - 3(N+1)\]</span></p>
<p>Where N = total sample size, k = number of groups, <span class="math inline">\(\bar{R}_i\)</span> = mean rank for group i, <span class="math inline">\(\bar{R}\)</span> = overall mean rank = (N+1)/2, nᵢ = sample size for group i. Distribution approximated by χ² with (k−1) df.</p>
</div><div class="column" style="width:40%;">
<p><strong>Assumptions of Kruskal-Wallis — much more relaxed than parametric ANOVA:</strong></p>
<ul>
<li><strong>Independence</strong> — same as parametric ANOVA, still critical</li>
<li><strong>Similar distribution shapes</strong> — groups should have similar spread/variance; if violated, interpret as differences in distributions generally, not just medians</li>
<li><strong>Ordinal or continuous data</strong></li>
</ul>
<p><strong>What’s NOT assumed:</strong> normal distribution, equal variances (though it helps interpretation), a specific distribution shape.</p>
</div>
</div>
</section>
<section id="demonstrating-assumption-violations" class="level2">
<h2 class="anchored" data-anchor-id="demonstrating-assumption-violations">Demonstrating Assumption Violations</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Creating a modified dataset with clear violations:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>violated_circ_df <span class="ot">&lt;-</span> circ_data <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">phase_shift_violated =</span> <span class="fu">case_when</span>(</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>      treatment <span class="sc">==</span> <span class="st">"Control"</span> <span class="sc">~</span> phase_shift,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>      treatment <span class="sc">==</span> <span class="st">"Knees"</span> <span class="sc">~</span> phase_shift <span class="sc">*</span> <span class="fl">3.25</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>      treatment <span class="sc">==</span> <span class="st">"Eyes"</span> <span class="sc">~</span> {</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>        n <span class="ot">&lt;-</span> <span class="fu">length</span>(phase_shift)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(phase_shift[<span class="dv">1</span><span class="sc">:</span>(n<span class="dv">-2</span>)], phase_shift[(n<span class="dv">-1</span>)<span class="sc">:</span>n] <span class="sc">-</span> <span class="dv">7</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>violated_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(phase_shift_violated <span class="sc">~</span> treatment,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> violated_circ_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What we changed:</strong> increased variance in the Knees group, added extreme outliers to the Eyes group, creating unequal variances and non-normality.</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" alt="Jittered scatterplot with boxplots of a modified phase-shift dataset with deliberately introduced unequal variance and outliers, by light treatment group." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="checking-violated-data-assumptions-normality" class="level2">
<h2 class="anchored" data-anchor-id="checking-violated-data-assumptions-normality">Checking Violated-Data Assumptions — Normality</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Clear violation:</strong> p &lt; 0.05, points deviate from the line.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  resid(violated_model)
W = 0.89473, p-value = 0.02335</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" alt="Normal Q-Q plot of residuals from the deliberately violated ANOVA model, with points visibly curving away from the reference line, showing a clear departure from normality." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="checking-violated-data-assumptions-variance" class="level2">
<h2 class="anchored" data-anchor-id="checking-violated-data-assumptions-variance">Checking Violated-Data Assumptions — Variance</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Clear violation:</strong> p &lt; 0.05, unequal variances evident.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  2  1.5618 0.2355
      19               </code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" alt="Scale-location plot for the deliberately violated ANOVA model, showing an uneven spread of standardized residuals across fitted values consistent with unequal variance." width="326"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="performing-the-kruskal-wallis-test-original-data" class="level2">
<h2 class="anchored" data-anchor-id="performing-the-kruskal-wallis-test-original-data">Performing the Kruskal-Wallis Test — Original Data</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Even though assumptions are met, let’s compare results:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>kruskal_original_result <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  phase_shift <span class="sc">~</span> treatment,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> circ_data)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>kruskal_original_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  phase_shift by treatment
Kruskal-Wallis chi-squared = 9.4231, df = 2, p-value = 0.008991</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> H = test statistic (χ² approximation); df = k − 1 = 2; p = 0.0135 (significant at α = 0.05); conclusion: at least one group differs.</p>
<p><strong>Compare to parametric ANOVA:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: phase_shift
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
treatment  2 7.2245  3.6122  7.2894 0.004472 **
Residuals 19 9.4153  0.4955                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<p><strong>How Kruskal-Wallis works:</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" alt="Jittered scatterplot of rank-transformed phase shift by treatment, with diamond points marking each group's mean rank, illustrating the ranks the Kruskal-Wallis test compares." width="307"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  treatment mean_rank sum_rank     n
  &lt;fct&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
1 Control       14.6       117     8
2 Eyes           5.29       37     7
3 Knees         14.1        99     7</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="kruskal-wallis-on-violated-data" class="level2">
<h2 class="anchored" data-anchor-id="kruskal-wallis-on-violated-data">Kruskal-Wallis on Violated Data</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Non-parametric test handles violations:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>kruskal_violated_result <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  phase_shift_violated <span class="sc">~</span> treatment,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> violated_circ_df)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>kruskal_violated_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  phase_shift_violated by treatment
Kruskal-Wallis chi-squared = 6.8453, df = 2, p-value = 0.03263</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: phase_shift_violated
          Df  Sum Sq Mean Sq F value Pr(&gt;F)  
treatment  2  41.806 20.9029  2.8361 0.0836 .
Residuals 19 140.037  7.3704                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Key observations:</strong> both tests still detect differences; Kruskal-Wallis is more robust to violations; the parametric test may give misleading results when assumptions are violated; the non-parametric test maintains validity.</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_of_variance_lecture_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" alt="Jittered scatterplot of rank-transformed phase shift by treatment for the deliberately violated dataset, with diamond points marking each group's mean rank, illustrating why Kruskal-Wallis stays valid when raw values are heavily skewed or contain outliers." width="307"></p>
</figure>
</div>
</div>
</div>
<p><strong>Why Kruskal-Wallis is robust:</strong> uses ranks instead of raw values, outliers affect ranks minimally, unequal variances are less problematic, no distribution assumptions are needed.</p>
</div>
</div>
</section>
<section id="post-hoc-tests-for-kruskal-wallis-pairwise-wilcoxon" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-tests-for-kruskal-wallis-pairwise-wilcoxon">Post-Hoc Tests for Kruskal-Wallis — Pairwise Wilcoxon</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Just like ANOVA, we need post-hoc tests to identify which groups differ:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum exact test 

data:  nonparam_circ_df$phase_shift and nonparam_circ_df$treatment 

      Control Eyes  
Eyes  0.0037  -     
Knees 1.0000  0.0787

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p><strong>Interpretation of p-values:</strong> Control vs Eyes: p = 0.024 (significant); Control vs Knees: p = 1.000 (not significant); Eyes vs Knees: p = 0.078 (not significant).</p>
<p><strong>Common adjustment methods:</strong> <code>"bonferroni"</code> (most conservative), <code>"holm"</code> (less conservative), <code>"BH"</code> (Benjamini-Hochberg, controls false discovery rate), <code>"none"</code> (not recommended).</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>pairwise_violated_result <span class="ot">&lt;-</span> <span class="fu">pairwise.wilcox.test</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> violated_circ_df<span class="sc">$</span>phase_shift_violated,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">g =</span> violated_circ_df<span class="sc">$</span>treatment,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>pairwise_violated_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum exact test 

data:  violated_circ_df$phase_shift_violated and violated_circ_df$treatment 

      Control Eyes  
Eyes  0.0037  -     
Knees 1.0000  1.0000

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Original Data Pairwise p-values:
   Control vs Eyes:  0.024 *
   Control vs Knees: 1.000
   Eyes vs Knees:    0.078</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Violated Data Pairwise p-values:
   Control vs Eyes:  0.015 *
   Control vs Knees: 1.000
   Eyes vs Knees:    0.015 *</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="dunns-test-an-alternative-post-hoc" class="level2">
<h2 class="anchored" data-anchor-id="dunns-test-an-alternative-post-hoc">Dunn’s Test — an Alternative Post-Hoc</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Dunn’s test is specifically designed for Kruskal-Wallis post-hoc comparisons:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>dunn_original_result <span class="ot">&lt;-</span> <span class="fu">dunnTest</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  phase_shift <span class="sc">~</span> treatment,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> circ_data,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>dunn_original_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Comparison          Z     P.unadj      P.adj
1  Control - Eyes  2.7789287 0.005453849 0.01636155
2 Control - Knees  0.1434629 0.885924641 1.00000000
3    Eyes - Knees -2.5517789 0.010717452 0.03215236</code></pre>
</div>
</div>
<p><strong>Advantages:</strong> designed specifically for Kruskal-Wallis, provides Z-statistics in addition to p-values, multiple adjustment methods available, more appropriate than multiple Wilcoxon tests. A Z-statistic tells you how many standard deviations a difference is from the expected value (usually zero, “no difference”).</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>dunn_violated_result <span class="ot">&lt;-</span> <span class="fu">dunnTest</span>(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  phase_shift_violated <span class="sc">~</span> treatment,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> violated_circ_df,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"bonferroni"</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>dunn_violated_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Comparison         Z     P.unadj      P.adj
1  Control - Eyes  2.614212 0.008943349 0.02683005
2 Control - Knees  1.126449 0.259975463 0.77992639
3    Eyes - Knees -1.440520 0.149720243 0.44916073</code></pre>
</div>
</div>
<p><strong>Interpreting Z-statistics:</strong> large |Z| values indicate bigger differences; Z &gt; 1.96 is approximately equivalent to p &lt; 0.05; the sign indicates the direction of the difference.</p>
</div>
</div>
</section>
<section id="which-post-hoc-test-should-you-use" class="level2">
<h2 class="anchored" data-anchor-id="which-post-hoc-test-should-you-use">Which Post-Hoc Test Should You Use?</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>Use Dunn’s test</strong> because it’s the proper follow-up to Kruskal-Wallis, maintains consistency with the overall K-W ranking, is more statistically appropriate for the omnibus test you ran, and is standard in published research</li>
<li>Wilcoxon is fine for simple two-group comparisons, but once you’ve run Kruskal-Wallis (a 3+ group test), Dunn’s is the standard choice</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>🖐 Notice</strong></p>
<p>Kruskal-Wallis ranks ALL your data once. Dunn’s test uses those same ranks. Pairwise Wilcoxon throws away that information and re-ranks separately for each pair.</p>
</div>
</div>
</div>
</div>
</section>
<section id="reporting-non-parametric-results" class="level2">
<h2 class="anchored" data-anchor-id="reporting-non-parametric-results">Reporting Non-Parametric Results</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Essential elements to include:</strong> test name and purpose, sample sizes per group, medians and IQRs (not means and SDs!), test statistic (H) and degrees of freedom, p-value, effect size, post-hoc test results, conclusion.</p>
<p><strong>Example write-up:</strong> “A Kruskal-Wallis test was conducted to compare the effect of light treatment on circadian rhythm phase shift across three groups: Control (n = 8), Knees (n = 7), and Eyes (n = 7). Median phase shifts were −0.48 hours (IQR = 0.84) for Control, −0.29 hours (IQR = 1.04) for Knees, and −1.48 hours (IQR = 0.66) for Eyes. The test revealed a statistically significant difference in phase shift between the groups, H(2) = 8.66, p = 0.013, ε² = 0.37. Post-hoc pairwise comparisons using Dunn’s test with Bonferroni correction indicated that the Eyes treatment differed significantly from Control (p = 0.024), but no other pairwise differences were significant.”</p>
</div><div class="column" style="width:40%;">
<p><strong>In-text citation format:</strong></p>
<blockquote class="blockquote">
<p>The Kruskal-Wallis test revealed significant differences between treatment groups, H(2) = 8.66, p = .013.</p>
</blockquote>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>⚠️ Common mistakes to avoid</strong></p>
<ul>
<li>Reporting means instead of medians, using SD instead of IQR</li>
<li>Not mentioning it’s a non-parametric test</li>
<li>Not justifying why a non-parametric test was used</li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="reporting-the-table-format" class="level2">
<h2 class="anchored" data-anchor-id="reporting-the-table-format">Reporting — the Table Format</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Table 1. Descriptive Statistics for Phase Shift by Treatment

 

Note. IQR = interquartile range.
 Kruskal-Wallis H(2) = 8.66, p = .013</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  treatment     n Median   IQR   Min   Max
  &lt;fct&gt;     &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Control       8 -0.485 0.89  -1.27  0.53
2 Eyes          7 -1.48  0.675 -2.83 -0.78
3 Knees         7 -0.29  0.93  -1.61  0.73</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script>
// Open the "RevealJS" entry in the "Other Formats" panel in a new tab,
// so clicking it for a live lecture doesn't navigate away from this page.
document.addEventListener("DOMContentLoaded", function () {
  document
    .querySelectorAll('.quarto-alternate-formats a[href$=".slides.html"]')
    .forEach(function (link) {
      link.setAttribute("target", "_blank");
      link.setAttribute("rel", "noopener");
    });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/ecostats_2026");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 UMD Biostatistics</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/wlperry">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:wlperry@d.umn.edu">
      <i class="bi bi-envelope-heart-fill" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>