<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – ANCOVA</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-b8eef193cd4aecd129dcd97c8f413977.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="ANCOVA – UMD Biostatistics">
<meta property="og:description" content="Hands-on activity: analysis of covariance.">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">ANCOVA</h1>
  <p class="subtitle">Covariates</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry 
</div>
</div>
</div>

</section>
<section>
<section id="lecture-15-analysis-of-covariance-ancova" class="title-slide slide level1 center">
<h1>Lecture 15: Analysis of Covariance (ANCOVA)</h1>

</section>
<section id="what-is-ancova" class="slide level2">
<h2>What is ANCOVA?</h2>
<ul>
<li>ANCOVA (Analysis of Covariance) combines regression and ANOVA to:
<ul>
<li>Compare group means while adjusting for a continuous covariate</li>
<li>Increase statistical power by reducing residual error</li>
<li>Control for confounding variables</li>
</ul></li>
</ul>
</section>
<section id="when-to-use-ancova" class="slide level2">
<h2>When to Use ANCOVA</h2>
<ul>
<li>Use ANCOVA when you have:
<ul>
<li><strong>Response variable</strong>: Continuous</li>
<li><strong>Predictor variable</strong>: Categorical (factor/groups)</li>
<li><strong>Covariate</strong>: Continuous variable that affects the response</li>
</ul></li>
</ul>
</section>
<section id="key-assumptions-of-ancova" class="slide level2 scrollable">
<h2>Key Assumptions of ANCOVA</h2>
<ol type="1">
<li><strong>Independence</strong> of observations</li>
<li><strong>Normality</strong> of residuals</li>
<li><strong>Homogeneity of variances</strong> across groups</li>
<li><strong>Linearity</strong> between response and covariate within each group</li>
<li><strong>Homogeneity of slopes</strong> (most critical!) - regression slopes must be not significantly different across all groups</li>
</ol>
<div class="callout callout-important callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical First Step</strong></p>
</div>
<div class="callout-content">
<p>Always test for <strong>homogeneity of slopes</strong> before proceeding with ANCOVA. If slopes differ significantly between groups, standard ANCOVA is inappropriate.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-1-cricket-chirping-analysis" class="title-slide slide level1 center">
<h1>Part 1: Cricket Chirping Analysis</h1>

</section>
<section id="data-overview" class="slide level2">
<h2>Data Overview</h2>
<p>We want to compare chirping rate of two cricket species: - <em>Oecanthus exclamationis</em> - <em>Oecanthus niveus</em></p>
<p>But we measured rates at different temperatures, and there’s a relationship between pulse rate and temperature. ANCOVA lets us adjust for temperature effect to get a more powerful test!</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               spp     temp chirp_rate
1 O. exclamationis 19.31296   40.69557
2 O. exclamationis 23.24355   51.78799
3 O. exclamationis 23.60175   50.75553
4 O. exclamationis 19.22222   40.80589
5 O. exclamationis 20.57129   50.16484
6 O. exclamationis 21.35188   46.24225</code></pre>
</div>
</div>

<img data-src="ancova_activity_files/figure-revealjs/cricket-visualization-1.png" width="576" class="r-stretch"></section>
<section id="step-1-test-homogeneity-of-slopes" class="slide level2">
<h2>Step 1: Test Homogeneity of Slopes</h2>
<p>This is the most critical assumption! We test if the regression slopes are equal across all groups.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: chirp_rate
             Sum Sq Df  F value                Pr(&gt;F)    
(Intercept)  133.06  1  19.7625            0.00008062 ***
temp        1372.62  1 203.8707 &lt; 0.00000000000000022 ***
spp           69.76  1  10.3617              0.002724 ** 
temp:spp      26.08  1   3.8734              0.056796 .  
Residuals    242.38 36                                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: - p &gt; 0.05, slopes homogeneous - proceed with ANCOVA - p &lt; 0.05, slopes differ and standard ANCOVA is inappropriate</p>
<h3 id="the-contrasts-setting-changes-the-specific-hypothesis-being-tested-for-your-main-effects.">The contrasts setting changes the specific hypothesis being tested for your main effects.</h3>
<ul>
<li>contr.treatment the test for temp is testing the effect of temperature only for the reference species (O. exclamationis)</li>
<li>one level of factor is the “reference” level (“O. exclamationis” comes first alphabetically).</li>
<li>is mean chirp_rate equal to zero for the reference species (“O. exclamationis”) when temp is 0?</li>
</ul>
<h3 id="with-contr.sum-test-for-temp-is-testing-the-average-effect-of-temperature-across-both-species.">With contr.sum, test for temp is testing the average effect of temperature across both species.</h3>
<ul>
<li>“sum coding” or “deviation coding.”</li>
<li>compares each factor level to the grand mean</li>
<li>is average mean chirp_rate (averaged across both species) equal to zero when temp is 0?</li>
</ul>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Intercept is hard to interpret in both models because temp = 0 is meaningless - center temp variable (e.g., temp_c = temp - mean(temp)) - run model - intercept would then test the chirp_rate at the average temperature - much more interpretable</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="step-2-fit-ancova-model" class="title-slide slide level1 center">
<h1>Step 2: Fit ANCOVA Model</h1>
<p>Since slopes are homogeneous (p &gt; 0.05), fit ANCOVA model without interaction term</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = chirp_rate ~ temp + spp, data = c_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.0065 -1.9653  0.1923  0.7886  5.9192 

Coefficients:
            Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept) -19.1014     4.7795  -3.997             0.000295 ***
temp          2.7926     0.2048  13.634 0.000000000000000530 ***
spp1          5.9003     0.4296  13.733 0.000000000000000424 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.694 on 37 degrees of freedom
Multiple R-squared:  0.8994,    Adjusted R-squared:  0.894 
F-statistic: 165.4 on 2 and 37 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<ul>
<li>Interpretation
<ul>
<li>spp1 is clue that contr.sum is active</li>
<li>represents coefficient for first species (O. exclamationis) relative to grand mean.</li>
<li>(Intercept): -19.1014 - average chirp_rate (across both species) when temp is 0</li>
<li>temp: 2.7926 - common slope- for every 1-degree increase in temp- chirp_rate increases by 2.7926 units</li>
<li>spp1: 5.9003- spp1 coefficient - deviation from grand mean for first species- O. exclamationis</li>
<li>effect for O. niveus is assumed to be -5.9003</li>
</ul></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: chirp_rate
           Sum Sq Df F value                Pr(&gt;F)    
temp      1348.81  1  185.90 0.0000000000000005296 ***
spp       1368.34  1  188.59 0.0000000000000004236 ***
Residuals  268.46 37                                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Both Type II (technically more appropriate) and Type III end up doing the exact same calculation:</p>
<ul>
<li>test for temp gets the Sum of Squares for temp after accounting for spp.</li>
<li>test for spp gets the Sum of Squares for spp after accounting for temp.</li>
</ul>
</section>
<section id="step-3-check-model-assumptions" class="slide level2">
<h2>Step 3: Check Model Assumptions</h2>

<img data-src="ancova_activity_files/figure-revealjs/cricket-assumptions-1.png" width="480" class="r-stretch"><div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  ancova_model$residuals
W = 0.96208, p-value = 0.1971</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  0.3897 0.5362
      38               </code></pre>
</div>
</div>
<p>Breusch-Pagan (BP) Test for homoscedasticity</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  ancova_model
BP = 1.0098, df = 2, p-value = 0.6036</code></pre>
</div>
</div>
</section>
<section id="step-4-calculate-adjusted-means" class="slide level2">
<h2>Step 4: Calculate Adjusted Means</h2>
<p>ANCOVA compares adjusted means - what each group’s mean would be at the overall mean of the covariate.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> spp                emmean        SE df lower.CL upper.CL
 O. exclamationis 51.70513 0.6049702 37 50.47934 52.93091
 O. niveus        39.90462 0.6049702 37 38.67883 41.13040

Confidence level used: 0.95 </code></pre>
</div>
</div>
</section>
<section id="step-5-pairwise-comparisons" class="slide level2">
<h2>Step 5: Pairwise Comparisons</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> contrast                     estimate    SE df t.ratio p.value
 O. exclamationis - O. niveus     11.8 0.859 37  13.733 &lt;0.0001</code></pre>
</div>
</div>
</section>
<section id="step-6-visualize-results" class="slide level2">
<h2>Step 6: Visualize Results</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="ancova_activity_files/figure-revealjs/cricket-results-plot-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="ancova_activity_files/figure-revealjs/cricket_ggplot-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</section></section>
<section>
<section id="part-2-partridge-longevity-analysis" class="title-slide slide level1 center">
<h1>Part 2: Partridge Longevity Analysis</h1>

</section>
<section id="data-overview-1" class="slide level2">
<h2>Data Overview</h2>
<p>We’ll analyze the effect of mating strategy on male fruitfly longevity, using thorax length as a covariate.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  partners type      treat longev  llongev thorax     resid1 predict1
1        8    0 No females     35 1.544068   0.64  -5.868456 40.86846
2        8    0 No females     37 1.568202   0.68  -9.301196 46.30120
3        8    0 No females     49 1.690196   0.68   2.698804 46.30120
4        8    0 No females     46 1.662758   0.72  -5.733936 51.73394
5        8    0 No females     63 1.799341   0.72  11.266064 51.73394
6        8    0 No females     39 1.591065   0.76 -18.166676 57.16668
       resid2 predict2
1 -0.04743024 1.591498
2 -0.07105067 1.639252
3  0.05094369 1.639252
4 -0.02424867 1.687007
5  0.11233405 1.687007
6 -0.14369601 1.734761</code></pre>
</div>
</div>

<img data-src="ancova_activity_files/figure-revealjs/p_df-visualization-1.png" width="576" class="r-stretch"></section>
<section id="step-1-test-homogeneity-of-slopes-1" class="slide level2">
<h2>Step 1: Test Homogeneity of Slopes</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: longev
              Sum Sq  Df  F value                Pr(&gt;F)    
(Intercept)   2963.8   1  26.0142           0.000001349 ***
thorax       12805.8   1 112.3988 &lt; 0.00000000000000022 ***
treat           36.9   4   0.0810                0.9881    
thorax:treat    42.5   4   0.0933                0.9844    
Residuals    13102.1 115                                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="step-2-fit-ancova-model-1" class="slide level2">
<h2>Step 2: Fit ANCOVA Model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = longev ~ thorax + treat, data = p_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-26.189  -6.599  -0.989   6.408  30.244 

Coefficients:
            Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)  -54.062     10.255  -5.272          0.000000612 ***
thorax       135.819     12.439  10.919 &lt; 0.0000000000000002 ***
treat1         8.006      1.890   4.237          0.000044991 ***
treat2         4.077      1.889   2.158             0.032935 *  
treat3         6.730      1.881   3.578             0.000502 ***
treat4        -2.940      1.891  -1.554             0.122749    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.51 on 119 degrees of freedom
Multiple R-squared:  0.6564,    Adjusted R-squared:  0.6419 
F-statistic: 45.46 on 5 and 119 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: longev
           Sum Sq  Df F value                Pr(&gt;F)    
thorax    13168.9   1 119.219 &lt; 0.00000000000000022 ***
treat      9611.5   4  21.753    0.0000000000001719 ***
Residuals 13144.7 119                                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="step-3-check-assumptions" class="slide level2">
<h2>Step 3: Check Assumptions</h2>

<img data-src="ancova_activity_files/figure-revealjs/p_df-assumptions-1.png" width="480" class="r-stretch"><div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  p_ancova_model$residuals
W = 0.99174, p-value = 0.6689</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value Pr(&gt;F)
group   4  0.6535 0.6255
      120               </code></pre>
</div>
</div>
<p>Breusch-Pagan (BP) Test for homoscedasticity</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  p_ancova_model
BP = 11.763, df = 5, p-value = 0.03818</code></pre>
</div>
</div>
</section>
<section id="step-4-calculate-adjusted-means-1" class="slide level2">
<h2>Step 4: Calculate Adjusted Means</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> treat                           emmean   SE  df lower.CL upper.CL
 No females                        65.4 2.11 119     61.3     69.6
 One virgin female daily           61.5 2.11 119     57.3     65.7
 Eight virgin females daily        64.2 2.10 119     60.0     68.3
 One inseminated female daily      54.5 2.11 119     50.3     58.7
 Eight inseminated females daily   41.6 2.12 119     37.4     45.8

Confidence level used: 0.95 </code></pre>
</div>
</div>
</section>
<section id="step-5-pairwise-comparisons-1" class="slide level2">
<h2>Step 5: Pairwise Comparisons</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                                       estimate   SE
 No females - One virgin female daily                               3.93 3.00
 No females - Eight virgin females daily                            1.28 2.98
 No females - One inseminated female daily                         10.95 3.00
 No females - Eight inseminated females daily                      23.88 2.97
 One virgin female daily - Eight virgin females daily              -2.65 2.98
 One virgin female daily - One inseminated female daily             7.02 2.97
 One virgin female daily - Eight inseminated females daily         19.95 3.01
 Eight virgin females daily - One inseminated female daily          9.67 2.98
 Eight virgin females daily - Eight inseminated females daily      22.60 2.99
 One inseminated female daily - Eight inseminated females daily    12.93 3.01
  df t.ratio p.value
 119   1.311  0.6849
 119   0.428  0.9929
 119   3.650  0.0035
 119   8.031 &lt;0.0001
 119  -0.891  0.8996
 119   2.361  0.1336
 119   6.636 &lt;0.0001
 119   3.249  0.0129
 119   7.560 &lt;0.0001
 119   4.298  0.0003

P value adjustment: tukey method for comparing a family of 5 estimates </code></pre>
</div>
</div>

<img data-src="ancova_activity_files/figure-revealjs/unnamed-chunk-8-1.png" width="576" class="r-stretch"><div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> treat                           emmean   SE  df lower.CL upper.CL .group
 Eight inseminated females daily   41.6 2.12 119     37.4     45.8  1    
 One inseminated female daily      54.5 2.11 119     50.3     58.7   2   
 One virgin female daily           61.5 2.11 119     57.3     65.7   23  
 Eight virgin females daily        64.2 2.10 119     60.0     68.3    3  
 No females                        65.4 2.11 119     61.3     69.6    3  

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 5 estimates 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
</section></section>
<section>
<section id="part-3-example-with-heterogeneous-slopes" class="title-slide slide level1 center">
<h1>Part 3: Example with Heterogeneous Slopes</h1>
<p>Example where slopes are <strong>NOT</strong> homogeneous using sea urchin data.</p>

<img data-src="ancova_activity_files/figure-revealjs/unnamed-chunk-10-1.png" width="576" class="r-stretch"></section>
<section id="test-for-homogeneity-of-slopes" class="slide level2">
<h2>Test for Homogeneity of Slopes</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: suture_width
                    Sum Sq Df F value                Pr(&gt;F)    
(Intercept)      0.0093295  1  104.97  0.000000000000002828 ***
volume           0.0197876  1  222.63 &lt; 0.00000000000000022 ***
treatment        0.0020070  2   11.29  0.000060644383975751 ***
volume:treatment 0.0062129  2   34.95  0.000000000044525318 ***
Residuals        0.0058662 66                                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Result</strong>: With p &lt; 0.05 - heterogeneous slopes! - Standard ANCOVA inappropriate here</p>
</section>
<section id="what-to-do-with-heterogeneous-slopes" class="slide level2">
<h2>What to do with Heterogeneous Slopes</h2>
<p>When slopes are not homogeneous have several options:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = suture_width ~ volume, data = filter(u_df, treatment == 
    "Initial"))

Coefficients:
(Intercept)       volume  
   0.051785     0.001926  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = suture_width ~ volume, data = filter(u_df, treatment == 
    "Low Food"))

Coefficients:
(Intercept)       volume  
  0.0359532    0.0005453  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = suture_width ~ volume, data = filter(u_df, treatment == 
    "High Food"))

Coefficients:
(Intercept)       volume  
   0.014077     0.003376  </code></pre>
</div>
</div>
</section></section>
<section id="option-2---johnson-neyman-procedure" class="title-slide slide level1 center">
<h1>Option 2 - Johnson-Neyman procedure</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>SIMPLE SLOPES ANALYSIS

Slope of volume when treatment = Initial: 

  Est.   S.E.   t val.      p
------ ------ -------- ------
  0.00   0.00     9.87   0.00

Slope of volume when treatment = Low Food: 

  Est.   S.E.   t val.      p
------ ------ -------- ------
  0.00   0.00     2.47   0.02

Slope of volume when treatment = High Food: 

  Est.   S.E.   t val.      p
------ ------ -------- ------
  0.00   0.00    13.06   0.00</code></pre>
</div>
</div>
</section>

<section>
<section id="summary-checklist-for-ancova" class="title-slide slide level1 center scrollable">
<h1>Summary Checklist for ANCOVA</h1>
<p>When conducting ANCOVA, always follow these steps:</p>
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>ANCOVA Checklist</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Visualize your data</strong> - plot response vs covariate, colored by groups</li>
<li><strong>Test homogeneity of slopes</strong> - fit model with interaction term
<ul>
<li>If p &gt; 0.05: proceed with ANCOVA</li>
<li>If p &lt; 0.05: use alternative approaches</li>
</ul></li>
<li><strong>Fit ANCOVA model</strong> - response ~ covariate + factor</li>
<li><strong>Check assumptions</strong> - use diagnostic plots</li>
<li><strong>Interpret results</strong> - focus on adjusted means, not raw means</li>
<li><strong>Conduct post-hoc tests</strong> - pairwise comparisons if needed</li>
<li><strong>Visualize results</strong> - show adjusted means with confidence intervals</li>
</ol>
</div>
</div>
</div>
</section>
<section id="key-points-to-remember" class="slide level2 scrollable">
<h2>Key Points to Remember</h2>
<ul>
<li><strong>ANCOVA increases power</strong> by accounting for covariate variation</li>
<li><strong>Adjusted means</strong> are what we compare, not raw group means</li>
<li><strong>Homogeneity of slopes</strong> is the most critical assumption</li>
<li><strong>Parallel lines</strong> in plot suggest homogeneous slopes</li>
<li><strong>Non-parallel lines</strong> indicate heterogeneous slopes - use alternative methods</li>
</ul>
<div class="callout callout-important callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Points from ANCOVA Analysis</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>Test homogeneity of slopes first</strong> - most critical assumption</li>
<li><strong>ANCOVA compares adjusted means</strong> at the mean value of the covariate</li>
<li><strong>Increases statistical power</strong> by removing variation due to the covariate</li>
<li><strong>Choose appropriate methods</strong> based on whether slopes are homogeneous</li>
<li><strong>Visualize your results</strong> showing relationship between variables</li>
<li><strong>Check all assumptions</strong> using diagnostic plots</li>
<li><strong>Interpret in biological context</strong> - what do the adjusted means tell us?</li>
</ol>
<p>Remember: covariate should be measured independently of the treatment and should not be affected by the treatment itself!</p>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/ecostats_2026");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>