<!DOCTYPE html>
<html lang="en"><head>
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Bill Perry">
  <title>UMD Biostatistics – Lecture: Non-Parametric T-Tests</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-f3d32509bb0d2f779b0d504f04cffa98.css">
  <link rel="stylesheet" href="../../css/main.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Lecture: Non-Parametric T-Tests – UMD Biostatistics">
<meta property="og:description" content="Rank-based tests on our own pine needle data — where the assumptions hold and the tests cost us power — then lake trout mass, where the assumptions genuinely fail and robust, rank-based, and permutation tests earn their keep.">
<meta property="og:site_name" content="UMD Biostatistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture: Non-Parametric T-Tests</h1>
  <p class="subtitle">Rank-based tests</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bill Perry
</div>
</div>
</div>

</section>
<section id="where-we-left-off" class="slide level2">
<h2>Where We Left Off</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>A brief review:</p>
<ul>
<li>Hypotheses</li>
<li>One- and two-sided t-tests</li>
<li>One-sample, two-sample, and <strong>paired</strong> t-tests — and how much more the paired test got out of the same four trees</li>
<li><strong>Assumptions of parametric tests</strong></li>
<li>What next — when assumptions fail!
<ul>
<li>we will always cover parametric tests first</li>
<li>then non-parametric approaches</li>
<li>later, other approaches use the appropriate underlying distribution when it isn’t normal, but Poisson or other</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea from last lecture</strong></p>
<p>A t-test’s p-value is only trustworthy if its assumptions hold. Today is about how to tell whether they do — and what to do when they don’t.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ The trap we’re walking into first</strong></p>
<p>It is tempting to treat non-parametric tests as the “safe” option you can always fall back on. We are going to start by showing why that instinct is wrong.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/pine_needles.jpg" style="width:3.12in;height:2.08in"></p>
<figcaption>Photo comparing needle length and bundle count across six pine species (Pinus ponderosa, nigra, resinosa, strobus, sylvestris, banksiana).</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="todays-overview" class="slide level2 scrollable">
<h2>Today’s Overview</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Today runs in two halves, and the order matters:</p>
<ol type="1">
<li><strong>Our own pine needles first.</strong> We check the assumptions on the data <em>you</em> collected, find that they hold, measure <strong>how big</strong> the effect actually was with Cohen’s d, and then run the non-parametric tests anyway — to see exactly what they cost.</li>
<li><strong>Then the lake trout.</strong> A dataset where the assumptions are genuinely, badly broken — which is where robust tests, rank-based tests, and permutation tests earn their keep.</li>
</ol>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The question behind today</strong></p>
<p>Not <em>“which test is safest?”</em> but <em>“which test does this data deserve?”</em></p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/pine_needles.jpg" style="width:3.12in;height:2.08in"></p>
<figcaption>Photo comparing needle length and bundle count across six pine species (Pinus ponderosa, nigra, resinosa, strobus, sylvestris, banksiana).</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/lake_trout.jpg" style="width:3.12in;height:1.38in"></p>
<figcaption>Illustration of a lake trout in profile, showing its mottled brown-and-cream coloring and forked tail, the species whose weight and length data are used in the second half of this lecture.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="part-1-start-with-our-own-data" class="slide level2 divider">
<h2>Part 1 · Start With Our Own Data</h2>
</section>
<section id="our-pine-needles-where-we-left-them" class="slide level2">
<h2>Our pine needles, where we left them</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a aria-label="2"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-3"><a aria-label="3"></a><span class="fu">library</span>(car)          <span class="co"># leveneTest()</span></span>
<span id="cb1-4"><a aria-label="4"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-5"><a aria-label="5"></a><span class="fu">library</span>(perm)         <span class="co"># permutation tests</span></span>
<span id="cb1-6"><a aria-label="6"></a><span class="fu">library</span>(effectsize)   <span class="co"># cohens_d()</span></span>
<span id="cb1-7"><a aria-label="7"></a></span>
<span id="cb1-8"><a aria-label="8"></a><span class="fu">source</span>(<span class="st">"themes_functions/r_themes_and_functions.R"</span>)</span>
<span id="cb1-9"><a aria-label="9"></a></span>
<span id="cb1-10"><a aria-label="10"></a>pine_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/pine_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-label="1"></a><span class="co"># same two-stage summary as last week: one value per tree per side</span></span>
<span id="cb2-2"><a aria-label="2"></a>p_df <span class="ot">&lt;-</span> pine_df <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a aria-label="3"></a>  <span class="fu">group_by</span>(team, side) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a aria-label="4"></a>  <span class="fu">summarise</span>(<span class="at">needle_length_mm =</span> <span class="fu">mean</span>(needle_length_mm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-5"><a aria-label="5"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb2-6"><a aria-label="6"></a></span>
<span id="cb2-7"><a aria-label="7"></a>p_wide_df <span class="ot">&lt;-</span> p_df <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a aria-label="8"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> side, <span class="at">values_from =</span> needle_length_mm)</span>
<span id="cb2-9"><a aria-label="9"></a></span>
<span id="cb2-10"><a aria-label="10"></a>p_wide_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  team       shady sunny
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;
1 botany      16.1  17.3
2 grace_jace  15.4  15.5
3 one         13.2  14.2
4 waterbugs   11.7  13.8</code></pre>
</div>
</div>
<p><a href="data/pine_data.csv" class="btn btn-primary" download="pine_data.csv">📥 Pine needle data</a> <a href="data/lake_trout.csv" class="btn btn-primary" download="lake_trout.csv">📥 Lake trout data</a> <a href="data/sage_brush_crickets_feeding_mating.csv" class="btn btn-primary" download="sage_brush_crickets_feeding_mating.csv">📥 Sagebrush cricket data</a></p>
<p><a href="themes_functions/r_themes_and_functions.R" class="btn btn-primary" download="r_themes_and_functions.R">📥 Tools script</a> <a href="data/07_nonparametric_t_tests.R" class="btn btn-primary" download="07_nonparametric_t_tests.R">📥 Script skeleton</a></p>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Reminder</strong></p>
<p>4 teams, 4 trees, both sides of each tree. The data are <strong>paired</strong> by design.</p>
<p>Last week these four trees gave us:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Unpaired two-sample t</td>
<td style="text-align: right;">0.425</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Paired t</strong></td>
<td style="text-align: right;"><strong>0.072</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Same two tools as last week</strong></p>
<p><code>source()</code> gives you <code>theme_regular()</code> and <code>summary_stats()</code> again. Nothing new to learn.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="do-our-assumptions-actually-hold" class="slide level2">
<h2>Do our assumptions actually hold?</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>🔮 Predict first:</strong> Before we run anything — do you expect needle length to be normally distributed with equal variance on the two sides of a tree? Commit to an answer.</p>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:60%;">
<p>Before reaching for anything non-parametric, we have to establish that we <em>need</em> it. Same two checks as last week.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-label="1"></a><span class="co"># normality, one side at a time -- all 32 needles per side</span></span>
<span id="cb4-2"><a aria-label="2"></a><span class="fu">shapiro.test</span>(pine_df<span class="sc">$</span>needle_length_mm[pine_df<span class="sc">$</span>side <span class="sc">==</span> <span class="st">"sunny"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  pine_df$needle_length_mm[pine_df$side == "sunny"]
W = 0.96105, p-value = 0.2934</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-label="1"></a><span class="fu">shapiro.test</span>(pine_df<span class="sc">$</span>needle_length_mm[pine_df<span class="sc">$</span>side <span class="sc">==</span> <span class="st">"shady"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  pine_df$needle_length_mm[pine_df$side == "shady"]
W = 0.98213, p-value = 0.8586</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-label="1"></a><span class="co"># equal variance</span></span>
<span id="cb8-2"><a aria-label="2"></a><span class="fu">leveneTest</span>(needle_length_mm <span class="sc">~</span> <span class="fu">factor</span>(side), <span class="at">data =</span> pine_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1   2e-04 0.9887
      62               </code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Everything passes</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Check</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Shapiro-Wilk, sunny</td>
<td style="text-align: right;">0.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shapiro-Wilk, shady</td>
<td style="text-align: right;">0.86</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Levene’s</td>
<td style="text-align: right;">0.99</td>
</tr>
</tbody>
</table>
<p>Remember the direction of these tests: <strong>H₀ is that the assumption holds.</strong> A large p means we have no evidence against it.</p>
<p>There is <strong>nothing wrong with this data.</strong> The paired t-test we ran last week was entitled to every bit of its p = 0.072.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 So why are we here?</strong></p>
<p>Because “my data are fine” is a conclusion you have to <em>earn</em>, not assume — and because plenty of students would have reached for a rank test anyway, thinking it was the cautious choice. Let’s find out what that caution would have cost.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="effect-size-how-big-not-just-whether" class="slide level2">
<h2>Effect Size — How Big, Not Just Whether</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Our paired t-test gave <strong>p = 0.072</strong>. The usual reflex is to call that “not significant” and stop.</p>
<p>But <code>p</code> never told us the one thing a reader actually wants to know: <strong>how much shorter are shady needles?</strong> A p-value answers <em>“could this be noise?”</em> — not <em>“does this matter?”</em></p>
<p><strong>Cohen’s d</strong> answers the second question. It is the difference between the groups expressed in <strong>standard deviations</strong>, so it has no units and can be compared across studies:</p>
<p><span class="math display">\[d = \frac{\bar{x}_1 - \bar{x}_2}{s}\]</span></p>
<p>For a <strong>paired</strong> design the difference is the paired difference, and <code>s</code> is the standard deviation <em>of those differences</em>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-label="1"></a>diffs <span class="ot">&lt;-</span> p_wide_df<span class="sc">$</span>shady <span class="sc">-</span> p_wide_df<span class="sc">$</span>sunny</span>
<span id="cb10-2"><a aria-label="2"></a></span>
<span id="cb10-3"><a aria-label="3"></a><span class="fu">mean</span>(diffs) <span class="sc">/</span> <span class="fu">sd</span>(diffs)     <span class="co"># Cohen's d, by hand</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.361371</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Read the formula out loud</strong></p>
<p>“The shady side averaged <strong>1.36 standard deviations</strong> below the sunny side.”</p>
<p>That sentence stands on its own. It does not depend on how many trees we sampled, and it would mean the same thing to someone measuring a different pine species in a different forest.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Cohen’s rough conventions</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">|d|</th>
<th style="text-align: left;">Label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.2</td>
<td style="text-align: left;">small</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.5</td>
<td style="text-align: left;">medium</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.8</td>
<td style="text-align: left;">large</td>
</tr>
</tbody>
</table>
<p>Ours is <strong>1.36</strong>. These are rules of thumb, not laws — what counts as “large” is a question about pine trees, not about statistics.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="why-we-report-it-what-d-tells-us-that-p-could-not" class="slide level2">
<h2>Why We Report It — What d Tells Us That p Could Not</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Here is the relationship that explains everything:</p>
<p><span class="math display">\[t = d \times \sqrt{n}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-label="1"></a><span class="fl">2.7227</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">4</span>)      <span class="co"># our t statistic, over root n</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.36135</code></pre>
</div>
</div>
<p><strong>The t-statistic is the effect size multiplied by the square root of your sample size.</strong> So a p-value confounds two completely different things: <em>how big the effect is</em>, and <em>how hard you looked</em>.</p>
<ul>
<li>A <strong>huge</strong> effect with n = 4 → large p.&nbsp;That is us.</li>
<li>A <strong>trivial</strong> effect with n = 10,000 → tiny p, and no biological meaning at all.</li>
</ul>
<p>Effect size separates them. That is why journals, and every reporting guideline written in the last twenty years, ask for it alongside the p-value.</p>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-label="1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb14-2"><a aria-label="2"></a></span>
<span id="cb14-3"><a aria-label="3"></a><span class="fu">cohens_d</span>(p_wide_df<span class="sc">$</span>shady,</span>
<span id="cb14-4"><a aria-label="4"></a>         p_wide_df<span class="sc">$</span>sunny,</span>
<span id="cb14-5"><a aria-label="5"></a>         <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |        95% CI
-------------------------
-1.36     | [-2.74, 0.10]</code></pre>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Look at that confidence interval: [-2.74, 0.10]</strong></p>
<p><em>This</em> is the honest summary of our four trees: the effect is <strong>probably large and probably negative</strong>, but with n = 4 we cannot rule out zero.</p>
<p>Notice that the CI crossing zero is the same fact as p &gt; 0.05 — but it says it far more usefully. “No significant difference” sounds like <em>we found nothing</em>. “d = -1.36, CI [-2.74, 0.10]” says <em>we found a large effect we could not pin down</em>, which is a completely different message to a reader, and the correct one.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Where this goes next</strong></p>
<p>Effect size is the input to a <strong>power analysis</strong> — given d, how many trees would we have needed? That is next week’s lecture.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="ranks-in-one-slide" class="slide level2">
<h2>Ranks, in one slide</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Every non-parametric test today works the same way: <strong>throw away the measurements, keep only their order.</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-label="1"></a>p_df <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a aria-label="2"></a>  <span class="fu">mutate</span>(<span class="at">rank =</span> <span class="fu">rank</span>(needle_length_mm)) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a aria-label="3"></a>  <span class="fu">arrange</span>(rank)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  team       side  needle_length_mm  rank
  &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt;
1 waterbugs  shady             11.7     1
2 one        shady             13.2     2
3 waterbugs  sunny             13.8     3
4 one        sunny             14.2     4
5 grace_jace shady             15.4     5
6 grace_jace sunny             15.5     6
7 botany     shady             16.1     7
8 botany     sunny             17.3     8</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ What just happened</strong></p>
<p>The shortest tree-side average became rank 1, the longest rank 8. A needle that was 4 mm longer than its neighbour and one that was 0.1 mm longer are now <strong>exactly one rank apart</strong>.</p>
<p>That is the whole trade. You become immune to outliers and to any weird distribution — and in exchange you give up the magnitudes.</p>
<p>A rank-based test then asks: <em>are the ranks of one group systematically higher than the other’s?</em></p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Watch for the statistic</strong></p>
<p>Rank tests report <strong><code>W</code></strong> (Mann-Whitney) or <strong><code>V</code></strong> (signed-rank), never <code>t</code>. If you see a <code>W</code>, you are reading rank-based output.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="running-both-rank-based-tests" class="slide level2">
<h2>Running both rank-based tests</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-label="1"></a><span class="co"># Unpaired: Mann-Whitney U  (the t-test's two-sample partner)</span></span>
<span id="cb18-2"><a aria-label="2"></a><span class="fu">wilcox.test</span>(needle_length_mm <span class="sc">~</span> side, <span class="at">data =</span> p_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  needle_length_mm by side
W = 5, p-value = 0.4857
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-label="1"></a><span class="co"># Paired: Wilcoxon signed-rank  (the paired t-test's partner)</span></span>
<span id="cb20-2"><a aria-label="2"></a><span class="fu">wilcox.test</span>(p_wide_df<span class="sc">$</span>shady, p_wide_df<span class="sc">$</span>sunny, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank exact test

data:  p_wide_df$shady and p_wide_df$sunny
V = 0, p-value = 0.125
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Notice <code>V = 0</code></strong></p>
<p>The signed-rank statistic is <strong>zero</strong> — meaning <em>every single tree</em> moved in the same direction. There is no arrangement of these four trees that would look more consistent.</p>
<p>Notice too that R says <strong>“exact test”</strong> for both. With no tied values it enumerates every possible arrangement rather than approximating. Hold on to that word — the next slide explains why it matters.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="same-answer-less-power" class="slide level2">
<h2>Same answer, less power</h2>
<div class="columns">
<div class="column" style="width:60%;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th>Parametric</th>
<th>Non-parametric</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Unpaired (2 groups)</td>
<td>t-test <strong>p = 0.425</strong></td>
<td>Mann-Whitney <strong>p = 0.486</strong></td>
</tr>
<tr class="even">
<td>Paired (4 trees)</td>
<td>paired t <strong>p = 0.072</strong></td>
<td>signed-rank <strong>p = 0.125</strong></td>
</tr>
</tbody>
</table>
<p><strong>Both methods tell the same story:</strong></p>
<ul>
<li>the unpaired comparison finds nothing</li>
<li>the paired comparison is far more sensitive</li>
<li>the direction is identical — shady needles shorter</li>
</ul>
<p><strong>But the rank test costs you.</strong> In both rows the non-parametric p-value is larger. That is the price of throwing away the actual measurements and keeping only their order — and we paid it on data that never needed it.</p>
</div><div class="column" style="width:40%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ At n = 4, the signed-rank test hits a wall</strong></p>
<p>With 4 pairs there are only 2⁴ = <strong>16</strong> possible arrangements of plus and minus signs. The most extreme possible result — all four the same way, which is exactly what we got — has a two-sided p of 2/16 = <strong>0.125</strong>.</p>
<p>So with four trees, a Wilcoxon signed-rank test <strong>can never return a p-value below 0.125</strong>, no matter how enormous the effect.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-label="1"></a><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span><span class="sc">^</span><span class="dv">4</span>     <span class="co"># smallest possible two-sided p, 4 pairs</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.125</code></pre>
</div>
</div>
<p>The test did not fail to find our effect. It was <strong>arithmetically incapable</strong> of declaring it significant.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="what-that-means-in-practice" class="slide level2">
<h2>What that means in practice</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Non-parametric tests are the right call when normality is genuinely broken and cannot be fixed</li>
<li>But they are <strong>not free</strong>, and they are <strong>not a safe default</strong></li>
<li>At small n they can be so blunt that no result could ever reach significance — check the floor <strong>before</strong> you run one</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea</strong></p>
<p>Choose the test that matches your data’s distribution, not the one that feels safest. For our four trees, the <em>parametric</em> paired t-test — whose assumptions we just checked and could not reject — is the more honest and more informative choice.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Try it yourself</strong></p>
<p>How many pairs would you need before a signed-rank test could reach p &lt; 0.05?</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-label="1"></a><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span><span class="sc">^</span><span class="dv">5</span>    <span class="co"># 5 pairs</span></span>
<span id="cb24-2"><a aria-label="2"></a><span class="dv">2</span> <span class="sc">/</span> <span class="dv">2</span><span class="sc">^</span><span class="dv">6</span>    <span class="co"># 6 pairs</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Where we go next</strong></p>
<p>We have now seen what these tests cost. What we have <strong>not</strong> seen is what they buy you — because nothing about the pine data was broken.</p>
<p>For that we need a dataset that is a genuine mess.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-2-a-dataset-where-the-assumptions-really-do-fail" class="slide level2 divider">
<h2>Part 2 · A Dataset Where the Assumptions Really Do Fail</h2>
</section>
<section id="meet-the-lake-trout" class="slide level2">
<h2>Meet the lake trout</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-label="1"></a>lt_df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/lake_trout.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a aria-label="1"></a>lt_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(lake) <span class="sc">%&gt;%</span> <span class="fu">reframe</span>(<span class="fu">summary_stats</span>(mass_g))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  lake            n  mean    sd    se ci_lower ci_upper
  &lt;chr&gt;       &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 I8             91  857.  727.  76.2     705.    1008.
2 Island Lake    10 3165  1617. 511.     2008.    4322.
3 N 01          674  659.  395.  15.2     629.     689.
4 NE 12         322  534.  520.  29.0     477.     591.
5 NE 14         139  848.  508.  43.1     763.     933.
6 Toolik        249  518.  373.  23.6     471.     564.</code></pre>
</div>
</div>
<p><a href="data/lake_trout.csv" class="btn btn-primary" download="lake_trout.csv">📥 Lake trout data</a></p>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Notice the design</strong></p>
<p>Six lakes of trout: <code>sampling_site</code>, <code>species</code>, <code>length_mm</code>, <code>mass_g</code>, <code>lake</code>.</p>
<p><strong>Everything from here on uses <code>mass_g</code>.</strong> Look hard at the <code>n</code> and <code>sd</code> columns for <strong>NE 12</strong> and <strong>Island Lake</strong> — 322 fish against 10, and very different spreads.</p>
<p>That imbalance is the rest of the lecture. Where the pine data was clean, this is everything that can go wrong at once.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-3-assumptions-of-parametric-tests" class="slide level2 divider">
<h2>Part 3 · Assumptions of Parametric Tests</h2>
</section>
<section id="parametric-vs.-non-parametric-tests" class="slide level2">
<h2>Parametric vs.&nbsp;Non-Parametric Tests</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>T-tests are <strong>parametric</strong> tests.</p>
<ul>
<li><strong>Parametric tests:</strong>
<ul>
<li>specify/assume the probability distribution the parameters came from</li>
<li>basic assumptions of parametric t-tests: random sampling, normality, equal variance (or Welch’s t-test), no outliers</li>
</ul></li>
<li><strong>Non-parametric tests:</strong> no assumption about the probability distribution/normality
<ul>
<li>Mukasa et al.&nbsp;2021, DOI: 10.4236/ojbm.2021.93081</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reference</strong></p>
<p>Whitlock &amp; Schluter, <em>Analysis of Biological Data</em>, Ch. 13 — Handling Violations of Assumptions, is the core reference for this whole lecture.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-2948249782.png" style="width:3.12in;height:2.66in"></p>
<figcaption>Flowchart of hypothesis tests branching into parametric and nonparametric tests, each split into one-sample and two-sample (independent vs.&nbsp;paired) tests, listing specific tests under each branch (e.g., t test and z test under parametric one-sample; Mann-Whitney and Wilcoxon under nonparametric two-sample).</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="assumptions-of-parametric-tests-overview" class="slide level2">
<h2>Assumptions of Parametric Tests — Overview</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>If a parametric test’s assumptions are violated, the test becomes unreliable</li>
<li>This is because the test statistic may no longer follow the distribution it’s supposed to</li>
<li>Most parametric tests are robust to mild/moderate violations of normality</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-286482702.png" style="width:3.12in;height:2.6in"></p>
<figcaption>Three probability density curves for a right-skewed distribution family at different sigma values (0.25, 0.5, 1) with mu = 0, showing how larger sigma produces a flatter, more spread-out, and less peaked skewed curve.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="assumptions-random-sampling" class="slide level2">
<h2>Assumptions — Random Sampling</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Basic assumptions of parametric t-tests: random sampling, normality, equal variance, no outliers.</p>
<p><strong>Random sampling:</strong></p>
<ul>
<li>samples are randomly collected from populations; part of experimental design</li>
<li>necessary for sample → population inference</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-2526616735.png" style="width:2.52in;height:3.03in"></p>
<figcaption>Diagram of a large circle labeled ‘population’ full of dots, with orange arrows showing a subset being drawn down into a small circle labeled ‘sample’, illustrating random sampling from a population.</figcaption>
</figure>
</div>
</div></div>
</section>
<section id="assumptions-normality-testing" class="slide level2">
<h2>Assumptions — Normality Testing</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>🔮 Predict first:</strong> We’re about to look at histogram, dotplot, boxplot, and QQ-plot views of the <em>same</em> NE 12 mass data. Which of the four do you expect to be most convincing about normality?</p>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:60%;">
<p>Let’s test normality for one lake — <strong><code>NE 12</code></strong> — as if we were going to run a one-sample t-test. We need a new data frame with only NE 12 data, called <code>ne12_data</code>.</p>
<p><strong>Normality:</strong> samples from a normally distributed population</p>
<ul>
<li>Graphical tests: histograms, dotplots, boxplots, <strong>QQ-plots</strong></li>
<li>“Formal” tests: <strong>Shapiro-Wilk test</strong> — sometimes not useful</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nonparametric_t_tests_lecture_files/figure-revealjs/nonparametric-t-tests-03-1.png" alt="Four-panel figure showing the mass distribution of Lake NE 12 trout as a histogram, a dotplot, a boxplot, and a QQ-plot, used to visually assess whether the data are approximately normally distributed." width="384"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="shapiro-wilk-test-for-normality" class="slide level2">
<h2>Shapiro-Wilk Test for Normality</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>H₀ is that the data ARE normally distributed</strong> — so a <em>small</em> p-value rejects normality.</p>
<ul>
<li>Graphical tests: histograms, dotplots, boxplots, <strong>QQ-plots</strong></li>
<li>“Formal” tests: <strong>Shapiro-Wilk</strong> — sometimes not useful</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ p prints as <code>&lt; 2.2e-16</code></strong></p>
<p>That is R telling you the p-value is smaller than it will bother to print. Not a borderline call — NE 12 mass is <strong>strongly</strong> non-normal, exactly as the histogram and QQ-plot showed. This is the case the rest of the lecture is for.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-label="1"></a><span class="fu">shapiro.test</span>(ne12_data<span class="sc">$</span>mass_g)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  ne12_data$mass_g
W = 0.85148, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
</div></div>
</section>
<section id="testing-the-equal-variance-assumption" class="slide level2">
<h2>Testing the Equal Variance Assumption</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Equal variance:</strong> samples are from populations with a similar degree of variability.</p>
<p>Equal variance is about <strong>two groups</strong>, so here we bring in the comparison we will use for the rest of the lecture: <strong>NE 12 vs.&nbsp;Island Lake</strong>.</p>
<ul>
<li>Graphical test: boxplots</li>
<li>Formal test: <strong>Levene’s test</strong> — H₀ is “the variances are equal,” so you <em>want</em> p &gt; 0.05</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-label="1"></a>isl_ne12_df <span class="ot">&lt;-</span> lt_df <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a aria-label="2"></a>  <span class="fu">filter</span>(lake <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"NE 12"</span>, <span class="st">"Island Lake"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a aria-label="3"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(mass_g))</span>
<span id="cb30-4"><a aria-label="4"></a></span>
<span id="cb30-5"><a aria-label="5"></a>isl_ne12_df <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a aria-label="6"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(lake, mass_g)) <span class="sc">+</span></span>
<span id="cb30-7"><a aria-label="7"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb30-8"><a aria-label="8"></a>  <span class="fu">theme_regular</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nonparametric_t_tests_lecture_files/figure-revealjs/nonparametric-t-tests-05-1.png" alt="Boxplot of trout mass for Lake NE 12 and Island Lake, showing Island Lake fish are far heavier and far more variable." width="307"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-label="1"></a><span class="fu">leveneTest</span>(mass_g <span class="sc">~</span> <span class="fu">factor</span>(lake), <span class="at">data =</span> isl_ne12_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value    Pr(&gt;F)    
group   1  25.997 5.775e-07 ***
      330                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>p is far below 0.05 — the variances are not equal.</strong></p>
</div></div>
</section>
<section id="testing-for-outliers" class="slide level2">
<h2>Testing for Outliers</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>No outliers:</strong> no “extreme” values very different from the rest of the sample.</p>
<ul>
<li>Graphical tests: boxplots, histograms</li>
<li>“Formal tests”: Grubbs’ test — no one really does this</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Watch out!</strong></p>
<p>Outliers are a problem for non-parametric tests as well — switching to a rank-based test doesn’t make an outlier stop mattering.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nonparametric_t_tests_lecture_files/figure-revealjs/nonparametric-t-tests-07-1.png" alt="Stacked histogram and boxplot of Lake NE 12 trout mass, used to visually check for outliers." width="307"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-4-when-assumptions-fail" class="slide level2 divider">
<h2>Part 4 · When Assumptions Fail</h2>
</section>
<section id="alternative-tests-when-assumptions-fail" class="slide level2">
<h2>Alternative Tests When Assumptions Fail</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>What if t-test assumptions fail? Alternative tests, with more relaxed assumptions, are available. In which case would you use each?</p>
<ul>
<li><strong>Welch’s t-test:</strong> <em>distribution normal but variance unequal</em></li>
<li><strong>Mann-Whitney-Wilcoxon test:</strong> <em>distribution not normal and/or outliers present (but both groups should still have similar distributions and ~equal variance)</em></li>
<li><strong>Permutation test for two samples:</strong> <em>distribution not normal (but both groups should still have similar distributions and ~equal variance)</em></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nonparametric_t_tests_lecture_files/figure-revealjs/nonparametric-t-tests-08-1.png" alt="Stacked histogram, boxplot, and QQ-plot of Lake NE 12 trout mass, shown together to help decide which alternative test to use when t-test assumptions are questionable." width="307"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="understanding-qq-plots" class="slide level2">
<h2>Understanding QQ-Plots</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>QQ-plots:</strong> a tool for assessing normality.</p>
<ul>
<li>On x: theoretical quantiles from a standard normal distribution</li>
<li>On y: ordered sample values</li>
<li>Deviation from normal can be detected as deviation from a straight line</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nonparametric_t_tests_lecture_files/figure-revealjs/nonparametric-t-tests-09-1.png" alt="Side-by-side boxplot and QQ-plot of trout mass for Lake NE 12 and Island Lake, colored by lake, used to compare the two groups' distributions and assess normality." width="326"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="data-transformations" class="slide level2">
<h2>Data Transformations</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>In some cases, data can be mathematically “transformed” to meet the assumptions of parametric tests. This usually involves:</p>
<ul>
<li>log₁₀ transformations</li>
<li>square root transformations</li>
<li>and many others</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-label="1"></a>log_box_plot <span class="ot">&lt;-</span> isl_ne12_df <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a aria-label="2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(lake, <span class="fu">log10</span>(mass_g))) <span class="sc">+</span></span>
<span id="cb33-3"><a aria-label="3"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb33-4"><a aria-label="4"></a>  <span class="fu">theme_regular</span>(<span class="at">base_size =</span> <span class="dv">9</span>)</span>
<span id="cb33-5"><a aria-label="5"></a></span>
<span id="cb33-6"><a aria-label="6"></a>ne12_island_box_plot <span class="sc">+</span> log_box_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nonparametric_t_tests_lecture_files/figure-revealjs/nonparametric-t-tests-10-1.png" alt="Side-by-side boxplots comparing raw trout mass to log10-transformed trout mass for Lake NE 12 and Island Lake, showing the log transformation narrowing the gap in spread between the two lakes." width="326"></p>
</figure>
</div>
</div>
</div>
<p>The log scale pulls the two spreads much closer together — but it does <strong>not</strong> fix them completely. Levene’s test on <code>log10(mass_g)</code> is still significant.</p>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/transformations_2 jpg.jpg" style="width:3.12in;height:2.68in"></p>
<figcaption>Reference chart of six common data transformations (square root, logarithm, inverse, and their ‘reflect and’ variants for left-skewed data), each shown as a small curve with its transformation formula, used to pick a transformation that matches a variable’s skew shape.</figcaption>
</figure>
</div>
<p><a href="https://www.elsblog.org/the_empirical_legal_studi/2006/08/variable_transf.html">source</a></p>
</div></div>
</section>
<section id="data-transformations-why-log" class="slide level2">
<h2>Data Transformations — Why Log?</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Log isn’t a trick you try at random — it fixes a specific shape of problem:</p>
<ul>
<li>Right-skewed data (a long tail of large values) → <code>log10(x)</code></li>
<li>Effects that are <strong>multiplicative</strong> rather than additive (doubling a value, not adding a fixed amount) → <code>log10(x)</code></li>
<li>Ratio-scale ecological measurements — mass, concentration, population size, area — are almost always multiplicative</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The mechanism, in one line</strong></p>
<p>A trout that is twice as heavy as another isn’t “500 g more” — it’s “2×.” Log turns that multiplicative relationship into an additive one, which is what a t-test’s equal-spread assumption expects. It compresses the right tail: 100 g → 1000 g and 1000 g → 10,000 g become the <em>same</em> distance, one log unit.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="data-transformations-beyond-log" class="slide level2">
<h2>Data Transformations — Beyond Log</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Log is the one you will reach for most in ecology, but match the transform to the shape of the problem:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Transformation</th>
<th>Use when…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>log10(x)</code></td>
<td>right-skewed, multiplicative, ratio-scale data (mass, concentration, abundance)</td>
</tr>
<tr class="even">
<td><code>sqrt(x)</code></td>
<td>count data, moderate right skew (Poisson-like variance)</td>
</tr>
<tr class="odd">
<td><code>asin(sqrt(x))</code></td>
<td>proportions or percentages bounded 0–1</td>
</tr>
<tr class="even">
<td><code>1/x</code></td>
<td>rates, or extreme right skew that log doesn’t fix</td>
</tr>
<tr class="odd">
<td>Box-Cox</td>
<td>no obvious transform works — let the data pick the power</td>
</tr>
</tbody>
</table>
<p><strong>None of these are guaranteed to work.</strong> You check afterward, every time — that’s Part 5 of the worksheet, and it’s the whole point of the take-home.</p>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a aria-label="1"></a>sqrt_box_plot <span class="ot">&lt;-</span> isl_ne12_df <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a aria-label="2"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(lake, <span class="fu">sqrt</span>(mass_g))) <span class="sc">+</span></span>
<span id="cb34-3"><a aria-label="3"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb34-4"><a aria-label="4"></a>  <span class="fu">theme_regular</span>(<span class="at">base_size =</span> <span class="dv">9</span>)</span>
<span id="cb34-5"><a aria-label="5"></a></span>
<span id="cb34-6"><a aria-label="6"></a>log_box_plot <span class="sc">+</span> sqrt_box_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nonparametric_t_tests_lecture_files/figure-revealjs/nonparametric-t-tests-28-1.png" alt="Side-by-side boxplots comparing log10-transformed and square-root-transformed trout mass for Lake NE 12 and Island Lake." width="326"></p>
</figure>
</div>
</div>
</div>
<p><code>sqrt()</code> narrows the spread less than <code>log10()</code> did here — this skew behaves more like a multiplicative effect than a count.</p>
</div></div>
</section>
<section id="a-transformation-can-fix-one-problem-not-the-other" class="slide level2">
<h2>A Transformation Can Fix One Problem, Not the Other</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-label="1"></a><span class="fu">leveneTest</span>(<span class="fu">log10</span>(mass_g) <span class="sc">~</span> <span class="fu">factor</span>(lake), <span class="at">data =</span> isl_ne12_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value    Pr(&gt;F)    
group   1   11.77 0.0006784 ***
      330                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Compare that to the Levene’s result on raw <code>mass_g</code> a few slides back — both fail. <strong>Normality improved with the log transform. Equal variance did not.</strong> Checking a transformation is not one pass/fail box — you re-test <em>every</em> assumption, separately, on the transformed variable.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ This is the take-home’s whole trap</strong></p>
<p>The sagebrush cricket data works the same way: a transformation can help one assumption without rescuing the other. There is no single “correct” test hiding in the data — there’s a <strong>best-justified</strong> one. Check every assumption on the raw data, then again on any transformed version, before you decide.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-5-welchs-t-test-a-one-slide-refresher" class="slide level2 divider">
<h2>Part 5 · Welch’s T-Test — a One-Slide Refresher</h2>
</section>
<section id="welchs-t-test-why-it-exists-in-one-number" class="slide level2">
<h2>Welch’s t-Test — why it exists, in one number</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>You met Welch’s last week: <strong>same t-statistic idea, separate variance estimates, fractional degrees of freedom.</strong> Nothing new to learn. What is new is <em>this dataset</em>, which shows you why it matters.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a aria-label="1"></a><span class="co"># Student's -- assumes equal variances</span></span>
<span id="cb37-2"><a aria-label="2"></a><span class="fu">t.test</span>(mass_g <span class="sc">~</span> lake, <span class="at">data =</span> isl_ne12_df, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  mass_g by lake
t = 14.181, df = 330, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Island Lake and group NE 12 is not equal to 0
95 percent confidence interval:
 2266.304 2996.360
sample estimates:
mean in group Island Lake       mean in group NE 12 
                3165.0000                  533.6677 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a aria-label="1"></a><span class="co"># Welch's -- does not</span></span>
<span id="cb39-2"><a aria-label="2"></a><span class="fu">t.test</span>(mass_g <span class="sc">~</span> lake, <span class="at">data =</span> isl_ne12_df, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  mass_g by lake
t = 5.1368, df = 9.0578, p-value = 0.0006016
alternative hypothesis: true difference in means between group Island Lake and group NE 12 is not equal to 0
95 percent confidence interval:
 1473.676 3788.989
sample estimates:
mean in group Island Lake       mean in group NE 12 
                3165.0000                  533.6677 </code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>⚠️ Same data. Same means. Sixty orders of magnitude apart.</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Student’s</td>
<td style="text-align: right;">14.18</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;"><strong>5.7 × 10⁻³⁶</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Welch’s</td>
<td style="text-align: right;">5.14</td>
<td style="text-align: right;"><strong>9.06</strong></td>
<td style="text-align: right;"><strong>0.0006</strong></td>
</tr>
</tbody>
</table>
<p>(R only prints <code>&lt; 2.2e-16</code> for the first one — that is the smallest number it will show you. The true value is 5.7 × 10⁻³⁶.)</p>
<p>Look at the <strong>df</strong>. Student’s pooled 322 Island-sized fish with 10 NE 12-sized ones and claimed <strong>330 degrees of freedom</strong>. Welch’s looked at the same data and said: you really only have about <strong>9</strong>.</p>
<p>Both still reject H₀ — but Student’s was never entitled to that much confidence. With n = 322 vs 10 and Levene’s p ≈ 6 × 10⁻⁷, the pooled variance is meaningless.</p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 The rule</strong></p>
<p>Unequal n <strong>and</strong> unequal variance is exactly the combination Welch’s was built for. When in doubt, <code>var.equal = FALSE</code> is the safer default — it costs you almost nothing when variances really are equal.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-6-rank-based-tests" class="slide level2 divider">
<h2>Part 6 · Rank-Based Tests</h2>
</section>
<section id="rank-based-tests-now-on-data-that-needs-them" class="slide level2">
<h2>Rank-Based Tests — now on data that needs them</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Same two tests you ran on the pine needles in Part 1 — ranks instead of measurements, no assumption about the distribution.</p>
<ul>
<li>Ranks of data: observations are assigned ranks; sums (and signs, for paired tests) of ranks for groups are compared</li>
<li><strong>Mann-Whitney U test</strong> — common alternative to the independent-samples t-test</li>
<li><strong>Wilcoxon signed-rank test</strong> — alternative to the paired t-test</li>
<li>Assumptions: similar distributions for groups, equal variance</li>
<li>Less power than parametric tests</li>
<li>Best when normality can’t be met by transformation (weird distribution) or there are large outliers</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ The difference from Part 1</strong></p>
<p>On the pine needles the rank test was a <strong>cost</strong> — we gave up power on data that was already well behaved.</p>
<p>Here, NE 12 mass is non-normal at p &lt; 2.2 × 10⁻¹⁶ and full of outliers. There is nothing to give up. <strong>This</strong> is the case the test was built for.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>📖 Reference</strong></p>
<p>Whitlock &amp; Schluter, Ch. 13, covers the Mann-Whitney U test and Wilcoxon signed-rank test as the standard rank-based alternatives.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="mann-whitney-u-test-results" class="slide level2">
<h2>Mann-Whitney U Test Results</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a aria-label="1"></a>wilcox_test_result <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(mass_g <span class="sc">~</span> lake, <span class="at">data =</span> isl_ne12_df)</span>
<span id="cb41-2"><a aria-label="2"></a></span>
<span id="cb41-3"><a aria-label="3"></a>wilcox_test_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  mass_g by lake
W = 3205.5, p-value = 9.506e-08
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 <code>W</code> again, and no “exact” this time</strong></p>
<p>The statistic is <code>W</code>, not <code>t</code> — rank-based output, as in Part 1.</p>
<p>But notice what R <em>doesn’t</em> say: with 332 fish and plenty of tied masses it cannot enumerate every arrangement, so this is the <strong>normal approximation</strong>, not an exact test. At this sample size that is fine — the floor problem that crippled our four trees does not exist here.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="part-7-permutation-tests" class="slide level2 divider">
<h2>Part 7 · Permutation Tests</h2>
</section>
<section id="permutation-tests-concept" class="slide level2">
<h2>Permutation Tests — Concept</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Permutation tests are based on resampling: reshuffling the original data</li>
<li>Resampling allows parameter estimation when the distribution is unknown, including SEs and CIs of statistics (means, medians)</li>
<li>A common approach is the bootstrap: resample with replacement many times, recalculate sample stats</li>
<li>We use the <code>perm</code> package</li>
<li>H₀: µ_A = µ_B, Hₐ: µ_A ≠ µ_B</li>
<li>Calculates the difference Δ in means between two groups</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="nonparametric_t_tests_lecture_files/figure-revealjs/nonparametric-t-tests-18-1.png" alt="Boxplot comparing trout mass between Lake NE 12 and Island Lake, colored by lake, shown as context for the permutation test comparing means between the two groups." width="307"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="permutation-tests-method" class="slide level2">
<h2>Permutation Tests — Method</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Randomly reshuffle observations between groups (keeping n₍NE 12₎ = 322 and n₍Island₎ = 10), calculate Δ</li>
<li>Repeat &gt; 1,000 times</li>
<li>Record the proportion of the differences in means as extreme as (or more extreme than) observed</li>
<li>This is equivalent to a p-value, and can be used in the “traditional” hypothesis-testing framework</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 For a graphical explanation</strong></p>
<p><a href="https://www.jwilber.me/permutationtest/">jwilber.me/permutationtest</a></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="permutation-test-implementation" class="slide level2">
<h2>Permutation Test Implementation</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>In R, using the <code>perm</code> package. Assumptions: both groups have a similar distribution; equal variance.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a aria-label="1"></a><span class="fu">library</span>(perm)</span>
<span id="cb43-2"><a aria-label="2"></a></span>
<span id="cb43-3"><a aria-label="3"></a><span class="co"># Balance the design: take 10 NE 12 fish, keep all of Island Lake</span></span>
<span id="cb43-4"><a aria-label="4"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb43-5"><a aria-label="5"></a>perm_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb43-6"><a aria-label="6"></a>  isl_ne12_df <span class="sc">%&gt;%</span></span>
<span id="cb43-7"><a aria-label="7"></a>    <span class="fu">filter</span>(lake <span class="sc">==</span> <span class="st">"NE 12"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-8"><a aria-label="8"></a>    <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">10</span>),</span>
<span id="cb43-9"><a aria-label="9"></a>  isl_ne12_df <span class="sc">%&gt;%</span></span>
<span id="cb43-10"><a aria-label="10"></a>    <span class="fu">filter</span>(lake <span class="sc">==</span> <span class="st">"Island Lake"</span>)</span>
<span id="cb43-11"><a aria-label="11"></a>)</span>
<span id="cb43-12"><a aria-label="12"></a></span>
<span id="cb43-13"><a aria-label="13"></a><span class="co"># The difference the test is about</span></span>
<span id="cb43-14"><a aria-label="14"></a>perm_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(lake) <span class="sc">%&gt;%</span> <span class="fu">reframe</span>(<span class="fu">summary_stats</span>(mass_g))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  lake            n  mean    sd    se ci_lower ci_upper
  &lt;chr&gt;       &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 Island Lake    10 3165  1617.  511.    2008.    4322.
2 NE 12          10  645.  538.  170.     260.    1030.</code></pre>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a aria-label="1"></a><span class="fu">permTS</span>(mass_g <span class="sc">~</span> lake,</span>
<span id="cb45-2"><a aria-label="2"></a>       <span class="at">data =</span> perm_df,</span>
<span id="cb45-3"><a aria-label="3"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb45-4"><a aria-label="4"></a>       <span class="at">method =</span> <span class="st">"exact.mc"</span>,</span>
<span id="cb45-5"><a aria-label="5"></a>       <span class="at">control =</span> <span class="fu">permControl</span>(<span class="at">nmc =</span> <span class="dv">10000</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact Permutation Test Estimated by Monte Carlo

data:  mass_g by lake
p-value = 2e-04
alternative hypothesis: true mean lake=Island Lake - mean lake=NE 12 is not equal to 0
sample estimates:
mean lake=Island Lake - mean lake=NE 12 
                                 2519.9 

p-value estimated from 10000 Monte Carlo replications
99 percent confidence interval on p-value:
 0.000000000 0.001059383 </code></pre>
</div>
</div>
</div></div>
</section>
<section id="part-8-summary" class="slide level2 divider">
<h2>Part 8 · Summary</h2>
</section>
<section id="summary-testing-assumptions" class="slide level2">
<h2>Summary — Testing Assumptions</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Key assumptions:</strong></p>
<ul>
<li><strong>Random sampling</strong> — samples are randomly collected from populations</li>
<li><strong>Normality</strong> — data follows a normal distribution</li>
<li><strong>Equal variance</strong> — samples come from populations with similar variability</li>
<li><strong>No outliers</strong> — no extreme values that can skew results</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Assessing assumptions</strong></p>
<ul>
<li>Key to do <em>every time</em></li>
<li>Should be acknowledged in the manuscript</li>
</ul>
</div>
</div>
</div>
</div></div>
</section>
<section id="summary-effect-size" class="slide level2">
<h2>Summary — Effect Size</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>Always report an effect size next to your p-value.</strong></p>
<ul>
<li><strong>Cohen’s d</strong> = the difference between groups, in standard deviations — unitless, and comparable across studies</li>
<li><strong>t = d × √n</strong>, so a p-value confounds <em>how big the effect is</em> with <em>how hard you looked</em></li>
<li>A <strong>confidence interval on d</strong> says what a bare “n.s.” never can: whether you found nothing, or found something you could not pin down</li>
<li>Effect size is also the input to a power analysis — next week</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ On our four trees</strong></p>
<p>Paired <strong>d = −1.36</strong>, CI [−2.74, 0.10], p = 0.072. A large effect, imprecisely measured. Reporting only “p = 0.072, n.s.” would have thrown that away.</p>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 In a results sentence</strong></p>
<blockquote>
<p>Needles on the shady side were 1.09 mm shorter than on the sunny side (paired <em>t</em>₃ = −2.72, <em>p</em> = 0.072, <em>d</em> = −1.36, 95% CI [−2.74, 0.10]).</p>
</blockquote>
<p>Every number there does work the others cannot.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="summary-data-transformations" class="slide level2">
<h2>Summary — Data Transformations</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>When assumptions aren’t met, transformations may help normalize data:</p>
<ul>
<li><strong>Log transformation:</strong> <code>log10(x)</code> — useful for right-skewed data, multiplicative effects</li>
<li><strong>Square root:</strong> <code>sqrt(x)</code> — useful for count data, moderately right-skewed distributions</li>
<li><strong>Box-Cox:</strong> a more flexible family of power transformations</li>
<li>More specialized transformations exist, especially for percentages or proportions</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Recall</strong></p>
<p>We saw <code>log10()</code> shrink the gap between the NE 12 and Island Lake boxplots earlier — that’s the transformation working.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="summary-parametric-test-options" class="slide level2">
<h2>Summary — Parametric Test Options</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>1. Standard t-test</strong></p>
<p>Strengths:</p>
<ul>
<li>High statistical power when assumptions are met</li>
<li>Well understood and widely accepted</li>
</ul>
<p>Weaknesses:</p>
<ul>
<li>Sensitive to violations of normality, equal variance</li>
<li>Heavily influenced by outliers</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>2. Welch’s t-test</strong></p>
<p>Covered in full in the <strong>T-Tests</strong> lecture; the one-slide refresher in Part 5 is all we needed today.</p>
<ul>
<li>Robust to unequal variances <strong>and</strong> unequal n — which is exactly our NE 12 vs.&nbsp;Island Lake case</li>
<li>Still <strong>parametric</strong>: it fixes the variance assumption, not the normality one</li>
<li>Costs almost nothing when variances really are equal, so it is a safe default</li>
<li>On these data it moved df from <strong>330 to 9.06</strong> — that is the whole story</li>
</ul>
</div></div>
</section>
<section id="summary-non-parametric-options" class="slide level2">
<h2>Summary — Non-Parametric Options</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>3. Mann-Whitney-Wilcoxon test</strong></p>
<p>Strengths:</p>
<ul>
<li>Non-parametric: doesn’t assume normal distribution</li>
<li>Robust against outliers</li>
<li>Works with ordinal data</li>
</ul>
<p>Weaknesses:</p>
<ul>
<li>Less statistical power than parametric tests</li>
<li>Still assumes similar distributions and approximately equal variance</li>
<li>Tests median differences rather than mean differences</li>
<li><strong>At small n there is a hard floor on the p-value</strong> — with 4 pairs a signed-rank test cannot go below 0.125 (see Part 1)</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>4. Permutation tests</strong></p>
<p>Strengths:</p>
<ul>
<li>Distribution-free: doesn’t assume a specific distribution</li>
<li>Can be applied to many types of test statistics</li>
<li>Valid at small n — the p-value is exact, not an approximation</li>
<li>Directly estimates p-values through resampling</li>
</ul>
<p>Weaknesses:</p>
<ul>
<li>Computationally intensive</li>
<li>Assumes exchangeability under the null hypothesis</li>
<li>Requires similar distributions and equal variance</li>
<li><strong>Hits the same small-n floor as the rank tests</strong> — being exact is not the same as being powerful, because there are only so many ways to rearrange 8 numbers</li>
</ul>
</div></div>
</section>
<section id="key-takeaway" class="slide level2">
<h2>Key Takeaway</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Statistical tests have different strengths and assumptions. The choice should be guided by your data’s characteristics, not just convenience.</p>
<p><strong>Always visualize your data before deciding on the appropriate test.</strong></p>
</div><div class="column" style="width:40%;">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>✅ Key idea</strong></p>
<p>Standard t-test → Welch’s → Mann-Whitney/Permutation isn’t a strict ladder of “better” tests — each answers a slightly different question (means vs.&nbsp;medians) under different assumptions. Pick based on what your data actually looks like.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="looking-ahead-the-take-home" class="slide level2 scrollable">
<h2>Looking Ahead — The Take-Home</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p>Part 8 of the worksheet (sagebrush crickets, due before Study Design &amp; Sampling) hands you a new dataset and asks <strong>you</strong> to run the whole decision process from today:</p>
<ol type="1">
<li>Check normality and equal variance on the raw data</li>
<li>Try a transformation if the raw data doesn’t pass</li>
<li>Check normality and equal variance <strong>again</strong>, on the transformed data — don’t assume it worked</li>
<li>Pick a test, justify the pick, and report it properly</li>
</ol>
<p>There is no lecture slide that tells you the answer this time.</p>
</div><div class="column" style="width:40%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>🖐 Remember from today</strong></p>
<p><code>log10()</code> fixed normality for the lake trout but <strong>not</strong> equal variance. Expect the crickets to behave similarly — a transformation earning partial credit is a completely normal outcome, not a sign you did something wrong.</p>
</div>
</div>
</div>
</div></div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // Bounds for smallest/largest possible scale to apply to content
        minScale: 0.2,

        maxScale: 2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/wlperry\.github\.io\/ecostats_2026");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>